### ISSUE TITLE
[Search] Links that are opened in new tabs are not filtered out from Search if they don't meet the criteria

### ISSUE THREAD

**Issue by Softvision-VladBacia** [bwinton/TabCenter#1004]
**[Affected versions]:**
-Firefox 51.0.1 and above
-Tab Center 1.31.0 (release version)

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Tab Center was installed from Test Pilot.
-Have a few webpages opened in multiple tabs.
-In `about:preferences#general` page, set the option "Show my windows and tabs from last time" and restart the browser.

**[Steps to reproduce]:**
1. Go to a website and open multiple links in different tabs.
2. Click the Search input field from Tab Center.
3. Write a string that contains the name of a webpage.
4. Delete the string and close one of the tabs that contain a webpage from prerequisites.
5. Perform a search for a random string that doesn't exist.

**[Expected result]:**
3. All webpages that are not corresponding to the search parameters are filtered out.
5. Search should not break and "x more tabs" button is always displayed for hidden webpages.

**[Actual result]:**
3. The new opened webpages are not filtered out.
5. The "x more tabs" button is not displayed and the search feature is broken. Search no longer works for the webpages from prerequisites. 

**[Notes]:**
- The issue is no longer reproducible after restarting the browser. After opening new webpages in new tabs the issue will reproduce with the above steps.
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiTEZMeFQ2TGp3RlE) is the video for this issue.

**Comment by ericawright** [comment]
I've seen this too - will look into it

**Comment by SoftVision-PaulOiegas** [comment]
Verified this on today custom made repository build and it no longer seems to reproduce. 👍
