### ISSUE TITLE
Add option to disable Tab Previews

### ISSUE THREAD

**Issue by Technohacker** [bwinton/TabCenter#1008]
Hey devs :)
It'd be nice to have a configuration option for disabling the tab previews.
It's a bit demanding on CPU (16% constantly) and therefore, keeps my fans spinning and drains my laptop battery.
After disabling the addon, Firefox goes back to low CPU and power usage.

Firefox Version: Firefox Developer Edition v53.0a2
OS: Arch Linux (Kernel 4.10)

Keep up the good work! :)

**Comment by Keith94** [comment]
There's a hidden option in about:config, change `extensions.verticaltabs.largetabs` value to 0

**Comment by Technohacker** [comment]
@Keith94 excellent, just like i needed it :)
Will close for now, do make sure that this is configurable in the release
Thanks!
