### ISSUE TITLE
The Bookmarks "pointer position" is wrongly displayed when dragging a link to the Bookmarks Toolbar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#1011]
[Affected versions]:
- Firefox 52.0.1 and above
- Tab Center 1.31.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Tab Center add-on is installed on a new clean profile.
- Bookmarks toolbar is enabled and at least 2 sites are bookmarked in the toolbar.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to any page and select the link from the address bar.
3. Drag the link between 2 bookmarks from the toolbar and observe the behavior.

[Expected result]:
- The position pointer appears between the two bookmarks.

[Actual result]:
- The position pointer appears in the top part of the page contents.

[Notes]:
- This issue is not reproducible with Tabs on Top.
- Here is a screen recording of the issue: 
![bookmarks pointer is displayed over the page contents](https://cloud.githubusercontent.com/assets/18304511/23856435/50ec22e4-0802-11e7-9b9a-9113ce472517.gif)

**Comment by Keith94** [comment]
Dupe of #147

**Comment by SoftVision-CiprianMuresan** [comment]
Seems like it. Thanks @Keith94.
