### ISSUE TITLE
[Reverse Tab Order] Pinned tabs are reversed after each browser restart

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#1012]
[Affected versions]:
- Firefox 52.0.1 and above
- Tab Center 1.31.0 (built on 3/13/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Tab Center add-on is installed on a new clean profile.
- "Show my windows and tabs from last time" option is selected in about:preferences.
- Reverse Tab Order is enabled in about:addons->Extensions->Tab Center
- At least 2 tabs are pinned.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and observe the pinned tabs order.
2. Restart the browser and observe the pinned tabs order.

[Expected result]:
- Pinned tab order remains the same.

[Actual result]:
- Pinned tabs are ordered in reverse.

[Notes]:
- The pinned tabs are flipped on each restart.
- The issue is also reproducible on the Tab Center version from Test Pilot.
- Here is a screen recording of the issue: 
![pinned tabs are reordered after restarting the browser](https://cloud.githubusercontent.com/assets/18304511/23858523/601e76e8-0809-11e7-81cb-fda46263896b.gif)

**Comment by SoftVision-PaulOiegas** [comment]
This seems to no longer reproduce on today custom build made from repo. 
Also, I have verified the second fix you mentioned in the PR and I haven't seen that long error that was present before.

However, while checking the second fix, I did some extra negative tests to see if I can break the tour functionality. I have found an edge case where the tour re-display at reinstall might be a wrong choice. But it's up to you guys @ericawright @bwinton .
If you move tabs on top, and after you choose to remove add-on + undo the removal from "about:addons" page, the tour is displayed again.

**Comment by ericawright** [comment]
Yeah I noticed the uninstall/undo behaviour before. It's the same for when a user uninstalls and then reinstall later - I don't really have a way to tell if it is a fresh install or not. I could leave behind a pref not clear it, then check for it on install. But that kind of feels wrong....

**Comment by SoftVision-PaulOiegas** [comment]
I agree. It's an edge case and a low impact behavior I think. So if it's hard to change, we should probably leave it as it is IMHO.
