### ISSUE TITLE
[Remember tabs] If tabs filtering is applied, all tabs except focused one and/or results are lost after browser is restarted / closed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#1015]
**[Affected versions]:**
- Firefox 52.0 and above
- Tab Center 1.31.0 (release version)
- Tab Center custom repo build 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Tab Center was installed from Test Pilot or from custom repository build.
- In `about:preferences#general` page, set the option "Show my windows and tabs from last time".

**[Steps to reproduce]:**
1. Go to a website and open multiple links in different tabs.
2. While focusing one tab, click the Search input field from Tab Center.
3. Write any string, found or not in the tabs names.
4. After filtering is made, restart or close the browser.
5. Reopen the browser and observe the opened tabs.

**[Expected result]:**
All the last session tabs are opened even if some or all were filtered out

**[Actual result]:**
With filter results
All the last session tabs except the focused one and filter results are lost after browser is restarted / reopened.

Without filter results
All the last session tabs except the focused one are lost after browser is restarted / reopened.

**[Notes]:**
- This issue also occurs without the "remember tabs..." option checked, if "restart" command is used. 
- See attached screen recording of the issue: https://goo.gl/Beruhx.

**Comment by ericawright** [comment]
(gotta say, this bug is kinda cool)
side note - pinned tabs always come back.

**Comment by SoftVision-PaulOiegas** [comment]
Sorry to say 😢, but this still reproduces with the original steps on today custom build made from master repo.

**Comment by SoftVision-PaulOiegas** [comment]
Aaaaa... 
![200](https://cloud.githubusercontent.com/assets/17258026/24456367/7998957e-149b-11e7-9302-8cd19ef31854.gif)

I can still reproduce it in the exact same way with today's custom build from the repo...

**Comment by ericawright** [comment]
why!? I swear we are testing this!

**Comment by SoftVision-PaulOiegas** [comment]
Did some further investigations and found out some different results on Windows vs Mac OS. Here are the 4 cases that I've tested now:

1. If you choose to close the window on Windows from [x] titlebar button, when you reopen the browser with the same profile, the issue still occurs.

2. The same thing happens on Mac OS if you only close the current window. When you restore the closed window, the issue occurs also on Mac OS.

3. If you use console "restart" on Windows, the issue does not occur.

4. If you use "Quit Firefox" option from Mac OS toolbar, the issue does not occur.
