### ISSUE TITLE
Shrink sidebar functionality breaks if "Ctrl + Shift + L" keyboard shortcut is used

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#1023]
**[Affected versions]:**
- Firefox 52.0 and above
- Tab Center 1.31.0 (release version)
- Tab Center custom repository build 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Tab Center was already installed on a new Firefox profile from Test Pilot or from custom repository build.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Choose to "Shrink sidebar when not in use".
3. Hover away the sidebar and wait for it to shrink.
4. Press "Ctrl + Shift + L" keys combination.
5. Remove the sidebar focus and observe its behavior. 

**[Expected result]:**
The sidebar correctly shrinks when focus is removed. 

**[Actual result]:**
The sidebar no longer shrinks when focus is removed.

**[Notes]:**
- In order to workaround the issue, you have to choose to "Keep the sidebar open" and then again to "Shrink sidebar when not in use".
- Here is a screen recording of the issue: https://goo.gl/UHFvgm.

**Comment by bwinton** [comment]
Ctrl-Shift-L toggles the sidebar open or closed.  I'm not sure why you would expect a sidebar that's toggled open to close…  I'm resolving this as-designed.

**Comment by SoftVision-PaulOiegas** [comment]
Well, I wasn't sure if this shortcut should override the user setting to shrink sidebar. So I logged it more to find out your opinion on this. Thanks for clarifying.

**Comment by SoftVision-PaulOiegas** [comment]
@bwinton One question here still. The key combination behavior mentioned above applies only when the sidebar is in auto shrink mode? Or it should also apply when the user chooses to keep the sidebar open?

**Comment by bwinton** [comment]
The toggle-expanded part will only work when the sidebar is in auto-shrink mode, but the side effect of focusing the findbar will still work in keep-expanded mode.
