### ISSUE TITLE
Searching with a lot of tabs

### ISSUE THREAD

**Issue by karlcow** [bwinton/TabCenter#1025]
1. Open around 415+ tabs
2. Search a term that you are sure to find.

Expected: find the item
Actual: The search starts… then stops.

**Comment by SoftVision-CarmenFat** [comment]
Hello and thank you for the report.
We have seen a similar behaviour on #1004. Can you please check if the filtering issue is still reproducible after restarting your browser?

Thank you.

**Comment by karlcow** [comment]
It was fixed after restart. So something caused this at a point indeed. Thanks.
