### ISSUE TITLE
Add options to disable preview (icon only)

### ISSUE THREAD

**Issue by YPetremann** [bwinton/TabCenter#1029]
I really like the TabCenter, it's like TST and I tree fonctionality is not required, but at least here it would be great if we could have an option to disable the preview that makes tabs taking more space.

**Comment by bwinton** [comment]
If there isn't enough space to display the thumbnails, it will automatically switch to icons, so it's not actually taking up any more space.  🙂  Thanks for the comment!

(Oh, and there's more information in #439 that you might find helpful.  😉)

**Comment by YPetremann** [comment]
For me the option should be available in the module option panel, the same place where "invert tab order" is.

**Comment by bwinton** [comment]
Definitely not.  We're not interested in testing that configuration in this experiment.  Once we're done our testing, a future maintainer might add more visible support for that option, but at this point it would just muddy the data we got.

**Comment by Keith94** [comment]
Is there a planned graduation date from Test Pilot yet?

**Comment by bwinton** [comment]
Mid-April, last I heard, but it could still slip.  And, of course, it'll stop working as of Firefox 57, because it's not a WebExtension, so there is a very final end date.  😉

**Comment by Keith94** [comment]
I hope that it will be migrated to WebExtensions, or even integrated in the browser itself, given the amount of users and feedback it has.

**Comment by bwinton** [comment]
Yeah, we're definitely thinking hard about what to do as next steps.  A lot of Firefox developers are big fans of the various tabs-on-the-side add-ons, and we don't want to lose them either!
