### ISSUE TITLE
[idea/suggestion] Add option to force condensed tabs

### ISSUE THREAD

**Issue by brouberol** [bwinton/TabCenter#1032]
For those of us (or maybe I'm the only one?) who prefer the look of the condensed tabs over the large ones, could it be possible to force tabs to stay in condensed mode no matter the number of open tabs? I had a look at the `VerticalTabs.actuallyResizeTabs` method, which does not seems to take any configuration key into account.

What do you think?

**Comment by Keith94** [comment]
Change `extensions.verticaltabs.largetabs` to `0` in about:config.
