### ISSUE TITLE
Hover timer

### ISSUE THREAD

**Issue by powerfool** [bwinton/TabCenter#1033]
I love how I can have tabs condensed or expanded but I run into the issue where the sidebar is expanded inadvertenly. I would like to be able to set a bigger timer for the hover action so that the expansion doesn't happen so quickly.

I love the add-on, I don't think I can go back to without it. 

Thank you,
D.

**Comment by adambowles** [comment]
I agree with this.

Using Firefox on my right monitor, I constantly open TabCenter as I move mouse over to left monitor.
