### ISSUE TITLE
Throbber / spinner appears as a rotating white box

### ISSUE THREAD

**Issue by hcs64** [bwinton/TabCenter#1038]
On currently nightly (build 20170329071901 on OS X and Win 7), the spinner is rendering as a rotating white box with rounded corners:
<img width="62" alt="screen shot 2017-03-29 at 4 01 59 pm" src="https://cloud.githubusercontent.com/assets/857753/24480414/10dfdb70-1499-11e7-9c62-727f493db94b.png">

mozregression led me to [this changeset](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=3ec1fe2261772be789ed16280521daacd0f7ca55&tochange=76ad1c764e5c626b20b87099fe9b822e21dc23e9) from [bug 759252](https://bugzilla.mozilla.org/show_bug.cgi?id=759252), so it seems like it is related to this recent change.

**Comment by SoftVision-PaulOiegas** [comment]
Seen this also yesterday but somehow I was convinced that it's a new feature lol. Thanks for the report ! 😄

**Comment by ericawright** [comment]
Yes, on nightly this has been happening as a result of https://bugzilla.mozilla.org/show_bug.cgi?id=759252 landing the other day. But, I  kind of think it's cute. Unfortunately it just disappears entirely when tabs are small, so it is something that will need to change eventually.

**Comment by mlissner** [comment]
I think I saw that Firefox is working on redoing the spinners, so I assume that's what breaking things here, but on nightly I'm not seeing a spinner at all. When a page is loading, I just have a space where the favicon would normally be until the page loads and then I see the favicon. It's surprisingly disorienting not to have anything showing progress of a page loading.

(Nightly on Ubuntu Linux with dark theme.)

**Comment by hcs64** [comment]
@mlissner: As ericawright mentioned, the spinning empty favicon holder only shows up when the tabs are full sized (with a thumbnail and domain). Do you have enough tabs that it is showing the small version of tabs with only the favicon and title?

**Comment by mlissner** [comment]
Ah, I missed that, @hcs64. I have the setting enabled that makes the tabs small all the time (the shrinking and expanded drove me nuts). So yeah, sounds like @ericawright is on this!

**Comment by mlissner** [comment]
Thank you!

**Comment by asamuzaK** [comment]
Not fix yet.
Spinner is spinning WITH a white background (blue background in compact themes).

**Comment by ericawright** [comment]
@asamuzaK for now, we've decided that that's okay. so long as the spinner hasn't disappeared
