### ISSUE TITLE
Pressing tab search shortcut key (ctrl+shift+L) keeps sidebar open even after mosue cursor is moved away

### ISSUE THREAD

**Issue by LiquidO2** [bwinton/TabCenter#1042]
**STR:**

- Set side bar to shrink when not in use
- Press ctrl+shift+L
- Move mouse cursor away from sidebar and click on the web page (whatever web page you are on)

**ER:**
Sidebar is automatically shrunk. 

**AR:**
You have to press shortcut key (ctrl+shit+L) again or you have to manually disable and enable auto shrink for auto shrink feature to behave normally again.

Is this behavior expected?

**Comment by bwinton** [comment]
Ctrl-Shift-L is the toggle-sidebar key, not the focus-search key.  It focuses the search bar as a helpful side effect.  Resolved: by design.
