### ISSUE TITLE
Search bug - Losing all open tabs

### ISSUE THREAD

**Issue by TDA** [bwinton/TabCenter#1043]
So, I had 119 tabs open, and searched for a particular keyword: "XYZ".
The search list gave me 6 tabs, and I ended up closing all 6 of them. Search remains blank, and no other tabs are shown. I press `escape`, try opening a new tab, but TabCenter is still empty, and all tabs seem lost.
I quit firefox, and started it again, and then hit restore session, only my pinned tabs are being restored. Any way to get back my tabs?

**Comment by TDA** [comment]
As a follow up, I seem to be able to get my tabs back if I can type keywords into the address bar (it shows the switch to tab option), but the tab does not appear as part of tab center. Once I switch to the tab, it magically appears :D

**Comment by ericawright** [comment]
Yikes, I was able to reproduce and will work on fixing asap.
In the meantime, to get your tabs back you can open the browser toolbox and go to the console. You can view the nodelist of your tabs by entering `window.gBrowser.tabs`, then loop through them and set the visibility to not be hidden ex. `window.gBrowser.tabs[0].setAttribute('hidden' false);`
Hope that helps!

**Comment by SoftVision-PaulOiegas** [comment]
@ericawright We have done some further testing on this area and found several new issues related to filtering. Maybe we can tackle more of them if you work on that area. 
#1044, #1045, #1046

**Comment by TDA** [comment]
@ericawright Hey, I did this:
```
window.gBrowser.tabs
TypeError: window.gBrowser is undefined
```

Anything I need to do to enable gBrowser?

**Comment by ericawright** [comment]
@TDA you must be in the browser toolbox. Not the regular dev tools. 
in dev tools go to the gear and scroll to `advanced settings`.  enable to two marked in the screenshot.
![screen shot 2017-04-03 at 2 18 13 pm](https://cloud.githubusercontent.com/assets/10803178/24624027/811b0bd4-1878-11e7-9426-b21d30d3e409.png)

Then go here (the shortcut on mac is `cmd-opt-shift-i` windows/linux is `ctrl-opt-shift-i`) :
![screen shot 2017-04-03 at 2 18 59 pm](https://cloud.githubusercontent.com/assets/10803178/24624048/997bbb06-1878-11e7-8678-129d6a888d67.png)

Once you are there try again in that console.

**Comment by TDA** [comment]
Hey @ericawright,
I tried the command there, and its not showing up the tabs yet. Any other way? 

![screen shot 2017-04-03 at 11 35 47 am](https://cloud.githubusercontent.com/assets/432707/24624785/c4e47b50-1861-11e7-80f6-6237434bfa16.png)

**Comment by ericawright** [comment]
![apr-03-2017 14-42-09](https://cloud.githubusercontent.com/assets/10803178/24625088/db8d47f0-187b-11e7-9574-862bf0026661.gif)
odd, it works for me.

Try selecting one of those tabs and check what attributes are on it. just with `window.gBrowser.tabs[3]` for example, see if the hidden attribute is set to true, or if there is any other suspicious attribute on it?

**Comment by ericawright** [comment]
it's possible that since you quit the previous session the tabs might be lost :(

**Comment by TDA** [comment]
@ericawright I tried out the changes from your PR (`filtered-out` did the trick) and it worked 💃 
YAYYYYY! :D thank you so much :D :D

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be correctly working on the above mentioned case. Did some other quick testing around it and couldn't find anything. We'll keep an eye on this filtering scenarios in the future.
