### ISSUE TITLE
After filtering the tabs and restart of the browser, all tabs that were outfiltered are invisible

### ISSUE THREAD

**Issue by digifu** [bwinton/TabCenter#1054]
I filtered my opened tabs with the tabCenter filter. After I filtered, the filter was still active, I restarted the browser due to an update. In the restarted browser, I still can see the filtered tabs, but the possibility to unfilter is gone. So I am not able to see the other tabs. But if I type in some tab names, that I remember that were opened before the filtering, then I can see the "switch to tab" information. So the dissapeared tabs are still recognized by the browser.

What I tried so far...
Changing from top to sidebar view, 
disabling and enabling the add-on

Is there a possibility to get the invisible tabs back? Maybe a possibility to see only the "opened tabs" in the URL field instead of the "history" and "opened tabs"?

**Comment by ericawright** [comment]
There is a new update coming today or tomorrow that fixes this issue. I can try to help you get your tabs back in the mean time.
check out the thread here: https://github.com/bwinton/TabCenter/issues/1043
and let me know if I can help in any other way, or if you would like some additional  clarity on how to try the instructions I outlined there.

**Comment by digifu** [comment]
It worked. All Tabs are back. Thank you!
