### ISSUE TITLE
Stuck at Top/Bottom with April 11 Release

### ISSUE THREAD

**Issue by laktak** [bwinton/TabCenter#1057]
This issue is hard to reproduce but happened to me a few times already:

- Open a few tabs so that the list will scroll
- Drag a tab (don't drop) and move the cursor to the top/bottom (so that the list scrolls)
- Repeat (still holding the tab) until it becomes stuck (it no longer follows the mouse cursor)
- Release the mouse button
- Try to scroll up/down - depending on the last action the tabs will either scroll to the top or bottom

Only restarting Firefox appears to fix this.

I am using "Reverse Tab Order"

PS: the upgrade to the April 11 release did not work very well, "Reverse Tab Order" did not work until I figured out that I had to restart Firefox

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @laktak, thanks for the report. Could you take a look at #997 and see if it's the same issue?

**Comment by laktak** [comment]
I guess it's the same issue with a different way to reproduce it.
