### ISSUE TITLE
Uh oh. ⁨Tab Center⁩ could not be enabled. Try again later.

### ISSUE THREAD

**Issue by deepak895** [bwinton/TabCenter#1059]
help me by solving this problem.
**Error**: 
Uh oh. ⁨Tab Center⁩ could not be enabled. Try again later.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @deepak895, thanks for the report. We had another issue just like yours which was recently closed. 
Could you please look over @SoftVision-PaulOiegas's comment in #1049 and see if that helps you?
