### ISSUE TITLE
Close button shows up briefly when panel slides open

### ISSUE THREAD

**Issue by digitarald** [bwinton/TabCenter#106]
The mouse hovers the close button while the panel moves out, causing some visual noise.

**Comment by bwinton** [comment]
Definitely something we want to fix, but probably not going to happen in the next six days…  😃

**Comment by Keith94** [comment]
Seems to be fixed by #478; can't reproduce anymore.

**Comment by bwinton** [comment]
Closing as per previous comment.  😉
