### ISSUE TITLE
Empty spaces remain after closed tabs and browser becomes unresponsive on Nightly with Tab Center installed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#1062]
[Notes]: 
- This is a regression **that is present for now only in Nightly** (starting with 2017-04-20 build) and it was introduced by Bugzilla issue [#1352069](https://bugzilla.mozilla.org/show_bug.cgi?id=1352069).
- LE: Issue is also reproducible on the 21st Nightly build that just came.

**[Affected versions]:**
- Firefox v53.0 and above
- Tab Center v1.33.0 (release version)
- Tab Center v1.33.0 custom build 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Test Pilot (production version) was already installed on a new profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://testpilot.firefox.com/experiments/tab-center page.
2. Click the "Enable Tab Center" button and go trough the tour slides in order to move tabs on the side.
3.  Open multiple new tabs.
4. Choose to close some of them (not the top or bottom) from "(x)" button or with scroll click.
5. Observe the Sidebar behavior.
6. Close all the tabs and observe the browser behavior.

**[Expected result]:**
- Step 5: Tabs are correctly closed and the other tabs slide in when one is closed.
- Step 6: The browser is closed when all tabs are closed.

**[Actual result]:**
- Step 5: Tabs closed leave an empty space in sidebar and the others are not sliding in.
- Step 6: A new tab is opened, the entire browser becomes unresponsive and cannot be used anymore.

**[Notes]:**
- After a while, an unresponsive script error is displayed (https://goo.gl/VtzinQ).
- Restarting the browser, makes it work until new tabs are opened and closed again.
- This issue occurs even in condensed view or with reverse tabs order.
- Here is the console output if it helps in some way (https://goo.gl/AQTrBa).
- Here is a screen recording of the issue https://goo.gl/ELAA6q.

**Comment by sivaraam** [comment]
I observed a similar issue in Nightly 2017-04-22. I could see blank spaces, but they seem to go off when I hover over tab list to see the extended tab center window. I didn't experience any browser unresponsiveness though.

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, the issue was introduced with the 2017-04-20 build and will persist in any new builds until will be fixed on Nightly or Tab Center side.

> I could see blank spaces, but they seem to go off when I hover over tab list to see the extended tab center window.

Indeed, the blank spaces are removed when hovering the sidebar in auto-hide mode.

> I didn't experience any browser unresponsiveness though.

This only occurs if you close all the tabs, one by one. When last one is closed, everything falls apart. 😄

**Comment by SoftVision-PaulOiegas** [comment]
This seems to be correctly working now on both fixed or auto hide modes of teh sidebar.
