### ISSUE TITLE
A grey column is displayed on the left of the Firefox sidebar, if Tab Center is in auto-hide mode

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/TabCenter#1065]
[Notes]:
- This is a regression that is present for now only in Nightly (starting with 2017-04-22 build) and it was introduced by Bugzilla issue #1355331.

[Affected versions]:
- Nightly 55.0a1
- Tab Center 1.33.0 

[Affected Platforms]:
- All Windows
- All Linux
- All MAC OS

[Prerequisites]:
- Tab Center was already installed on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open one of Firefox's sidebars.
3. Click on "Shrink sidebar when not in use" button.
4. Observe the area where the page content meets with the sidebar.

[Expected result]:
- There is nothing between the page content and Firefox Sidebar.

[Actual result]:
- A grey column is wrongly displayed between the page content and Firefox Sidebar.

[Additional notes]:
- Firefox's sidebars include: History (Ctrl + H), Bookmarks (Ctrl + B) and Synced Tabs (manually from toolbar)
- This is also reproducible with the Test Pilot version.
- Attached a screen recording of the issue:

![sidebar](https://cloud.githubusercontent.com/assets/26000308/25340982/104cf89c-2910-11e7-9e9e-5e8202d2df11.gif)

**Comment by ericawright** [comment]
bug #1355331 has been reverted for the time being

**Comment by SoftVision-CarmenFat** [comment]
Since bug #1355331 has been backed out, the issue is no longer reproducible on the latest version of Tab Center (built on 4/28/2017) using latest Nightly 55.0a1 (28-04-2017).
