### ISSUE TITLE
Title disappears from rendered tab, focus shifts to the wrong tab

### ISSUE THREAD

**Issue by Smile4ever** [bwinton/TabCenter#1077]
After you've executed the steps below, the title in Tab Center for the current tab is empty and the focused tab is wrong.

Steps to reproduce:
1. Go to https://nl.wikipedia.org/w/index.php?title=William_Joseph_Maloof&action=edit
2. Change the text
3. Press CTRL+W
4. A popup appears: "This page is asking you to confirm that you want to leave - data you have entered may not be saved.". Answer "Stay on Page".

The tab's title becomes empty and the current tab focus shifts away to the next tab. Also, the close button is gone for that tab.

If you try to close the tab without title by pressing CTRL+W and clicking "Leave this Page", the tab no longer renders content (intended) but the tab stays in Tab Center as a ghost tab and becomes unclickable. This ghost tab still knows it's tooltip though.

**Comment by Smile4ever** [comment]
I would like to add that if you close the last non-ghost tab in a window (while there are ghost tabs in the same window created by the above procedure), a "New tab" page opens in a new tab and uses 100% of a CPU core, totally freezing Firefox.

**Comment by SoftVision-CarmenFat** [comment]
Hi @Smile4ever and thanks for the report!

I was able to reproduce the issue you described on all Firefox versions, using Windows 10, Ubuntu 16.04 LTS and Mac OS X, with both Tab Center v1.34.0 - **release version** and v1.34.0 - **custom build**.
