### ISSUE TITLE
Right click "Move to New Window" Results in Blank Window

### ISSUE THREAD

**Issue by hafta** [bwinton/TabCenter#1078]
I can't reproduce this reliably, but sometimes right clicking on a tab (that is not the current tab) and selecting "Move to New Window" results in a new blank window displayed with an empty URL bar.

It seemed to only happen with tabs that were both 1) not pinned and 2) had not been viewed since the browser was restarted.

Nightly 55.0a1 (2017-05-06) (64-bit), OS X

**Comment by SoftVision-CarmenFat** [comment]
Hi @hafta and thanks for the report!

- I tried to reproduce the issue you described but without success.
- I was wondering if there is an additional step that you use when reproducing this problem, like **reloading all tabs** after restarting the browser?
If the answer is yes, then this might be related to http://bugzil.la/1362378

**Comment by hafta** [comment]
Hi @SoftVision-CarmenFat 

It sounds similar to http://bugzil.la/1362378 but I don't reload the tabs before hitting the bug. Today when I hit the problem, I had a window open with approximately 30 tabs and none of them pinned. I restarted Nightly due to an update being available. After that, when right-clicking on a tab I hadn't viewed yet and selecting open in a new window, I hit the problem. Here's a video.

[TabCenterNewWindowBlank.mp4.zip](https://github.com/bwinton/TabCenter/files/997918/TabCenterNewWindowBlank.mp4.zip)

**Comment by ericawright** [comment]
@hafta, 
Unfortunately we are shortly discontinuing support for Nightly, so I'll be closing this bug. If this bug is seen on v54 or earlier please let me know.
