### ISSUE TITLE
Opening a new window resets the index for opening a tab in the previous window

### ISSUE THREAD

**Issue by jdm** [bwinton/TabCenter#1079]
STR:
1. have multiple tabs open in a window, be active in a tab in the middle of the list
2. open a new window
3. switch back to the original window and open a new tab

Expected:
The new tab opens next to the open tab

Actual:
The new tab opens next to the first tab in the list

**Comment by ericawright** [comment]
Can I ask how you go about opening this new window. `cmd -N`?  and was this done with tabs in reverse?

**Comment by jdm** [comment]
Yes, cmd+n (or cmd+shift+p). The checkbox for "Reverse tab order" is not checked.

**Comment by jdm** [comment]
This appears to be a symptom of having the [Always Right](https://addons.mozilla.org/en-US/firefox/addon/always-right/?src=api) extension installed. I can't reproduce the problem when it's disabled.

**Comment by ericawright** [comment]
good to know. we have the Always Right  extension on the incompatible list #464 closing to track there.
