### ISSUE TITLE
Add support for displaying the page URL in a tab tooltip

### ISSUE THREAD

**Issue by Smile4ever** [bwinton/TabCenter#1083]
This is a feature request to not only display the title in the tab tooltip, but also the page URL. Some people might not want this, an optional thing (=setting) would be good.

**Comment by Keith94** [comment]
I don't know if it belongs in Tab Center, but you can use another add-on for this purpose: https://addons.mozilla.org/firefox/addon/tabtooltip/

**Comment by Smile4ever** [comment]
Thanks for the suggestion,  but it's not compatible with Nightly. In case it would work, it's still an SDK addon for which support will be discontinued in Firefox 57.

**Comment by bwinton** [comment]
TabCenter is also an SDK add-on, and won't work on Firefox 57…  And while this would be an interesting idea for a production version of TabCenter, I don't think this is something we're interested in testing, so I'm going to close this bug.

Thanks for the idea, though!
