### ISSUE TITLE
Can't scroll tablist, tabs diappear off the bottom of the screen

### ISSUE THREAD

**Issue by regroups** [bwinton/TabCenter#1084]
The tablist won't scroll, so when enough tabs are opened that the list goes beyond the bottom of the screen or browser window the tabs get lost. See this screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/27029926/26203887/0eb21f74-3c31-11e7-8411-1dc7a0865cdb.png)

It might look like the bottom of the image has been cut off but it hasn't, the list just runs off the end of the window.

The scroll indicator extends down most of scrollbar and can only be moved a couple of pixels up or down. There are a lot more tabs below what is visible here but the list can't be scrolled down to see them and the scroll indicator itself has run off the bottom of the screen.

I have this problem with Firefox 53 on FreeBSD and OpenBSD, tested with multiple desktop environments/window managers (xfce, kde, cwm, i3). This is with fresh profiles and no other addons installed.

**Comment by ericawright** [comment]
Thank you for the report. Unfortunately we don't have enough resources to support FreeBSD nor OpenBSD.
