### ISSUE TITLE
When the sidebar is on the right, the addressbar suggestion list is cropped from the left

### ISSUE THREAD

**Issue by MikkCZ** [bwinton/TabCenter#1095]
See description in https://bugzilla.mozilla.org/show_bug.cgi?id=1358856. I can reproduce this behaviour in Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0 ID:20170528100205 CSet: 6a235092bda7c20cb83651d3404284fe36d04c1b, but with Tab Center in sidebar only.

**Comment by CharoSW** [comment]
They are not supporting Nightly at this point in time because of bugs like this popping up.    Until Photon gets rolled out to Beta you're just going to have to close the sidebar before clicking into the URL bar

**Comment by MikkCZ** [comment]
I know, but still it is good to keep track of the issues so someone can fix them eventually.

**Comment by vanowm** [comment]
How do you move sidebar to the right?

**Comment by MikkCZ** [comment]
That option is part of Photoncin Nightly builds.

**Comment by ericawright** [comment]
we are neither supporting nightly nor tabs on the right
