### ISSUE TITLE
TabCenter side bar overlap other extensions

### ISSUE THREAD

**Issue by QuAzI** [bwinton/TabCenter#1096]
TabCenter side bar overlap other extensions (Vimperator in my case)

![2017-05-31_00-54-39_9w648inr](https://cloud.githubusercontent.com/assets/1897605/26606858/5de9854a-459c-11e7-9868-308a35fc05ff.png)

**Comment by SoftVision-CarmenFat** [comment]
Hi @QuAzI and thanks for the report. 
However, this issue is a dupe of #857.
Since we keep tracking this kind of issues in #464 I'll close this report.
