### ISSUE TITLE
TabCenter UI suggestion(s)

### ISSUE THREAD

**Issue by sann-nord** [bwinton/TabCenter#1097]
I really like this extension as it helps to maximize available vertical space with my Firefox sessions.  I have the following suggestion(s) - they go 'hand in glove'

When TabCenter is activated, there is no 'easy' way to close the 'current' tab - one must right click on the current tab and navigate to the bottom of the menu to close the current window - or interrupt the 'GUI-driven' interaction and hit CTRL-W to close the current window. 

I would like to suggest to either 1) add an 'X' right next to the '+' sign (to add a new tab) so that this 'X' will close the current tab -OR- 2) add a mouseover function for each tab that would pull up an 'X' to close that window.  Either approach would more closely approximate the default tab view in Firefox where a single click 'X' to close is always presented while keeping the 'right-click' menu functionality for more advanced functionality.

I would also like to suggest keeping the TabCenter 'toggle' icon in the titlebar - whether TabCenter is active or not.  This would enable UI consistency plus has the advantage of putting a 'minimally used' function out of the top left 'hot corner' area for frequently used actions.

Thoughts? Comments?

**Comment by lopis** [comment]
> there is no 'easy' way to close the 'current' tab

Middle mouse button or CTRL+W just like normal browser tabs. I honestly think the close button was an eyesore.

**Comment by sann-nord** [comment]
UPDATE: I keep my vertical tab area as narrow as possible so that only the the 'iconized' tab appears (no text next to the tab).  After reading heavybinary's post from June 1st, I realized that by making the area wider the 'X' mouseover function is provided - it's simply a question of 'real estate' use v. minimal interface functionality - and therefore my original post is moot!  Sorries...
