### ISSUE TITLE
Broken HTTPS resource shows as http:// in tab

### ISSUE THREAD

**Issue by martinthomson** [bwinton/TabCenter#1101]
When a page is somehow broken (in this example, a 404 with an empty body), the title shows the URL of the page.  Except that the title on the tab is "http://blah.example.com" instead of "https://blah.example.com".

I got this on https://tools.ietf.org/html/draft-galis-netslices-revised-problem-statement-03

Without tab center, this works as intended.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @martinthomson, thanks for the report.
I wasn't able to reproduce the issue you are experiencing on Windows 10 using the latest Firefox release, in my case the title correctly shows the https:// link:
![image](https://user-images.githubusercontent.com/18304511/26886877-3d9b5ffc-4baf-11e7-9a67-32596c415b32.png)

Could you please give us some more details about what OS you are using, Firefox Version, Tab Center and Test Pilot versions?

**Comment by martinthomson** [comment]
I see that this has been fixed.  I have lost track of which version (the version that was current at the time of the report was updated might have been it.  Either way, let's call this INVALID.

**Comment by martinthomson** [comment]
Oh, I should point out that I was on Nightly.
