### ISSUE TITLE
Create and post a migration plan.

### ISSUE THREAD

**Issue by nicholasbishop** [bwinton/TabCenter#1102]
I didn't realize this extension was being dropped. Is there any plan forward for this extension or something like it? I didn't realize when I installed tab center that the functionality could go away without any warning and I'm mildly desperate to find a replacement.

**Comment by bwinton** [comment]
There isn't yet.  I'm hoping https://github.com/eoger/tabcenter-redux/ becomes close enough by the time TabCenter stops working, so any help you could give to that repo would be appreciated by quite a lot of people!

**Comment by CharoSW** [comment]
Question: is this is the project ending completely?

**Comment by bunnybooboo** [comment]
For anyone seeking an immediately working alternative, use both:
https://testpilot.firefox.com/experiments/containers
and using some Photon magic
https://addons.mozilla.org/En-uS/firefox/addon/sea-containers/

You could remove the top tabs in fullscreen mode and keyboard shortcut ( CTRL . ) which will soon change to ( CTRL Shift . ) Hope that helps.

**Comment by jonathanKingston** [comment]
As @bunnybooboo suggested Sea Containers is an alternative available. It looks like @eoger's redux is designed for parity. I would love if containers were enabled to add Sea Containers like functionality to the redux version. If there is a chance of merging functionality like that I might have time to contribute.

I understand if this wouldn't be a priority as it opens up a lot of UX questions on integration.

**Comment by nicholasbishop** [comment]
Thanks for the quick response, glad to know alternatives are being explored :)

**Comment by fbruetting** [comment]
I'd like to reinstall my system – am I able to make TC work again on a completely new system when copying ~/.mozilla?

**Comment by bwinton** [comment]
@fbruetting: No.  Well, it might work, but it's completely unsupported and will be removed from TestPilot in the not too distant future.  Giving Tab Center Redux (linked above) a try will be a much more future-proof solution!  Good luck with the reinstall!

**Comment by grahamperrin** [comment]
[I switched to Vertical Tabs Reloaded:](https://discourse.mozilla-community.org/t/whats-all-this-about-sunsetting-tab-center/15999/13?u=grahamperrin) …
