### ISSUE TITLE
Once Tab Center Redux is on AMO, we should refer users to it.

### ISSUE THREAD

**Issue by Caspy7** [bwinton/TabCenter#1105]
Currently a Moz dev is developing Tab Center Redux https://github.com/eoger/tabcenter-redux .

Once this is on AMO, we should edit the AMO description to refer users to it (including a link).

Also do the same in the description that users see in the addon manager.

**Comment by Keith94** [comment]
AMO page is up: https://addons.mozilla.org/firefox/addon/tab-center-redux/

**Comment by Caspy7** [comment]
I figured that would take longer...

(I don't know if notifications like this work in GH, but...) 
@eoger do you have any estimation of when Redux will be fit for mass consumption?  (I haven't used either it or the original at this point.)

Figure it will be preferable to get as close to the current Tab Center featureset but start referring users sometime before 55 releases. (I believe I read that things start breaking in Tab Center with 55?)

**Comment by eoger** [comment]
@Caspy7 [These P1s](https://github.com/eoger/tabcenter-redux/issues?q=is%3Aissue+is%3Aopen+label%3AA-P1) are the most blocking.

**Comment by Caspy7** [comment]
Hrm, looks like all of those are dependent on Firefox/Mozilla.

Of note is [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1332447) to add a webextension API to hide the tab strip.  At the moment it's unclear if that will even make it before 57 (though it's pretty important for all tab management addons) as no Moz devs are working on it.

In particular I'd like to point out [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1332447#c21) indicating there's "broad approval" on the idea and now it's just a matter of finding someone to work on it.

Anyone? :)

**Comment by bwinton** [comment]
I thought I heard someone in IRC mention that they might take it, so hope remains alive.  I've got to say, even with the extra tab strip, I'm finding tabcenter-redux to be surprisingly useful already!

**Comment by omeringen** [comment]
What about Sidebar Tabs developer ? Is he also a Moz dev ?
https://addons.mozilla.org/en-US/firefox/addon/sidebar-tabs-webextension/

Used current versions of both Sidebar Tabs and Tabcenter-redux and IMHO sidebar tabs addon looks better for functionality and visually.

**Comment by Keith94** [comment]
>Is he also a Moz dev ?

Yes.
I personally found Sidebar Tabs too buggy in its current state; and the dev recommends not to use it.

**Comment by omeringen** [comment]
Two different moz dev is manintaing two different, same purpose extension. Okay.

**Comment by bwinton** [comment]
It's probably also worth noting that one is a fork of the other.

**Comment by omeringen** [comment]
Okay no problem about deleting the post i understand,. Also fork is good but it seriously seems meanless to me at this point(it's not sarcasm). Anyway.
@bwinton not that important but just use it for a couple of hours please, it's not that buggy.

bTw, i want to say. Vertical Tabs test experience is one of the best thing i see on Firefox after the Panorama which has been removed. The point is, i think these features(core browsing features IMHO) should integrate into browser instead of developing them as an addon.

Anyway, it was a nice test. Thanks.

**Comment by bwinton** [comment]
Fixed in #1116, I think…

(Also, I'm working with some people on implementing Panorama as a WebExtension, so hopefully that'll be a thing at some point in the future.)

**Comment by Caspy7** [comment]
> (Also, I'm working with some people on implementing Panorama as a WebExtension, so hopefully that'll be a thing at some point in the future.)

Any idea about an ETA on this?
Several users are rather antsy about losing the current one with 57. A soft talking point would be nice :)

**Comment by bwinton** [comment]
It's being worked on. :wink:

(The needed APIs almost definitely won't be there for 57, but I still have my fingers crossed that we'll land a compromise version of the API in Nightly by the time 57 is released, so that people can switch to that.)

**Comment by Caspy7** [comment]
Is work still ongoing? 
Looks like here's one effort at replacement. 
https://addons.mozilla.org/en-US/firefox/addon/panorama-view/
Perhaps it's time to go public?
https://www.reddit.com/r/firefox/comments/7jmhj5/guess_who_i_bumped_into_on_amo_panorama_view_v57/

Or is this the one you're working on?
