### ISSUE TITLE
Tab Center is incompatible with Nightly 56.0a1

### ISSUE THREAD

**Issue by jonalmeida** [bwinton/TabCenter#1107]
Updated to Nightly 56.0a1 and Tab Center has been disabled with no option in the addons list to enable (unlike other addons which are marked as legacy but still work).

**Comment by bwinton** [comment]
Resolved, duplicate of #1104.

**Comment by bwinton** [comment]
(I've switched to [Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/).  It's not the same, but it's getting better, and will work on Firefox 57+, which this version won't.)

**Comment by jhasse** [comment]
Check out https://github.com/bwinton/TabCenter/issues/1131#issuecomment-335830960 if you still want to use TabCenter with 56 (not 57+).
