### ISSUE TITLE
Firefox Nightly 56 and Tab Center

### ISSUE THREAD

**Issue by karlcow** [bwinton/TabCenter#1108]
Tab Center is said to be incompatible with Firefox Nightly since the switch to 56.
![capture d ecran 2017-06-16 a 10 25 43](https://user-images.githubusercontent.com/505230/27208048-4dbdbe90-527e-11e7-8fcb-c22bda3a41f2.png)

**Comment by Keith94** [comment]
See #1104

**Comment by karlcow** [comment]
duplicate of #1104

**Comment by karlcow** [comment]
Thanks @Keith94

**Comment by jhasse** [comment]
Check out https://github.com/bwinton/TabCenter/issues/1131#issuecomment-335830960 if you still want to use TabCenter with 56 (not 57+).
