### ISSUE TITLE
Please, update it to support Firefox 56 

### ISSUE THREAD

**Issue by yuniers** [bwinton/TabCenter#1110]
I got used to this add-on and now I miss the sidebar

**Comment by Keith94** [comment]
Check out https://github.com/eoger/tabcenter-redux/ as a replacement add-on

**Comment by ericawright** [comment]
thank you @Keith94. @yuniers do check out eoger's addon. v56 is difficult to support right now because of all of the changes happening, it's possible we might be able to support it once it moves to beta.
