### ISSUE TITLE
The Onboarding Tour strings are wrongly displayed on the doorhanger

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/TabCenter#1125]
[[Affected versions]:
- Release 55.0.3
- Beta 56.0
- Tab Center 1.37.0

[Affected Platforms]:
- All Windows
- All Mac

[Steps to reproduce]:
1. Open the browser.
2. Navigate to about:debugging and click "Load Temporary Add-on".
3. Select the Tab Center xpi and click on "Open".
4. Observe the Onboarding Tour.

[Expected result]:
- The text for each of the Onboarding Tour slide contains the specific title, description and related buttons.

[Actual result]:
- All the strings on the Onboarding Tour are incorrectly displayed.

[Notes]:
- Attached a screen recording of the issue: 
![onboarding](https://user-images.githubusercontent.com/26000308/30692300-94d40324-9ed3-11e7-891f-5330339cdab0.gif)

**Comment by ericawright** [comment]
thank you, this was the specific XPI I sent.
