### ISSUE TITLE
"Reverse Tab Order" option is still displayed in "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [bwinton/TabCenter#1126]
[Affected versions]:
- Firefox 55.0.3
- Beta 56.0
- Tab Center 1.37.0

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Tab Center .xpi (v1.37.0) downloaded from Bug [1380005](https://bugzilla.mozilla.org/show_bug.cgi?id=1380005) was installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to about:addons.
3. Double click on the "Tab Center" experiment.
4. Observe the items from the experiment's description.

[Expected result]:
- "Reverse Tab Order" option is not displayed.

[Actual result]:
- "Reverse Tab Order" option is displayed.

[Notes]:
- Must mention that even though checking the "Reverse Tab Order" checkbox, its functionality is not available and the opened tabs are not affected.
- Attached a screen recording of the issue: 

![reverse](https://user-images.githubusercontent.com/26000308/30699860-89aa2990-9eee-11e7-9631-85c2b6e5e695.gif)

**Comment by ericawright** [comment]
Thank You! this is now fixed with 729dcd5
