### ISSUE TITLE
Not compatible with version 56

### ISSUE THREAD

**Issue by panosl** [bwinton/TabCenter#1130]
This is a must have extension for me, but I upgraded to 56, and it's being marked as not compatible.

**Comment by bwinton** [comment]
Yup. The APIs it depends on are being removed from Firefox, so it's going away. Fortunately, someone has made [a new extension](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/) based on the new APIs that works very similarly (and will hopefully get some features that were impossible in this extension)!

**Comment by jhasse** [comment]
Check out https://github.com/bwinton/TabCenter/issues/1131#issuecomment-335830960 if you still want to use TabCenter with 56 (not 57+).
