### ISSUE TITLE
TabCenter got deactivated with FF 56.0 - will it come back?

### ISSUE THREAD

**Issue by sco2tbold** [bwinton/TabCenter#1132]
I really got to love TabCenter. Will it come back?

**Comment by martin-klima** [comment]
Me too. I hope my tabs will be at left side again.

**Comment by bwinton** [comment]
First of all, thank you. I didn't expect TabCenter to be as loved as it was, and it's really nice to see!

Unfortunately, the technologies it's based on are going away, so it's not going to come back. But, someone has [re-written it](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/) using the new APIs, so if you install that, it should work reasonably similarly (and it will get better over time).
