### ISSUE TITLE
Add link to Tab Center Reborn in README

### ISSUE THREAD

**Issue by ariasuni** [bwinton/TabCenter#1133]
Current README links to Tab Center Redux, however the development of this extension has been discontinued for more than 6 months now.

Tab Center Reborn is a regularly updated fork of Tab Center Redux which I’m developing.

Please include a link to it instead or besides Tab Center Redux so that users knows about the updated fork.

**Comment by ariasuni** [comment]
Thanks a lot!

**Comment by bwinton** [comment]
My pleasure! Sorry it took so long. 🙂
