### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by User-47186985** [bwinton/TabCenter#175]
Hello, 
I think the Tab Center is a great idea, but could use a few improvements. I hope this is the right place for some suggestions. It would be convenient to have categories to sort the tabs. Also, the Tab Center should be below or at least correctly lined up with the navigation bar. Most importantly, the New Tab button should be easily reachable. I'm not good at drawing, but here is a quick mockup how I'd want it to look like.
![untitled](https://cloud.githubusercontent.com/assets/7759619/15188126/85dcef64-17a4-11e6-8721-a358c8bd1431.png)

**Comment by pvsomebody** [comment]
As a fellow Firefox user very pleased to see vertical tabs finally make it, I wouldn't necessarily agree with all of the suggestions, but the idea to move the location bar on top sounds nice.

Is there going to be a feedback survey, or questionnaire on Tab Center?

**Comment by Keith94** [comment]
Even the original Vertical Tabs had the navigation bar on top it seems.

https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs/

**Comment by bwinton** [comment]
There are some good ideas here, and we'll integrate them into future mockups.  Thanks!
