### ISSUE TITLE
Writing/posting any text on social apps ex Facebook, is not quick and shows a lag on typing and reflecting back.

### ISSUE THREAD

**Issue by eranshul20** [bwinton/TabCenter#208]
Slow response and lag on reflecting what user has type

Firefox 46.0.1
Windows 10, 64 bit

**Comment by wresuolc** [comment]
We're having trouble reproducing this.  Maybe you have other add-ons installed which it is conflicting with?

**Comment by wresuolc** [comment]
We're talking about reviewing our code and maybe running a profiler for speed.  We'll use this issue to track that.  Thanks!

**Comment by strugee** [comment]
I can reproduce general sluggishness with this addon. I have several hundred tabs although the problem occurs even when I get a single "Restore Session" tab.

I'm happy to try my hand at running the browser through a profiler to try to find the slowness. I'm also happy to provide a detailed bug report, with e.g. addons I have installed, etc.

Should I file a separate issue?

**Comment by ericawright** [comment]
@strugee working within this issue is fine. If you want to go out of your way to provide any additional info it would be much appreciated 😄

**Comment by strugee** [comment]
Oops. Forgot about this :/

I don't run Tab Center anymore, so I don't know if this still happens.
