### ISSUE TITLE
Sometimes updates are borked

### ISSUE THREAD

**Issue by wresuolc** [bwinton/TabCenter#226]
My browser got an update to Tab Center and the add-on stopped working (the tabs returned to the top of the screen).  This was in the browser console:

CustomizeMode:TypeError: aWindowPalette is null
Stack trace:
CustomizableUIInternal.getUnusedWidgets@resource://app/modules/CustomizableUI.jsm:1719:9
this.CustomizableUI.getUnusedWidgets@resource://app/modules/CustomizableUI.jsm:3348:12
CustomizeMode.prototype.populatePalette@resource://app/modules/CustomizeMode.jsm:792:27
CustomizeMode.prototype.enter/<@resource://app/modules/CustomizeMode.jsm:331:7
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:714:7
CustomizeMode.prototype.deferredWrapToolbarItem/</<@resource://app/modules/CustomizeMode.jsm:875:9
CustomizeMode.jsm:805

**Comment by Screwtapello** [comment]
I'm guessing an upgrade is "remove old version" followed by "install new version". Tab Center is correctly disabled during the "remove" phase but not re-enabled during the "install" phase.

Manually restarting Firefox puts everything back to normal (TabCenter installed and working).

**Comment by ericawright** [comment]
I believe updates are no longer borked :)
