### ISSUE TITLE
Make It Prettier

### ISSUE THREAD

**Issue by ericawright** [bwinton/TabCenter#252]
Visual things that could use improvement:
- No visual feedback when you mouse over the pin icon
- The + icon jumps a little when expanding and shrinking
- On linux/windows the font is different for “New Tab” some with drop shadow, some a hollow font style
- "New Tab" mouse-over feedback in dark theme (very subtle)

**Comment by ozgurakyazi** [comment]
- When mouse over the pin icon, it writes "Keep Sidebar Open"
- + icon is just stable, no jumping

I don't know is that same for you but maybe you could check those again.

**Comment by sevaan** [comment]
+ icon should be aligned with the favicons. It's slightly to the left which throws off the balance. http://i.sevaan.com/1O0T2s1w2o1Y

**Comment by bwinton** [comment]
I believe it is now prettier.  😃
