### ISSUE TITLE
tab is not disappearing while in fullscreen

### ISSUE THREAD

**Issue by jastisriradheshyam** [bwinton/TabCenter#255]
- [ Linux Mint (Cinnamon edition) ] Operating system
- [Release ] Firefox build (Nightly, Developer Edition, Beta, Release)

---
As in subject while in full screen mode tab portion is not disappearing as it normally happens in normal ones.
Thanks.

**Comment by bwinton** [comment]
I believe this should be fixed as of our latest style refresh.  Please re-open it with a screenshot and steps to reproduce if you can still replicate the problem.  Thanks!
