### ISSUE TITLE
Cursor appears in unexpected location after enabling Tab Center

### ISSUE THREAD

**Issue by pdehaan** [bwinton/TabCenter#269]
Originally filed by @Qhuea in https://github.com/mozilla/testpilot/issues/892

---

This seems to have started when I enabled tab center, but this gives me access to place a weird movable flashing cursor-bar (the one that appears when you type,) in weird places in webpages. I can't provide a screenshot, but I can provide an example picture. 

![capture](https://cloud.githubusercontent.com/assets/12704804/15443776/d796be6e-1e9f-11e6-8e8e-a60201a4f3da.PNG)

...

This is on any website, anywhere. It's reacting as if it's an editable text document. I've tried resetting Firefox and that does not work.

...

I'm using Windows 7, and no other Test Pilot add-ons. I use adblock plus, that's all. The weird cursor thing works on all websites for me, BTW.

**Comment by Screwtapello** [comment]
Is this just the Firefox "Caret Browsing" mode? Does it go away when you press F7?

**Comment by Qhuea** [comment]
@Screwtapello sorta. I went away in certain places. It still stays in the location in the image.

**Comment by bwinton** [comment]
I can't seem to reproduce this after our latest style update, so I'm going to close this bug.  If you can figure out how to get it to fail again, please re-open it with steps to reproduce!  Thanks!  🙂
