### ISSUE TITLE
Misleading behaviour of 2 simultaneously opened pages

### ISSUE THREAD

**Issue by LadyQA** [bwinton/TabCenter#291]
Actual: If Tab center and Options page are opened simultaneously, 2 marked as opened options are misleading for user 
http://screencast.com/t/SfAQira9ZJ8

**Comment by bwinton** [comment]
Thanks for the report.  We're thinking about a new theme which will help with this…

**Comment by Keith94** [comment]
Seems mostly fixed as of #478?

**Comment by bwinton** [comment]
Yeah, I agree.  And the parts that aren't should be fixed by #7.  Thanks!
