### ISSUE TITLE
"New Tab" title for new tab appears always in English

### ISSUE THREAD

**Issue by flodolo** [bwinton/TabCenter#294]
I've just noticed that the title of a new tab always appears in English as "New Tab", even in a localized build.

Not sure why, considering I can't seem to find any hard-coded "New Tab" in the add-on code.

**Comment by bwinton** [comment]
I also don't know, but I think we're going to leave this, since the add-on is English-only for now, and any l10n efforts should catch this case, too.  Thanks for the report!
