### ISSUE TITLE
Additional tabs can't be closed with Cmd-W while the last close animation is running

### ISSUE THREAD

**Issue by rnewman** [bwinton/TabCenter#306]
* Open three tabs.
* Hit Cmd-W three times in rapid succession, so that you hit the key three times before the second tab is selected.

Expected:
* All three tabs are closed.

Actual:
* Only one tab is closed. Subsequent close events aren't handled until the next tab is visibly selected.

**Comment by chris-morgan** [comment]
I didn’t find this before filing #394, but I feel #394 makes a much clearer case of it.

In stock Firefox, the tab is instantly closed and the animation to vanish it from the tab bar happens after that. With this, the tab is not actually closed until the animation to vanish it from the tab bar is completed.

**Comment by Croydon** [comment]
AFAIK I saw already a commit for that, did somebody forget the close the issue? :)

**Comment by bwinton** [comment]
Did you?  I didn't think we fixed this yet…  Which commit was it?

**Comment by Croydon** [comment]
Sorry, I get way too many GitHub notifications these days since there is no native way to filter it. I got it confused with #324.
