### ISSUE TITLE
new tab order inconsistency

### ISSUE THREAD

**Issue by meandavejustice** [bwinton/TabCenter#313]
Moved on behalf of @Qhuea from https://github.com/mozilla/testpilot/issues/931

>When I try and open a new tab, if I hover my mouse over the '+' and wait for the tab center to fully open, it will put the new tab on top of the old tab, but if I press the '+' while the tab center opening  animation is still playing, the new tab appears on the bottom. 
![ontop](https://cloud.githubusercontent.com/assets/12704804/15635179/672d504a-258c-11e6-817f-dd3088ac6d8e.PNG)
![onbottom](https://cloud.githubusercontent.com/assets/12704804/15635180/672f3f36-258c-11e6-991a-064725ff74f4.PNG)

**Comment by ericawright** [comment]
Can't duplicate - but as this bug was originally submitted 2 days ago it may have been fixed with the most recent release?

**Comment by meandavejustice** [comment]
@Qhuea can you confirm?

**Comment by Qhuea** [comment]
@meandavejustice @ericawright I'm not sure if I'm on the newest version, but it seems to still be functional for me.

**Comment by wresuolc** [comment]
May be related to #322

**Comment by ericawright** [comment]
this should be fixed as of adding a pref to open tabs on the top of bottom
