### ISSUE TITLE
Quick expanding (leftmost pixel) is unreliable

### ISSUE THREAD

**Issue by phlsa** [bwinton/TabCenter#331]
On Windows 10, the quick expansion of the side bar when hitting the left screen edge only seems to be working some of the time. I wasn't able to find a pattern of when it works and when it doesn't, but I'd say that it works as expected around 15% of the time.

**Comment by bwinton** [comment]
Does it slow-expand the other times, or just not expand?

**Comment by phlsa** [comment]
It does expand, but with the delay.

**Comment by phlsa** [comment]
Looks like this has something to do with the event not always triggering. When I move the mouse into the window from the left side, it always triggers correctly. If I move it in more slowly (but still faster than the 300ms delay) from the right side, it never triggers correctly.
