### ISSUE TITLE
new tab button and bookmark bar missing after disabling Test pilot

### ISSUE THREAD

**Issue by johngruen** [bwinton/TabCenter#333]
From @kaus02 Running: 

* Windows 8
* Firefox edition 46.0.1

After disabling the Test pilot:

1. new tab button is missing
2. bookmark bar is missing.

No it's not resolved, checked it again still new tab button missing(v 46.0.1). I am attaching the screenshot in which tab center is activated.
![screenshot 22](https://cloud.githubusercontent.com/assets/14627369/15626680/bed39b78-24e8-11e6-998b-ed5fbeeabefe.png)
And also the one in which tab center is deactivated.
![screenshot 23](https://cloud.githubusercontent.com/assets/14627369/15626692/30d7949a-24e9-11e6-80f9-834bba3ba829.png)

**Comment by ericawright** [comment]
@kaus02 has the "new tab" button always been missing, or just recently?

**Comment by kaus02** [comment]
@ericawright Just I as disabled the ta center, it went missing.

**Comment by ericawright** [comment]
You should be able to get it back by going to the customization menu, and dragging the new tab icon back into place (if you haven't already). Though we'll have to look into why it may have disappeared in the first place.

**Comment by kaus02** [comment]
@ericawright thanks,I got it back.

**Comment by bwinton** [comment]
This should be fixed by the fix for #471, so I'm going to close this and track it there.
