### ISSUE TITLE
Favicon not changing

### ISSUE THREAD

**Issue by grimofdoom** [bwinton/TabCenter#345]
often favicons will not change to the new website if you switch to another tab, before the website loads all the way. Annoying and makes things too tricky.

**Comment by ericawright** [comment]
I think I may have seen this once or twice, but not enough to be able to reproduce it regularly. What system are you on, and are there any specific steps to trigger it more often?

**Comment by bwinton** [comment]
We've switched to showing thumbnails instead of favicons, so I'm going to close this.  If you still see it, please feel free to re-open the bug.  Thanks!
