### ISSUE TITLE
tabs order change bug

### ISSUE THREAD

**Issue by harit-amine** [bwinton/TabCenter#356]
Sometimes, the tabs order is changed when clicking on them, sorry i don't know any information about my version build, thank's for your effort

**Comment by tobia** [comment]
Hi @harit-amine
Are you sure you're making a single click on the tabs, and not a click + drag?
I use this extension on Mac and Linux every day and I have never seen this bug.
What operating system are you using?

**Comment by harit-amine** [comment]
Hi @tobia 
I'm using it under Linux, and i have the latest version of Firefox, it doesn't happen often and i'm sure that i don't drag it, it's just a simple click, and it happens on the first reload of the tab.
