### ISSUE TITLE
Make Tab Center localizable

### ISSUE THREAD

**Issue by brwolfgang** [bwinton/TabCenter#360]
Hi there, I work with the Brazilian L10N team and I've noticed that the context-menu option named "Close Tabs Below" is not available to localization.

I guess the other strings that are common to Firefox (such as "Close tab", "New Tab", etc) are pulled from the browser but since "Close Tabs Below" is related to this addon it's not yet localized.

I understand that as this experiment grows more addon-specific strings will appear and it would be great to have those strings available to localization.

Tab Center is a great experiment, keep the good work =)

**Comment by johngruen** [comment]
@bwinton we would love to do this for the German launch if at all possible. For reference, @meandavejustice did something similar with Min Vid.

https://github.com/meandavejustice/min-vid/commit/4341c32e7e2212c1ca5f008bd0859c7defc6f489

https://github.com/meandavejustice/min-vid/commit/15da7648ba2f3527deb40bb4478e7849712154f2

@clouserw can also assist with pontoon integration if this is something you think can be done.

**Comment by bwinton** [comment]
@brwolfgang If you wanted to contribute a Brazilian localization once that pull request lands, I'ld love to include it.  :)

**Comment by brwolfgang** [comment]
@bwinton How can I help? I'm familiar with Pontoon but translating a text file is also fine.

**Comment by bwinton** [comment]
I'm hoping we can get it into Pontoon in the near future.  In the meantime, let's wait until it lands, and if necessary, I'll write some instructions then.

**Comment by brwolfgang** [comment]
See you then
