### ISSUE TITLE
Tab Center prevents tab, address and instrument bars from hiding if Firefox is fullscreened

### ISSUE THREAD

**Issue by pvsomebody** [bwinton/TabCenter#363]
The screenshot below shows the issue. Is this a bug, or a feature?

![screenshot_20160616_001737](https://cloud.githubusercontent.com/assets/13513395/16099574/9f37827a-3361-11e6-928a-604696946a2b.png)

**Comment by bwinton** [comment]
It sounds similar to another bug I can't find…  Which OS are you using, and how did you enter fullscreen?  (And thanks!)

**Comment by maotora** [comment]
Hi, i had this problem and asked in the irc firefox server and they helped me with this [here](http://kb.mozillazine.org/Browser.fullscreen.autohide) it basically hides the address bar (and conceptually everything on fullscreen but i think the tabs center is very recent) by going to
`about:config` and do `browser.fullscreen.autohide` and set that to true (default is false).

**Comment by pvsomebody** [comment]
Hi, bwinton. I am on openSUSE Tumbleweed Linux, most recent stable Firefox, and it happens both if I press F11 or the Full Screen button in the three-bar menu.

Thanks, maotora. It kind of, sort of helps, since it only hides the instruments bar, the tab bar is still there. By the way, `about:config` says that this option is set to true by default, so it must have been the vertical tabs that set it to false after installation.

**Comment by bwinton** [comment]
So Tab Center doesn't support all the various combinations of changes you can make in `about:config`.  If you can reproduce this on a clean profile, by only installing Tab Center, and it's different when Tab Center is installed vs. when it isn't, then please re-open this bug and post the screenshots.  But until then, I'm going to have to close this.  Thanks for the report, though!
