### ISSUE TITLE
window header present with disabled tab center

### ISSUE THREAD

**Issue by peterbandi** [bwinton/TabCenter#364]
I have tried the tab center briefly than disabled it. But ever since the window header (where the _ [] X buttons are normally located on other windows) keeps coming back and I have to re-enable and disable tab center again to make it disappear. I have also enabled activity stream and universal search.

OS: Windows 10
Firefox: 47.0

**Comment by bwinton** [comment]
We've done a bunch of work to clean up our uninstall procedure, so I'm going to close this, but please feel free to re-open it if you're still running into this problem.  Thanks!
