### ISSUE TITLE
Is separation line between the new tab "plus" icon and bookmarks list really necessary?

### ISSUE THREAD

**Issue by pvsomebody** [bwinton/TabCenter#366]
It was never there when I was using Firefox with standard skin on a few Linuxes, but it's here after installing Tab Center and I find my eyes drawn there without any good reason, since the colors of the panel above and below the plus are also different.

Is this a deliberate design decision or an oversight?

**Comment by bwinton** [comment]
Well, I think it was originally a deliberate design decision, but we've since gone back and done a style refresh, so I'm going to assume that the new deliberate design fixed this.  😉  Feel free to re-open this and attach a screenshot if you still run into it.  Thanks!

**Comment by pvsomebody** [comment]
Now, that it is aligned with the line separating the toolbar, the one with
the address line from the rest of the web page, it is perfect. :)

2016-08-22 21:29 GMT+03:00 Blake Winton <notifications@github.com>:
