### ISSUE TITLE
Sidebar is messed up …

### ISSUE THREAD

**Issue by manngo** [bwinton/TabCenter#367]
Sidebar items no longer appear correctly on the side, but occupy some space on the left of the visible page area:

- If the vertical tabs are not pinned, opening a sidebar item (`View:Sidebar:…`) results in the item occupying a narrow strip offset from the top by about 10cm.
- If the vertical tabs are pinned, the same occurs, but it is now wider with some buttons along the top of the panel. The viewing area is now full width, ignoring the vertical tabs.

However, when testing again, the width and positioning of the sidebar was not consistent.

Using FF47 on OSX 10.11.5

**Comment by armenzg** [comment]
I'm using FF50 (nightly) on Linux and I don't notice anything strange.

Do you still have the issue?
Could you please attach a screenshot to help us visualize what to look for?

**Comment by bwinton** [comment]
We've done a bunch of work to fix this, so I believe it's no longer an issue.  Feel free to re-open it and attach a screenshot if you're still running into this bug.  Thanks!
