### ISSUE TITLE
On start lack of an 'add new tab' button

### ISSUE THREAD

**Issue by pasi1** [bwinton/TabCenter#370]
on start i don't have a 'add new tab' button but when i call <ctr>+<n> there is. -vertical tabs menu

**Comment by bwinton** [comment]
This sounds kind of strange.  Can you let us know which OS and version of Firefox you're using, and attach a screenshot or two showing the problem?  Thanks!

**Comment by pasi1** [comment]
it is Firefox 47.0 on Ubuntu 14.04.4 LTS

![Uploading firefox47.jpg…]()

... you really don't like linux systems ;-)
https://www.dropbox.com/s/l4vudkzd9lq2b34/firefox_47.png?dl=0
first is when i just start the ff second on right is from <ctrl>+<n>

**Comment by pasi1** [comment]
ups sorry it is Tab Center... sorrry. i mess up

**Comment by yacut** [comment]
I had the exact same problem, after disabling the [Tab Mix Plus](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/ ) addon it was solved.

**Comment by pasi1** [comment]
Yes, i did this same and now i'v got '+', but i'm big fan of tab mix plus so probably  things go to remove 'VerticalTabs'. VT is less enjoyable when you have to work on two screens and it is rolling up over the mouse every time when is travelling between screens.
But idea is well!

**Comment by ericawright** [comment]
duping to #464
