### ISSUE TITLE
Auto-expansion when Windows taskbar is also hidden on left side of screen is tedious

### ISSUE THREAD

**Issue by jimokam** [bwinton/TabCenter#374]
I may be one of 1000 users who has my Windows taskbar on the left side of the screen, set to auto-hide.  So when I want to switch tabs I often move the mouse too far to the left and unhide the taskbar instead.  Is there a chance that an option can be added that will expand the tabs on pressing a certain key combination?  This would make it much easier to select a tab without inadvertently touching the edge of the screen.  It would also give some added functionality to my gaming mouse's programmable buttons.

Thanks,

Jim

**Comment by jschwartzentruber** [comment]
This also affects Ubuntu/Unity with auto-hide launcher enabled.

**Comment by bwinton** [comment]
We now have a key combo (`ctrl`-`shift`-`k`) to toggle the sidebar, which should help.
I believe the rest of this will be fixed by #7, so I'm going to close this issue.  Thanks!
