### ISSUE TITLE
High CPU usage with background tabs activity

### ISSUE THREAD

**Issue by lissyx** [bwinton/TabCenter#379]
STR:
1. Have some tabs opened, including for example Facebook and Hangouts with chat session started
2. Switch to reading one other tab
3. Wait for messages to arrive in the chats

Expected:
 Animation of the tab has no impact

Actual:
 I see |firefox| process going to 100% CPU

Reproduced since the early days of Vertical Tabs in Test Pilot, Linux Ubuntu 15.10 with e10s enabled.

**Comment by lissyx** [comment]
I'm still experiencing this. Reproducing tabs are some pinned ones. I cannot say if it only happens for pinned tabs though.

**Comment by bwinton** [comment]
https://github.com/bwinton/VerticalTabs/blob/master/verticaltabs.jsm#L134 looks like it might be part of the problem…  Perhaps also https://github.com/bwinton/VerticalTabs/blob/master/verticaltabs.jsm#L188

**Comment by abFx** [comment]
same here, with last release it seems to be consuming a lot of cpu and its gettings slower and slower, maybe just keeping it simple as it was before, just text, no images or lazy load for non blocking experience

**Comment by lissyx** [comment]
This is still happening for me, clearly hard to live with :/

**Comment by lissyx** [comment]
I don't know if anything changed on Nightly's side or on TabCenter side, but I noticed today (might have started before) that I don't see huge CPU spike, and my fan is not blowing anymore.

This is on a linux ubuntu 16.04 nightly, https://hg.mozilla.org/mozilla-central/rev/969c3295d3aa77931cca26eddb047d9d74bd9858 TabCenter being 1.26.0

**Comment by lissyx** [comment]
Still no problem, I will close and re-open if the issue comes again.
