### ISSUE TITLE
Distinguish between new background tabs and visited tabs

### ISSUE THREAD

**Issue by lewisl9029** [bwinton/TabCenter#383]
I'd like to see some visual indicator for tabs that have been opened in the background but haven't been visited yet (i.e. italicize the title text, adjust the background color, add a color strip, etc) . This would help users more easily keep track of which tabs they still need to visit after opening a large number of tabs in the background.

**Comment by bwinton** [comment]
This is an interesting idea, but it's a pretty large change from the way things currently work, and so I don't think we're going to do it in this experiment.  Thanks for the suggestion, though!  🙂

**Comment by lewisl9029** [comment]
Thanks for the follow up @bwinton!

To clarify, are you against adding something like this entirely? Or is it just not going to be a priority for the core team?

I guess what I'm asking is: would you accept a PR for something like this? I'm definitely willing to working with your UX team to revise the feature until the UX is sound.

**Comment by bwinton** [comment]
I don't think it's a bad idea, but I don't think it's something we want to add.  (We're going to be putting this in front of a larger, less technical, group of people soon, and I think this will be more confusing than it would be helpful for them.)

But, after that test is done, it does seem like something we could add an option for if you wanted to make a PR.  (Perhaps you could make it a hidden option like `largetabs`?)

**Comment by lewisl9029** [comment]
Sounds good. I might not have time to work on the PR for another month or two anyways. I'll definitely remember to hide it under a hidden option when I do get started. =)
