### ISSUE TITLE
Tab Center Issues: Covering Essential Navigational Buttons and Freezing Issues

### ISSUE THREAD

**Issue by MozillaPilot** [bwinton/TabCenter#385]
I've just recently discovered some issues that involve the Tab Center, as of late I've been noticing that the Tab Center at times whenever I close tabs that has been on for a long time, it temporarily freezes my browser. Now, today on the 27th of June, 2016, approximately at 6:16 am (PST: Pacific Standard Time) my Tab Center has taken over the main part of the navigation bar (Back and Forward) buttons. I tried to rectify the issue, by restarting my browser a couple of times and restarting the feature from the Mozilla Test Pilot Page, but those attempts seems to not work. I have completely suspended my usage of the Tab Center, until a new and fixed version of the Tab Center is developed and released. 

Don't get me wrong I love it, it made the top portion of my browser seem much more slicker than what it now is (again). So please, I implore you guys at Mozilla to develop a newer version of the Tab Center where the bugs are fixed and it runs smoothly whenever it's installed onto the browser. 

I'm currently on iOS X El Capitan (10.11.5), using Mozilla Firefox 47.0.

**Comment by ericawright** [comment]
@MozillaPilot Thank you for the feedback. Is there any chance that you can provide a screenshot of this happening?

**Comment by MozillaPilot** [comment]
![screen shot 2016-06-27 at 6 39 25 am](https://cloud.githubusercontent.com/assets/20167801/16381648/64371940-3c32-11e6-9fe5-f91a87d0cb6b.png)

**Comment by bwinton** [comment]
We've done a bunch of work to fix this, so I believe it's resolved now, but please feel free to re-open this issue with steps to reproduce the problem if you're still seeing it.  Thanks!
