### ISSUE TITLE
Set up issue template listing incompatible add-ons

### ISSUE THREAD

**Issue by chuckharmston** [bwinton/TabCenter#390]
Lots of energy is spent debugging what turns out to be an incompatibility with other add-ons. It might be nice to [borrow a page from Test Pilot's handbook](https://github.com/mozilla/testpilot/blob/master/.github/ISSUE_TEMPLATE.md) and use a [GitHub issue template](https://github.com/blog/2111-issue-and-pull-request-templates) to indicate addons that are known to cause issues?

**Comment by ericawright** [comment]
related to #372 Can add an issue template, and feature request section

**Comment by mlissner** [comment]
Related is #464, where a list of incompatible add-ons are being listed.
