### ISSUE TITLE
Dragging tab does not automatically change viewable area of long tab list

### ISSUE THREAD

**Issue by csalsa** [bwinton/TabCenter#396]
Steps to reproduce:
1. Create enough tabs to tab list so list extends over one full "page"
2. Scroll to bottom and attempt to drag tab to top of list.
Behavior is the view over the tab list does not automatically scroll up so tab can be placed at top of tab list.  Instead tab can be put in list at position top of viewable tabs.

**Comment by bwinton** [comment]
Thanks for the report, @csalsa!  It looks like we're fixing this as part of #494, so I'm going to close this issue and we can track it there…
