### ISSUE TITLE
Dual Scollbar in the tab section

### ISSUE THREAD

**Issue by npusr** [bwinton/TabCenter#406]
Even if I have only few tabs the side bar has an scroll bar 

![capture](https://cloud.githubusercontent.com/assets/9779729/16797546/aaa775e8-4905-11e6-8c85-40711f9cbb62.PNG)

When number of tabs increases bayond the side bar height instead of extending current scroll bar , a another new scroll bar is created.

![capture2](https://cloud.githubusercontent.com/assets/9779729/16797674/349ca188-4906-11e6-82bd-754a645668ed.PNG)

**Comment by ericawright** [comment]
We have fixed this issue for a few operating systems, can you let me know what you're using as we may have missed it?

**Comment by devm-ru** [comment]
@ericawright I have the same. Archlinux. Firefox DevEdition 49.0a2.

**Comment by bwinton** [comment]
This should be fixed now that we removed all the scrollbars!  😃
