### ISSUE TITLE
Odd vertical gap and misplaced X icon when quickly mousing over sidebar

### ISSUE THREAD

**Issue by pdehaan** [bwinton/TabCenter#41]
Found in 1.9

### Steps to reproduce:
1. Install latest add-on.
2. Quickly mouse over the sidebar a few times.

### Actual results:
Sometimes I'm getting an odd gap between the "New Tab" to bar and the first tab (in this case "New Tab"). Sometimes even just moving my mouse vertically along the list of tabs causes things to shift unexpectedly.

Also, the "X" isn't always pinned to the right, but then if you mouse over other items, it shifts over into the correct spot.

![new_tab_and_add-ons_manager_and_irccloud_and_bwinton_verticaltabs__firefox_add-on_for_arranging_tabs_vertically](https://cloud.githubusercontent.com/assets/557895/14511193/9d5afc24-018a-11e6-9976-7c9b7e276d22.png)

**Comment by johngruen** [comment]
@pdehaan I can't repro...gif?

**Comment by pdehaan** [comment]
I can reproduce the vertical gap (i'm heavily leaning towards it being pinned tab related), but oddly cannot reproduce the floating close button today.

#### GIF AHOY!
![tabcenter1_9](https://cloud.githubusercontent.com/assets/557895/14611808/efd51ab8-0548-11e6-936a-ffafe5a0922c.gif)

**Comment by bwinton** [comment]
@pdehaan Can you try to replicate this again?  I think it was pinned-tab related, and we've re-written a bunch of that code…

**Comment by bwinton** [comment]
And closing due to massively re-written code and a new style refresh.  😉
