### ISSUE TITLE
Allow tab bars to be pinned open by default

### ISSUE THREAD

**Issue by rnewman** [bwinton/TabCenter#431]
Sometimes my setting for having the tab bars open and pinned is lost, so I have to go flicking through windows expanding and pinning each. I never want my tab bar to auto-collapse; I find the animation visually uncomfortable, and thumbnails aren't enough for me to predict a mouse target, so I need to hover, expand, skim, aim, and click, which takes much longer.

**Comment by bwinton** [comment]
This should be saved per-window.  If you can figure out when it gets lost, that would be helpful in trying to figure out what's happening in this bug!

**Comment by mlissner** [comment]
Could this be a duplicate of #391 ?

**Comment by rnewman** [comment]
That seems like a reasonable hypothesis to me.
