### ISSUE TITLE
Icons misaligned after latest update

### ISSUE THREAD

**Issue by TDA** [bwinton/TabCenter#436]
The latest update to 48.0b9 seems to have broken vertical tab icons. I can now resize the `tabcenter`, but the icons are lopsided:
<img width="279" alt="screenshot 2016-07-22 01 17 43" src="https://cloud.githubusercontent.com/assets/432707/17050902/55ed6c46-4faa-11e6-878d-b114285ccf0b.png">

Could I just have the previous version that was working fine?

**Comment by ericawright** [comment]
I was wondering if this concern was because there were no screenshots. Are there still none showing for you?

**Comment by TDA** [comment]
@ericawright Yup, still none there :( Nothing on restored/pinned tabs :(

**Comment by ericawright** [comment]
new design work has come out, and the screenshot images are fixed thanks to #522.
