### ISSUE TITLE
Pinned Tabs not showing screenshots

### ISSUE THREAD

**Issue by ericawright** [bwinton/TabCenter#442]
<img width="214" alt="screen shot 2016-07-22 at 11 24 05 am" src="https://cloud.githubusercontent.com/assets/10803178/17061844/71516ff6-4ffe-11e6-8282-23624daa5691.png">

Neither on opening the browser, nor after making a new pinned tab

**Comment by TDA** [comment]
Aha! So thats why I thought the icons were lopsided: https://github.com/bwinton/VerticalTabs/issues/436 Didnt know they were supposed to show a mini-screenshot :D

**Comment by eoger** [comment]
It looks like it happens only for restored tabs in my case

**Comment by Keith94** [comment]
Fixed?

**Comment by bwinton** [comment]
I believe so.  We're way better at getting thumbnails these days…  🙂
