### ISSUE TITLE
The "Search" input box from the Sidebar is not aligned with the "New Tab" and "Keep Sidebar opened" buttons

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#460]
![search bar container not centered](https://cloud.githubusercontent.com/assets/18304511/17101753/eae992b2-527e-11e6-96c3-7b669c3ecdf0.png)

[Affected versions]:
- Firefox 45 and up
- Tab Center 1.22

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- latest Tab Center add-on is installed

[Steps to reproduce]:
1. Hover over the Tab Center Sidebar and click the "Search" bar.
2. Observe the Search input box position comparing it to the "New Tab" and "Pin" buttons.

[Expected result]:
The Search input box is aligned with the "New Tab" and "Keep Sidebar opened" buttons.

[Actual result]:
The Search input box is positioned lower than the "New Tab" and "Keep Sidebar opened" buttons.

[Notes]:
- Also the "Search" icon and cursor seem to not be centrally positioned in the text box.
- Attached a screenshot of the issue.

**Comment by Keith94** [comment]
This should be fixed.

**Comment by SoftVision-CiprianMuresan** [comment]
This issue is no longer reproducible on the latest Tab Center version. It seems to have been fixed along the way.
