### ISSUE TITLE
Opening new tab with alt+enter opens the tab at the botton

### ISSUE THREAD

**Issue by powerfool** [bwinton/TabCenter#462]
In an existing tab with some page loaded, type something in the address bar and hit alt+enter. A new tab will open with that link but it will open at the bottom of the list.

**Comment by Keith94** [comment]
It's normal, Firefox does that by default. Are you suggesting to change the default behavior somehow?

**Comment by powerfool** [comment]
You're right, it does that by default. However, without Vertical Tabs, on Firefox the tab priority is usually from right to left (at least for me), on the right being the most recent tabs I'm using. In that case, opening a tab with alt+enter on the URL bar just places it close to where my current focus is. 

With Vertical Tabs though, I usually keep the most recent tabs on the top of the list so when I open a tab with alt+enter and it opens at the bottom, that's a bit inconvenient. 

I guess the option should be getting reversed if I'm using Vertical Tabs. New tabs should always open at the top of the stack.

Does that make sense?

**Comment by Keith94** [comment]
It makes sense, it would be nice to see an option to open these tabs at the top rather than the bottom...

**Comment by SoftVision-CiprianMuresan** [comment]
There is an option in about:addons which allows you to open new tabs at the top. 
![newtabsopenatthetop](https://cloud.githubusercontent.com/assets/18304511/17131468/4816426c-5326-11e6-9d0d-34a57b09f13a.png)

**Comment by powerfool** [comment]
I have this enabled but still observe the behaviour I just described. Thanks @SoftVision-CiprianMuresan.

**Comment by SimonSapin** [comment]
I’m observing this issue as well. With the option enabled, CTRL+T creates a new tab on top. But clicking on an URL from another desktop application (running `firefox http://example.net`) or clicking Addons or Preferences in Firefox’s hamburger menu crates a new tab at the bottom.

As a result, I tend to have recently-used tabs both near the top and near the bottom. #551 makes this even more painful.
