### ISSUE TITLE
Don't switch to large tabs (or small tabs) when my mouse is in the tabbar.

### ISSUE THREAD

**Issue by Manishearth** [bwinton/TabCenter#465]
I'm fine with cheese being moved, I'm less fine with cheese being moved when I'm in the process of eating it 😄 

When a tab is closed, we should wait for the mouse to exit the tab area (if it is in it), and then perhaps wait for X more seconds of mouse-not-being-in-the-tab-area.

**Comment by bwinton** [comment]
That's a pretty drastic divergence from the way the tabbar normally operates, and I don't think we're going to fix this.  (It would also make it hard to close multiple tabs by clicking on the "x".)

Is there a problem you're running into that perhaps we could fix another way?

**Comment by Manishearth** [comment]
Wait, why would it make it harder to close multiple tabs by clicking on the x? This makes it easier.

As it stands if I'm trying to close two tabs (or close one tab and switch to another), and the first tab closed brings it down below the threshhold and makes the tabs larger. This means that I end up clicking the wrong tab for the second tab.



... it occurs to me that I wasn't specific enough about what I meant by "reflow". I mean `resizeTabs()` -- when the tabs suddenly revert to being large.

**Comment by bwinton** [comment]
Ah, yeah, that makes more sense…  I'll edit the title to reflect it.
