### ISSUE TITLE
Preview Issue + Pin/Full-screen Issue

### ISSUE THREAD

**Issue by JojoJojoJoey** [bwinton/TabCenter#468]
Issue 1:
The tab preview thumbnail function does not work for sites requiring log-in. For example, the preview thumbnail for Facebook pages is the log-in page.

Issue 2:
When the left tab bar is pinned (so that it will not minimise), it will stay there when I view a full-screen youtube video. The tabs won't show, instead the tab bar appears as a blank background (from firefox themes).
-------------------------------
Apple OS X El Capitan 10.11.5
Firefox 47.0

**Comment by ericawright** [comment]
for the second issue, it should be fixed with #449

**Comment by ericawright** [comment]
the first issue will be fixed with the next release thanks to #522
