### ISSUE TITLE
The "New Tab" button can't be placed back in the Sidebar if it was removed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#471]
[Affected versions]:
- Firefox 45 and up
- Tab Center 1.23

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Tab Center add-on is installed

[Steps to reproduce]:
1. Hover the Sidebar to display it.
2. Right click the "New Tab" button and click either "Move to Menu" or "Remove from Toolbar".
3. Click the Firefox "Menu" button and click Customize.
4. Drag the "New Tab" button to the Sidebar and release the mouse button.

[Expected result]:
The "New Tab" button is placed in the Sidebar.

[Actual result]:
The "New Tab" button can't be placed in the Sidebar since it's not visible in customization mode.

[Notes]:
- If either of the options are selected the button will not be visible to the user unless he enters the Menu or Customization.
- Attached a screen recording of the issue.

[newtab button cant be placed back after being removed.zip](https://github.com/bwinton/VerticalTabs/files/388374/newtab.button.cant.be.placed.back.after.being.removed.zip)

**Comment by bwinton** [comment]
Yeah, we should disable the "Move to…" menu items for the New Tab button.

**Comment by ericawright** [comment]
Also happens if the new tab button has been moved though customization before tab center
