### ISSUE TITLE
Right clicking on the "Pin" button has the added effect of pinning or unpinning the Sidebar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#472]
[Affected versions]:
- Firefox 45 and up
- Tab Center 1.23

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Tab Center add-on is installed
- Sidebar is unpinned.

[Steps to reproduce]:
1. Hover the Sidebar to display it.
2. Right click the "Pin" button.

[Expected result]:
The context menu for the button appears.

[Actual result]:
The context menu for the button appears and the Sidebar is pinned open.

[Notes]:
- The same thing happens if you right click the "Unpin" button to unpin the Sidebar. 
- Attached a screen recording of the issue.

[right click on pin button pins the sidebar.zip](https://github.com/bwinton/VerticalTabs/files/388402/right.click.on.pin.button.pins.the.sidebar.zip)

**Comment by SoftVision-CiprianMuresan** [comment]
@ericawright, I've just observed that the "Move tabs to the top" button has the same behaviour. Could you also fix this in #729 seeing as it isn't merged yet?

**Comment by ericawright** [comment]
yup, thanks

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest build (1.26.0).
