### ISSUE TITLE
The "Pin/Unpin" button has the same tooltip for both actions

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#473]
![incorrect tooltip](https://cloud.githubusercontent.com/assets/18304511/17214375/4bf5229c-54e1-11e6-80a1-65512dd25378.png)

[Affected versions]:
- Firefox 45 and up
- Tab Center 1.23

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Tab Center add-on is installed
- Sidebar is unpinned.

[Steps to reproduce]:
1. Hover the Sidebar to display it.
2. Hover the "Pin" button and observe the tooltip.
3. Pin the Sidebar and then hover the "Unpin" button.
4. Observe the tooltip.

[Expected result]:
A tooltip explaining what the button does appears.

[Actual result]:
The same tooltip appears as the one for pinning the Sidebar.

[Notes]:
- Attached a screenshot of the issue.

**Comment by bwinton** [comment]
Will be fixed by #485…
