### ISSUE TITLE
Rearranging tab removes the URI text from it

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#475]
![giphy](https://cloud.githubusercontent.com/assets/5490615/17363685/c3f84474-5930-11e6-925e-671028916612.gif)

**Comment by bwinton** [comment]
@Manishearth: I think this might be related to your patch…  Can you take a look at what's happening here?

**Comment by Manishearth** [comment]
Won't have time till monday, but yes 😄

**Comment by Manishearth** [comment]
At a quick glance -- we added an updateURI call where it initially didn't exist (https://github.com/bwinton/TabCenter/pull/467/files#diff-d8933c1a1ae4976d98ba20545c5f0b36R616). Perhaps we should only have it update the label if nonempty?

**Comment by bwinton** [comment]
Yeah, that might work…

**Comment by Manishearth** [comment]
Turns out that updateURI doesn't get called when the tab is moved, so this seems to be caused by some other change?

**Comment by bwinton** [comment]
So, given what you said, I now suspect the problem is that we're moving around a XUL element, but not re-calling the updateURI method, so our custom URI gets deleted by the XUL movement, and not re-added.

**Comment by Manishearth** [comment]
Why would we need to re-call on moving an element? Don't elements keep their contents when moved?

**Comment by bwinton** [comment]
It looks like no… 😕  (I'm guessing that the main element is preserved, but all the anonymous content it contains gets re-generated.  Which leads me to wonder if we should set the address on the `tab`, and have it  filter down into the `address-label`…)
