### ISSUE TITLE
Miniature previews are not displayed for some tabs, pattern unknown

### ISSUE THREAD

**Issue by pvsomebody** [bwinton/TabCenter#477]
Please see attached screenshot.
![screenshot from 2016-08-02 10-26-17](https://cloud.githubusercontent.com/assets/13513395/17320441/3a5afe80-589c-11e6-88ff-3339900a27de.png)

Always reproducible with add-ons disabled on openSUSE Linux, latest Mozilla.

**Comment by tkafka** [comment]
For me, some of the tabs which are not loaded (when I restart Firefox for example) seem to be black.

**Comment by ericawright** [comment]
this will be fixed with the new release coming soon. #522
