### ISSUE TITLE
Tooltip color change on "Test Pilot" button after enabling "Tab Center" experiment

### ISSUE THREAD

**Issue by wresuolc** [bwinton/TabCenter#489]
Original report @ https://github.com/mozilla/testpilot/issues/1165

-------------------------------------------------------------

[Affected versions]:

    Nightly 50.0a1
    Test Pilot 0.8.3 -tag-2016-07-29

[Affected Platforms]:

    All Windows
    All Mac OS
    All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net page.
2. Click on the big green "Install the Test Pilot Add-on" button.
3. Observe the "Test Pilot" button from browser toolbar.
4. Chose the "Tab Center" experiment and "Enable" it.
5. Observe again the "Test Pilot" button from browser toolbar.

[Expected result]:
In both cases the "Test Pilot" button is displayed with a blue "New" tooltip over it.

[Actual result]:
Step 3 - the "Test Pilot" button is displayed with a blue "New" tooltip over it.
Step 5 - after "Tab Center" installation, the tooltip changes its color into red.

[Notes]:

    Added a screen recording with the issue https://goo.gl/uCdqbH.

**Comment by bwinton** [comment]
Right, so, TabCenter removes and replaces the toolbar, which causes the elements to be re-created, and the style that is set on the element to be dropped.

You can get the same effect by replacing "Enable Tab Center" with "Enter Customize Mode", thus I'm confident in claiming that this isn't a Tab Center bug, and will re-open the issue in Test Pilot.  Sorry!
