### ISSUE TITLE
Places context menu is broken

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#490]
Issue caused by latest patch 1e95d53, the context menu for bookmarks toolbar items is completely disabled (all items are grayed out).

![snag 2016 08 05 10 57 36](https://cloud.githubusercontent.com/assets/5490615/17445840/6ec2e226-5afb-11e6-98de-29abc2822b45.png)

**Comment by ericawright** [comment]
I'm unable to duplicate this. 
<img width="297" alt="screen shot 2016-08-17 at 3 14 21 pm" src="https://cloud.githubusercontent.com/assets/10803178/17755093/d4c35674-648c-11e6-89ba-47fed448f4af.png">

Is it still happening, and if so, can you tell my what OS you're on?

**Comment by Keith94** [comment]
I can reproduce on Windows 8.

**Comment by Keith94** [comment]
I can still reproduce this on Windows 8, with the latest dev version from GitHub.

**Comment by ericawright** [comment]
![screen shot 2016-08-18 at 10 30 06 am](https://cloud.githubusercontent.com/assets/10803178/17783749/44851744-652e-11e6-8e9e-26f4381b7d5a.png)
from windows 8.1

**Comment by bwinton** [comment]
Are there any add-ons that might be conflicting here?

**Comment by Keith94** [comment]
I notice this issue with Tab Center only in a clean profile, but feel free to close this..

**Comment by JohnBrewer** [comment]
Same problem Windows 10, both Firefox 47.0.1 and 48.0.1.

**Comment by xenithorb** [comment]
Also seeing this with Dev Edition 50.0a2 on Linux (Fedora 24)

**Comment by kkot** [comment]
I have same problem Firefox 49, Windows 10.

**Comment by SoftVision-PaulOiegas** [comment]
This is a dupe of #583. I have provided the exact steps to reproduce there.

**Comment by Keith94** [comment]
Fair enough.
