### ISSUE TITLE
When a new tab is focused, Tab Center scrolls to the previously-focused tab

### ISSUE THREAD

**Issue by roryokane** [bwinton/TabCenter#492]
My Tab Center has many tabs open, enough that I have to scroll to see all my tabs. I have noticed that whenever I change the current tab, whether by using hotkeys to switch tabs or by opening a new tab, the Tab Center scrolls to make the previously-focused tab visible. But the desired behavior is to scroll the make the newly-focused tab visible.

This happens when I change the current tab with the hotkeys <kbd>Ctrl-Tab</kbd>, <kbd>Command-Shift-{</kbd>, or <kbd>Command-Shift-}</kbd>. This also happens when I open a new tab, no matter the method – clicking “New Tab”, pressing <kbd>Command-T</kbd>, <kbd>Command</kbd>-clicking a link, or opening a link from an external program.

An easy way to reproduce the problem:

1. Open a new window with <kbd>Command-N</kbd>.
1. **[Edit](https://github.com/bwinton/TabCenter/issues/492#issuecomment-241180928):** Make sure “Keep sidebar open” (formerly “keep pinned”) is enabled in the top right of Tab Center.
1. Repeatedly press <kbd>Command-T</kbd> until there are enough tabs that a scrollbar appears.
1. Press <kbd>Command-Shift-{</kbd> to switch from the first tab (the most recently created one) to the last tab (the one that the window opened to). You will see that the Tab Center does not scroll at all, so the currently-selected tab is not visible in the Tab Center.
1. Press <kbd>Command-Shift-}</kbd> to switch from the last tab in the list back to the first tab. You will see the Tab Center scroll to show the tab that was just selected – but the new selected tab is once again hidden.

**Comment by ericawright** [comment]
Unable to duplicate. @roryokane is this still happening for you?

**Comment by roryokane** [comment]
Yes, this is still happening. However, I have not restarted my browser since then, so perhaps that might fix it.

I’ll post back after I’ve saved the contents of my tabs and restarted. If I can still reproduce the bug after restarting, I’ll also try installing Tab Center in a new Firefox profile and see if I can reproduce it like that.

**Comment by roryokane** [comment]
I found out why this probably wasn’t reproducing for you: the bug only happens when “Keep sidebar open” has been clicked. When the sidebar is shrunken, tabs are scrolled to immediately, which is what should happen.

With “Keep sidebar open” enabled, I was also able to reproduce this problem in a new Firefox profile that had nothing but Tab Center installed.

**Comment by ericawright** [comment]
what I am seeing is this:

![aug-23-2016 11-39-58](https://cloud.githubusercontent.com/assets/10803178/17904919/13fd5360-6926-11e6-8171-7148fec04cea.gif)

TC scrolls, but the tab is covered by the arrow buttons
