### ISSUE TITLE
Tabs opened from external programs open at the bottom of the list, unlike manual new tabs

### ISSUE THREAD

**Issue by roryokane** [bwinton/TabCenter#493]
When I click the New Tab button or press <kbd>Command-T</kbd>, new tabs open at the top of the list. This is different from the non-Tab-Center Firefox default of opening at the right of the list, presumably because the New Tab button is at the top instead of at the bottom. However, there is an inconsistency.

If I click a link in an external program that opens a page in my default browser – for example, double-clicking a web location file in the Finder, or clicking a link in my calendar program – the new tab for that link opens at the bottom of the list instead of the top of the list. This inconsistency means that if I open an external-program link, and then want to open some new tabs to research the same topic, those new tabs will be created in the list as far as possible from the tab for that link. This makes it harder to refer between those related tabs, especially when the tab list is long enough to need to be scrolled.

Solution: new tabs opened from links in external programs should be created in the same place as new tabs from clicking New Tab – at the top of the tab list.

**Comment by ericawright** [comment]
closing as dupe of #491

**Comment by roryokane** [comment]
Whoops, you forgot to actually mark this as closed.
