### ISSUE TITLE
When dragging a tab in the list and the pointer nears the edge, the list should scroll

### ISSUE THREAD

**Issue by roryokane** [bwinton/TabCenter#494]
I have many tabs open in Tab Center, enough that I have to scroll to see all my tabs. Sometimes, new tabs are not opened next to the other tabs they are related to, so I would like to drag them next to those tabs. But if the destination in the tab list is offscreen when the list is scrolled so the tab I want to drag is visible, there is no way to move the tab to the destination with just one drag-and-drop.

This problem is most noticeable when mixing new tabs opened with Command-T, and new tabs opened by clicking a link in an eternal program. Due to bug #493, the former type of tab currently opens at the top of the list, while the latter type opens at the bottom of the list. If I want to move a new tab from an external program next to my recent manually-opened new tabs, I have to drag it from the bottom of the list to the top of the list. But since I have eight screenfuls of tabs, this means I have to repeat the following at least eight times: drop the tab near the top of the visible area, scroll the list until the tab is near the bottom of the visible area, then start dragging the tab again.

The solution is exhibited in standard controls on multiple OSs. When dragging an item within the list, if the cursor comes within a certain distance of the visible edge of the list, the list should start scrolling in that direction. Moving the cursor farther towards or past the edge of the list should increase the scrolling speed further. The scrolling speed while the mouse is still should gradually increase, maybe quadratically, so that long lists can be navigated in reasonable time. When the cursor moves more than a certain distance away from the edge of the list (on the side of the list content), the scrolling should stop. At any time, releasing the mouse click should place the dragged item under the cursor and stop the scrolling.

You can easily see an example of this desired scrolling behavior by typing many paragraphs into a text area in Firefox, such as the GitHub issue comment text area, then dragging to select text and moving the mouse past the end of the text area.

**Comment by Keith94** [comment]
#396 is the same too.
