### ISSUE TITLE
Little unusable with bookmarks panel open.

### ISSUE THREAD

**Issue by Zefling** [bwinton/TabCenter#495]
Tabs panel are much too far. Is it possible to choose the side of tabs or bookmarks ?

![tabs](https://cloud.githubusercontent.com/assets/3032555/17455545/e12806f6-5bba-11e6-9dab-b03b7aafac1e.png)

**Comment by bwinton** [comment]
You can't currently choose which side the tabs open on, but that's being tracked in #7.
For the bookmarks, I found [an add-on](https://addons.mozilla.org/en-US/firefox/addon/rightbar/) (which I haven't tested at all!) which looks like it might do the trick…

Good luck, and thanks for reporting the issue!  🙂
