### ISSUE TITLE
Add tree hierarchy for tabs

### ISSUE THREAD

**Issue by Randl** [bwinton/TabCenter#498]
Possibility to arrange tab into tree-style hierarchy, like in [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab) addon simplifies woek with big amount of tabs greatly

**Comment by bwinton** [comment]
Nope.  This add-on is aimed at a less technical audience, and not having a hierarchy is one of the more important simplifications we're making.  (I really like Tree Style Tabs, though, and think it perfectly fits the audience it's going for!  🙂)

**Comment by AaronHarris** [comment]
I support having this crucial feature as an configurable option, but not as the default view for new users.

**Comment by bwinton** [comment]
Be that as it may, it's not going to be added to this add-on.  I heartily recommend Tree Style Tabs, if that's something you're looking for!

**Comment by mimoo** [comment]
Unfortunately Tree Style Tabs is likely to be phased out by removal of the XUL plugins.
