### ISSUE TITLE
Private browsing icon is invisible in normal windows

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#502]
In private browsing mode, the tabs toolbar seems to be lacking the purple badge and only has a blank space there:

![snag 2016 08 08 09 00 30](https://cloud.githubusercontent.com/assets/5490615/17486683/9a49a02c-5d46-11e6-9472-c8be18c60ce1.png)

Except when I put the window in fullscreen mode, now the badge appears correctly in the toolbar:

![snag 2016 08 08 09 00 14](https://cloud.githubusercontent.com/assets/5490615/17486686/9e7d6426-5d46-11e6-819c-0a5df593992d.png)

**Comment by ericawright** [comment]
could not duplicate the change between full screen and not, on Windows 10. However, in the meantime we will likely be hiding the badge.

**Comment by Keith94** [comment]
I'm using windows 8.

**Comment by ericawright** [comment]
interesting, tested on windows 8.

fullscreen:
<img width="1102" alt="screen shot 2016-08-08 at 4 24 43 pm" src="https://cloud.githubusercontent.com/assets/10803178/17499755/46273e26-5d84-11e6-97c3-5d2b9eb1562b.png">

windowed:
<img width="986" alt="screen shot 2016-08-08 at 4 24 20 pm" src="https://cloud.githubusercontent.com/assets/10803178/17499775/7c18cf90-5d84-11e6-9fff-c3a9f32141fc.png">

**Comment by Keith94** [comment]
If you press F11 do you see it now in fullscreen?

**Comment by ericawright** [comment]
oh, I was mistakenly testing with the brand new branch which hasn't been released yet. Yes I can see the private browsing icon. However, I see it both in windowed and in fullscreen.
![screen shot 2016-08-08 at 4 37 58 pm](https://cloud.githubusercontent.com/assets/10803178/17499950/151116ca-5d86-11e6-90b5-91b5c883e1a2.png)
![screen shot 2016-08-08 at 4 38 16 pm](https://cloud.githubusercontent.com/assets/10803178/17499951/19d47b48-5d86-11e6-810c-579af313d1d1.png)

**Comment by Keith94** [comment]
You're right, the 'unreleased' version is just bugged then, so it doesn't show the icon for me.
