### ISSUE TITLE
When tabs toolbar is narrow, buttons don't fit or align correctly

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#504]
For example, when entering private browsing fullscreen mode, it causes buttons to get squished as shown below.

Suggestion is to maybe move the tab find bar below other buttons, and possibly hide "New Tab" label in such a case.

![snag 2016 08 08 09 38 50](https://cloud.githubusercontent.com/assets/5490615/17487962/04dcefc0-5d4c-11e6-8df1-ffe5c4257804.png)

**Comment by ericawright** [comment]
I'm concerned by the minimize and restore buttons being in the toolbar, as then should never be there. have you done some customization or have any other relevant add-ons installed?

**Comment by Keith94** [comment]
I only used Nightly with a clean profile + Tab Center (latest dev version from github).

**Comment by ericawright** [comment]
This is a combination of #502 which has been fixed and #509 which is a little more descriptive - will track it there, thanks!
