### ISSUE TITLE
Style: Scroll Bar Covers X

### ISSUE THREAD

**Issue by ericawright** [bwinton/TabCenter#505]
Can be hard to click the `x` button when there are enough tabs for a scroll.

<img width="59" alt="screen shot 2016-08-08 at 2 31 01 pm" src="https://cloud.githubusercontent.com/assets/10803178/17496961/71742734-5d74-11e6-8d52-6aa73a0df3e3.png">

**Comment by TDA** [comment]
<img width="1280" alt="screenshot 2016-08-17 15 46 19" src="https://cloud.githubusercontent.com/assets/432707/17755964/ee21c3b2-6491-11e6-87c0-660bf2800f0a.png">

@ericawright Was this fixed? Or only affects certain version/screen sizes? Cuz I dont see it in FF 45.3 ESR on 13" MBP

**Comment by ericawright** [comment]
@TDA this is a screenshot from the in-development version which has not been released yet.

**Comment by ericawright** [comment]
fixed with V1.24
