### ISSUE TITLE
Window buttons wrongly displayed in full screen mode on Windows 10

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#509]
[Affected versions]:
- Nightly 51.0a1
- Tab Center v1.23

[Affected Platforms]:
- Windows 10

[Prerequisites]:
- Test Pilot add-on was already installed on a new profile.

[Steps to reproduce]:
1. Go to http://testpilot.dev.mozaws.net and choose the "Tab Center" experiment.
2. Click the "Enable" button on the experiment details page.
3. Press the F11 key on the keyboard to enter in Full screen mode.
4. Hover over Tab Center sidebar and observe the window buttons displayed on top right of it.

[Expected result]:
- Window buttons are correctly displayed on top right corner of the sidebar. 

[Actual result]:
- The window close button (x) is wrongly displayed under the minimize and restore ones.

[Notes]:
- The issue is only present on Windows 10 due to the different buttons style. Tested with Win 7, Win 8.1 and issue is not reproducible.
- When slowly hovering outside the sidebar, the search bar disappears and the window buttons are rearranged for ~1 second before bar is closed.
- Added a screen shoot and a screen recording with the issue https://goo.gl/JOR69s .

![window buttons messed](https://cloud.githubusercontent.com/assets/17258026/17554950/2c32f620-5f16-11e6-82ee-b9ff07eff042.png)

**Comment by ericawright** [comment]
Thank you for this and the steps to reproduce! I've been seeing this around and couldn't repro.

**Comment by ericawright** [comment]
reproducible in win 8 as well 
![screen shot 2016-08-24 at 3 24 09 pm](https://cloud.githubusercontent.com/assets/10803178/17950174/609a656c-6a0e-11e6-95c8-38e580ced575.png)

And Win 7
![screen shot 2016-08-24 at 3 27 37 pm](https://cloud.githubusercontent.com/assets/10803178/17950239/bf13582e-6a0e-11e6-8f47-20ad8810939f.png)

**Comment by SoftVision-PaulOiegas** [comment]
Cannot reproduce it anymore. Seems to be fixed... at least on Windows 10.
