### ISSUE TITLE
Thumbnails are no longer displayed for a tab that position was changed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [bwinton/TabCenter#511]
[Affected versions]:
- Nightly 51.0a1
- Tab Center v1.23

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Test Pilot add-on was already installed on a new profile.
- Tab Center experiment was already enabled.

[Steps to reproduce]:
1. Open a few websites in different tabs and observe their specific thumbnails.
2. Change the position in the list for one of the tabs with drag and drop. 
3. Observe the moved tab thumbnail.

[Expected result]:
- The tab changes his position in the list and the specific thumbnail is correctly displayed.

[Actual result]:
- The tab changes his position, but the specific thumbnail is no longer displayed.

[Notes]:
- A screen recording describing the issue was attached: https://goo.gl/s0HNYA.

**Comment by ericawright** [comment]
likely related to #475
