### ISSUE TITLE
Feedback:  Pinned tabs are same size as all other tabs

### ISSUE THREAD

**Issue by DouglasK** [bwinton/TabCenter#512]
In the horizontal tab layout, pinned tabs are narrower than standard tabs, giving a nice space saving in addition to them not scrolling when the rest of tabs scroll.
In the new vertical layout, they're the same height (about 3x the text height).  I believe we should cut the height by half at least and have it look good.

**Comment by mlissner** [comment]
Looks like a dup of #434.

**Comment by bwinton** [comment]
Yeah, it's a good idea, but we should track it there.  Thanks for the report and the dupe find!
