### ISSUE TITLE
Up and Down arrow keys to choose tabs from filtered results of SearchBox 

### ISSUE THREAD

**Issue by liljaylj** [bwinton/TabCenter#515]
Perfect workflow should be like this:
1. User hits shortcut to focus search box (mentioned in #514) -> Tab Center expands and SearchBox gets focus
2. User input search query to SearchBox -> Tab Center shows filtered out result
3. Then user selects (using `up` and/or `down` keys) preferred tab from list and hits `Enter` -> Browser switch to selected tab

**Comment by ericawright** [comment]
this is already possible by using 'ctrl-tab' and 'ctrl-shift-tab' to select which tab. Except the tab will change right away, no need to press enter.

**Comment by liljaylj** [comment]
I know that it is possible using `ctrl-tab` and `ctrl-shift-tab` hotkeys, but if you enable `browser.ctrlTab.previews` preference you have to use `ctrl-pgup` and `ctrl-pgdn` which is not very comfortable
