### ISSUE TITLE
Option to position tab center below url and bookmarks bars

### ISSUE THREAD

**Issue by dudelson** [bwinton/TabCenter#523]
Thank you for this addon! I'm coming from tree-style tabs, so I've been using vertical tabs for a while, but I'm excited to have this feature directly in firefox. The only thing that's a little bit bothersome to me right now is that tab center is to the _left_ of the url and bookmarks bars, whereas tree-style tabs is _below_ them. I prefer the tree-style tabs way, because it makes the vertical tab bar feel more integrated into firefox as opposed to feeling off to the side.

Current tab center look:
![tab_center_tabs](https://cloud.githubusercontent.com/assets/3400780/17643917/4f8e2bc6-6146-11e6-89e1-1d44942c3282.png)

Tree-style tabs look:
![tree_style_tabs](https://cloud.githubusercontent.com/assets/3400780/17643919/627865f8-6146-11e6-92fb-1b1d8b8836d2.png)

Would it be possible to add an option to enable the tree-style tabs look in tab center?

**Comment by bwinton** [comment]
We've played around with that before, but feel that it breaks the visual hierarchy of having the tabs control the urlbar, and so won't be adding that option to this add-on.  (Well, not for a while, anyways.  It is a fairly frequently requested feature, so it'll probably eventually make it in.)
