### ISSUE TITLE
Tabs Bar cause overlapping the URL toolbar and minimize/maximize buttons.

### ISSUE THREAD

**Issue by hossainalikram** [bwinton/TabCenter#525]
STR:

1. Open Firefox and Install Activity Stream
2. Go to about:config and set browser.tabs.drawInTitlebar to true. 

Actual Results:
The Toolbar besides awesome bar overlaps with the minimize, maximize buttons

Expected Results:
The Toolbar besides awesome bar should not overlaps with the minimize, maximize buttons.

![capture1](https://cloud.githubusercontent.com/assets/8605491/17644198/3d9a0eec-61a2-11e6-95f2-356866bcc2fd.png)

**Comment by hossainalikram** [comment]
Private browsing makes the issue more bad! It makes another small layer beside the button.

![capture2](https://cloud.githubusercontent.com/assets/8605491/17644205/7e7d8c40-61a2-11e6-8d9d-028841e55a9e.PNG)

I reproduced both issues with Latest Release and Nightly on Windows 7, 64 Bit.

**Comment by bwinton** [comment]
> 2\. Go to about:config and set browser.tabs.drawInTitlebar to true.

Yeah, don't do that.  It's not a supported modification.  Thanks for the report, though!
