### ISSUE TITLE
largetabs=0 doesn't quite work (I'm still seeing large tabs regularly)

### ISSUE THREAD

**Issue by mlissner** [bwinton/TabCenter#541]
I just got the upgrade to the new version (thank you, it looks great!), and I set the hidden setting, `largetabs` to `0`. It only sort of works. Most of the time, it seems to be collapsing my tabs down to the smaller size like I'd expect, but I think it's when I'm closing tabs, it still pops them up to the larger size, if only temporarily.

Not sure exactly what the cause is, but you'll run into it quickly if you set `largetabs` to `0`.

**Comment by kanakk** [comment]
I also saw this, and I also saw it mostly when closing tabs.  Restarting firefox  appears to have fixed the issue for me.

**Comment by Keith94** [comment]
Not reproducible for me with `largetabs=0`

**Comment by mlissner** [comment]
Testing again. Will try with a restart if it doesn't fix automatically.

**Comment by mlissner** [comment]
I can't reproduce it either anymore. Great!
