### ISSUE TITLE
Tab center crashed and put all tabs back on top

### ISSUE THREAD

**Issue by Mahendranadh** [bwinton/TabCenter#546]
Do not have clear STR. Tab center UI vanished and all the tabs showed up on the top. And the window turned gray. No content is displayed. Resizing window did not help. This happened on two windows with Private Browsing windows. Seemed to have happened when Tab Center was getting an update. Bad experience to lose all your tabs and a end up with a grey unresponsive window

<img width="1027" alt="tab center crash" src="https://cloud.githubusercontent.com/assets/17054715/17824474/0934a2f6-6617-11e6-82bd-aa5a6b04cf5d.png">
.

**Comment by bwinton** [comment]
I believe this is due to XUL caching and the add-on trying to update, which we are tracking in a different bug.  If you restart, everything should be fixed, so I'm going to close this as a dupe.

Thanks for the report!
