### ISSUE TITLE
Close a tab is like a two step process with mouse

### ISSUE THREAD

**Issue by Rj7** [bwinton/TabCenter#547]
I need to hover over the tab I want to close and then close button is visible. Then I miss the close button when I try to close since I moved my mouse more than necessary to the right. This becomes frustrating sometimes.

Suggestion: May be move the close button to the left side of the tab.

**Comment by bwinton** [comment]
Yes.  We found that if the close button was on the left then:

1. There would be no room for the thumbnail or favicon, and
1. people would accidentally close tabs when trying to switch to them.

As a workaround, you can pin the sidebar open, or use `ctrl-w`/`cmd-w` to close your tabs.  🙂
