### ISSUE TITLE
Scroll Buttons linger even after sufficient tabs are closed

### ISSUE THREAD

**Issue by kanakk** [bwinton/TabCenter#550]
Possibly related to the other issue where I have scroll buttons on multiple windows, even those with just 3-4 tabs: https://github.com/bwinton/TabCenter/issues/549

I'm on Firefox 48, using tab center 1.2.4, and have the largetabs set to 0.  

The scroll buttons remain, albeit in a disabled state, even after I've closed tabs and have just one tab in the window.

**Comment by ericawright** [comment]
this should be fixed with #597
