### ISSUE TITLE
Bring back the scroll bar in the tab list

### ISSUE THREAD

**Issue by roryokane** [bwinton/TabCenter#551]
Commit 396f290db98a100ee2e73ad052470dd0434aa142 “hide the scroll bar” in pull request #508 did what its name says – the scroll bar is no longer visible. I wish the scroll bar were back, because I found it useful.

I am guessing that disabling the scroll bar is an attempt to emulate the default horizontal Firefox tab interface, which also has arrow scroll buttons replacing the scroll bar. I think this is a reasonable decision for horizontal tabs, because a scroll bar would either hover over the tabs, covering the bottom half of every tab’s name, or it would take up valuable vertical screen space.

However, with vertical tabs, screen real estate is not quite so scarce. A scroll bar at the right side of the tab list (shown only when the list is expanded) only covers a few characters from the end of each tab name, instead of the bottom half of the whole name. And with OS X’s default auto-hiding scroll bars, these characters are only covered while actively scrolling (or when trying to reveal the scroll bar by resting two fingers on the trackpad).

The usefulness of the scroll bar is that it shows you the size of the tab list and your current position in it. I currently have about nine and a half window-heights of tabs in my list, so if I remember that a relevant tab was about halfway through the list, it is hard for me to judge when I have scrolled halfway without seeing my scroll position. And showing the size of the tab list is useful for distinguishing different windows that each have enough tabs to scroll but that have very different numbers of tabs, such as two of my windows’ 1.5 vs. 9.5 screenfuls of tabs.

If scroll bars were restored, the OS’s default scroll buttons could also replace the custom scroll buttons. But if you have some data that says inexperienced users find the custom buttons easier to use than their OS’s default scroll buttons, then maybe they’re worth leaving in. (I don’t use either type of scroll buttons; I just use my mouse wheel.)

**Comment by jamesderlin** [comment]
I agree completely.  I typically have a lot (hundreds) of tabs open, and having a scroll bar would allow me to scroll through my list of open tabs at the speed *I* want and lets me easily scroll to the beginning or end of the tab list.  Using the up/down arrow buttons forces me to scroll at a fixed rate they were configured for, and that does not scale.  While it makes sense to not have a horizontal scroll bar for a horizontal tab strip, I don't see why it was removed for a vertical list.  Even though the tab list isn't a true sidebar, removing the vertical scroll bar makes it gratuitously inconsistent with sidebars such as the Bookmarks list and History list.
