### ISSUE TITLE
Bookmarks toolbar is unusable

### ISSUE THREAD

**Issue by Eli112358** [bwinton/TabCenter#552]
When right clicking on anything in the bookmarks toolbar, only "Open all in tabs" is not greyed out.
Bookmarks sidebar is unaffected.
I've disabled all other add-ons and hardware acceleration, so those are ruled out.

**Comment by cpeterso** [comment]
I just noticed this bug today. It think it is a regression in the recent release of Tab Center version 1.24.0.

**Comment by Keith94** [comment]
#490

**Comment by Eli112358** [comment]
Yes, #490 is the same bug; my issue search wasn't thorough enough.
And I forgot some additional info: I'm using Windows 10.

**Comment by JohnBrewer** [comment]
Same problem. Windows 10 Firefox 47.0.1

**Comment by gillefc** [comment]
Didn't have this issue until the most recent version (48.0.1) this morning (22 Aug 16) on Windows 10 and Windows 7.

**Comment by JohnBrewer** [comment]
Updated to 48.0.1 still have issue. Removed Test Pilot "Tab Center" and it went away.

**Comment by ericawright** [comment]
duping this in favor of #490.
