### ISSUE TITLE
Control-Shift-K to focus tab search conflicts with DevTools

### ISSUE THREAD

**Issue by callahad** [bwinton/TabCenter#553]
When I press <kbd>Ctrl-Shift-K</kbd> I expect the DevTools' JavaScript Console to appear.

Instead, the TabCenter sidebar slides in and focuses its search box.

Impact: this breaks my ability to summon or switch between Firefox's DevTools using the keyboard.

**Comment by callahad** [comment]
This seems to have regressed. Please reopen.

**Comment by ericawright** [comment]
this has not been released yet. Did you try it using the code from master on Github?

**Comment by callahad** [comment]
Huh, I could've sworn it was working properly an hour ago, and now isn't. Maybe I'm imagining things.

I've also been switching between profiles with an without Tab Center, so I must be misremembering. :/ sorry for the noise.

**Comment by ericawright** [comment]
@callahad not a problem :)

**Comment by nbriz** [comment]
i'm still having this issue ( Firefox release 48.0 ), is this because I installed the addon from the experiments page ( rather than downloading the latest version here )

**Comment by ericawright** [comment]
@nbriz yes, it will be officially released soon
