### ISSUE TITLE
Enabling Tab center disables File Menu functions in drop box.

### ISSUE THREAD

**Issue by JohnBrewer** [bwinton/TabCenter#555]
Windows 10, Firefox 47.0.1 Enabling tabs removes all functionality of file menu functions found in right click, i.e. when place cursor on bookmark and right click the File Menu opens, offering Open, Open in a New Tab, etc. but nothing below Open functions at all.

**Comment by Keith94** [comment]
#490

**Comment by JohnBrewer** [comment]
Apparently this is a duplicate og a previously opened issue. #490.

**Comment by JohnBrewer** [comment]
Closed as duplicate of #490.
