### ISSUE TITLE
Hide pin icons when tabs are minimized

### ISSUE THREAD

**Issue by johngruen** [bwinton/TabCenter#557]
### Expected

Pin icons don't interfere with favicons

### Actual
![screen shot 2016-08-22 at 9 37 10 am](https://cloud.githubusercontent.com/assets/3323249/17857023/34e221f6-684e-11e6-823d-99466a155329.png)

**Comment by johngruen** [comment]
![screen shot 2016-08-22 at 9 55 07 am](https://cloud.githubusercontent.com/assets/3323249/17857111/89a94552-684e-11e6-8881-a93e0215c24d.png)

**Comment by shorlander** [comment]
Yeah... I did a kind of hacky thing there using background-image. Maybe should add a separate element for the pin indicator?

**Comment by bwinton** [comment]
@shorlander Could you take this one?
