### ISSUE TITLE
Minimizing tabs is jittery in new UI

### ISSUE THREAD

**Issue by johngruen** [bwinton/TabCenter#558]
![minimize jitter](https://cloud.githubusercontent.com/assets/3323249/17857185/bfa073ba-684e-11e6-926a-dc9a95b64d36.gif)

**Comment by johngruen** [comment]
Status update: a ghost just temporarily maximized my minimized tabs 
👻

**Comment by ericawright** [comment]
I can't duplicate this, but my theory is that it might be from #497 if it is detecting the mouse within the TC area

**Comment by ericawright** [comment]
@johngruen still unable to duplicate this on OSX and Win 10. Does this still happen to you? Or do you have any more info on how to duplicate?

**Comment by ericawright** [comment]
removing this from shield-ready as I'm unable to duplicate
