### ISSUE TITLE
Pinned tab title changed icon looks weird/misaligned

### ISSUE THREAD

**Issue by eoger** [bwinton/TabCenter#560]
<img width="231" alt="screen shot 2016-08-22 at 12 56 55 pm" src="https://cloud.githubusercontent.com/assets/6424575/17869538/a59b45d4-6868-11e6-9fbf-708f7fe89e8c.png">

This is on OSX

**Comment by Manishearth** [comment]
(can confirm this)

**Comment by bwinton** [comment]
Looks fine to me (and more importantly to @shorlander, who designed the theme)…
If you can mark up your screenshot to more clearly demonstrate the problem, I'll be happy to take a second look, but until then, I think I'm going to mark this closed.

Thanks for the report!

**Comment by Manishearth** [comment]
I think the issue is that it looks very similar to the loading spinny, except it's shunted to the side.

**Comment by eoger** [comment]
So you're saying that this is intended?
