### ISSUE TITLE
Selecting a tab with keyboard shortcuts should scroll to it correctly

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#563]
**Steps to reproduce**

1. Pin the tab sidebar open
2. Open many new tabs so the tab list overflows
3. Press Ctrl+1 to select the first tab
4. Then press Ctrl+9 to select the last tab, and toggle back and forth

**Actual behavior**
The tab gets selected via shortcut but is not immediately visible in the tab list

**Expected behavior**
The tab bar should scroll correctly so the selected tab is visible

**Comment by ericawright** [comment]
duping to #492
