### ISSUE TITLE
Title of first tab becomes "New Tab"

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#564]
**Steps to reproduce**

1. Install Tab Center (I use Nightly on Windows)
2. Open Add-ons Manager
3. Disable Tab Center

**Actual behavior**
The first tab's label gets changed to "New Tab", which also persists after Tab Center is re-enabled

**Expected behavior**
The label should remain unchanged by the add-on

**Comment by xbouroseu** [comment]
I can confirm that this happens to me too.

**Comment by thomaslevesque** [comment]
Me too
