### ISSUE TITLE
Sidebar should collapse when focus is moved away from it

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#565]
**Steps to reproduce**

1. Have the Tab Center sidebar in 'unpinned' state
2. Press the shortcut (Ctrl+Shift+K) to focus the tab search bar
3. Click somewhere else on the browser such as the website content

**Actual behavior**
Sidebar remains in 'expanded' state, covering up the site content

**Expected behavior**
Sidebar should return to 'collapsed' state when focus is moved away

**Comment by bwinton** [comment]
The shortcut only focuses the tab search bar as a side effect.  It's actually the "Toggle Tab Sidebar Open/Closed" shortcut, so to collapse it, you'll need to press the shortcut again.

Resolved, as designed.

(Where did you see that it was a shortcut to focus the search bar, cause we really need to get in front of that messaging, as they say…  Thanks!)
