### ISSUE TITLE
After recent update new tabs open at the top

### ISSUE THREAD

**Issue by devanes** [bwinton/TabCenter#567]
Previously there was an issue where new tabs (Ctrl-T) opened not below the current tab below the next one (one too low). This doesn't happen anymore. Now all new tabs open at the top.

Which is (for me) a nuisance. I always have a few specific tabs at the top, which I want to keep there. I don't want to have to drag all new tabs down first. In my view, the logical place for a new tab to open is below the currently selected one.

**Comment by ericawright** [comment]
If you go to "about:addons" and preferences you can change the preference of where your "new tabs" are opened (top or bottom). As for the tabs opened by ctrl-clicking a link we are tracking that issue in #410 and it is being worked on.

**Comment by devanes** [comment]
Ah great. I hadn't noticed there were settings (ok a setting) available now. After unchecking this it works right. The tabs opening one tab to low is gone as well.

Good work so far!
