### ISSUE TITLE
Search filtering is lost when unpinned sidebar is unfocused 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#571]
[Affected versions]:
- Nightly 51.0a1
- Tab Center v1.24.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Tab Center add-on version (v1.24.0) was installed on a new clean profile.
- Tab center Sidebar is kept unpinned.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Open several pages in new tabs.
3. Hover the Sidebar and filter the tabs by searching the name of one of the opened pages.
4. Hover away from Sidebar and observe the behavior.

[Expected result]:
- Applied filtering is kept even if Sidebar is unfocused.

[Actual result]:
- Applied filtering is cleared when Sidebar is unfocused.

[Notes]:
- This issue is not reproducible when Sidebar is pinned so I assume it should work also when not pinned.
- In my opinion this could affect the user experience if the user likes to have the sidebar unpinned, has lots of tabs opened, and the applied filtering displays more results. In order to view each result separately he will have to filter multiple times to view them all.  We should let the user to cancel the filtering when not needed anymore.
- Added a screen recording with the issue http://goo.gl/Q1AI0y .

**Comment by dannyhajj** [comment]
I want to point out a different behavior when using the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>.
When using the shortcut to toggle the visibility of the sidebar and focus on the search box the filter does not get reset.
However there is an erroneous behavior that occurs, similar to the reported issue.

## Steps to reproduce:
- Have the bar set to collapse when not in focus
- Use the kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> keyboard shortcut
- Type in a search filter
- Hover with your mouse over the sidebar than move the mouse out

## Result
- The filter is reset
- The search box is emptied
- The sidebar stays visible

## Excepted result
- I think nothing should happen as long as the search box is still in focus.

**Comment by ericawright** [comment]
@dannyhajj great catch, I'm going to open the above comment into it's own bug

**Comment by ericawright** [comment]
closing. as-designed
