### ISSUE TITLE
Pasting a string in sidebar search field when not pinned is impossible

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#572]
[Affected versions]:
- Nightly 51.0a1
- Tab Center v1.24.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Tab Center add-on version (v1.24.0) was installed on a new clean profile.
- Tab center Sidebar is kept unpinned.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Copy a string from anywhere.
3. Hover the Sidebar and right click in the search field.
4. Choose to paste the copied string.

[Expected result]:
- Copied string is correctly pasted in the search box and the filtering is performed.

[Actual result]:
- Copied string is not pasted in the search box.

[Notes]:
- This issue is not reproducible when Sidebar is pinned so I assume it should work also when not pinned.
- Added a screen recording with the issue http://goo.gl/a59Gu5 .

**Comment by SoftVision-PaulOiegas** [comment]
Good fix, this is no longer reproducible.

**Comment by SoftVision-PaulOiegas** [comment]
After a more thorough testing, discovered that this works on Windows, but not also on Mac OS and Ubuntu. We should reopen this to properly fix it.
Screen recording for Mac OS - http://goo.gl/suc55Y

**Comment by ericawright** [comment]
@SoftVision-PaulOiegas this should be fixed with #578 which was just merged yesterday

**Comment by SoftVision-PaulOiegas** [comment]
Well, I did a new build from the repo today so I'm not very sure. I thought it's fixed to but when I've tested on other OSes, not really...

However, do we need to setup anything else or it's enough just to clone the repo and build the xpi to have the latest changes ?

**Comment by ericawright** [comment]
Yes, you just clone the repo, build the xpi, then use the xpi to install it. 

You are correct though, this is still a problem. Though only with the search context menu, it sems to be behaving differently than the other context menus. semi-related to #612

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed now also on Mac OS and Linux. The only thing I noticed on Ubuntu is that the search icon is completely removed from text box when pasting long strings.
