### ISSUE TITLE
Long search strings are displayed outside the search textbox designed area

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#573]
[Affected versions]:
- Nightly 51.0a1
- Tab Center v1.24.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Tab Center add-on version (v1.24.0) was installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Hover the Sidebar if not pinned, click the search field.
3. Enter a long string and observe how it is displayed in search box.

[Expected result]:
- Entered long string is correctly contained in the search box and scrolled when number of characters exceeds the box length. 

[Actual result]:
- Entered long string exceeds the box designed area.

[Notes]:
- This issue occurs no matter how long are the words entered and even if a space is entered after each character.

![long search string](https://cloud.githubusercontent.com/assets/17258026/17929895/2d3d9402-6a0c-11e6-87ed-7304ec316a07.png)

**Comment by johngruen** [comment]
hide that overflow!
