### ISSUE TITLE
Crashed tab at startup, could not restore tabs

### ISSUE THREAD

**Issue by kumar303** [bwinton/TabCenter#582]
After using TabCenter successfully for quite some time, I started up Firefox today and saw a single vertical tab saying 'this tab has crashed'. When I clicked 'restore', nothing happened. I could create new tabs just fine and they were in my vertical menu as expected. Unlike when the built-in tabs crash, I had no way to restore all my previously open tabs. This is a bummer because I had many tabs open that I wanted to preserve.

I'm not sure exactly what information would be helpful to diagnose this. Let me know if you have questions.
- Tab Center: 1.24.0
- Firefox Dev Edition: 50.0a2 (but the crashed version was probably older)
- Mac OS X: 10.10.5

**Comment by bwinton** [comment]
Your tabs should still be saved in `~/Library/Application\ Support/Firefox/Profiles/<random string>.<profile name>/sessionstore-backups/` so at least all is not lost, but yes, I agree that's not ideal!

Is/Was there anything suspicious-looking in the Browser Console (from `cmd-shift-j`)?

**Comment by kumar303** [comment]
d'oh. I forgot to look in Browser Console. I was on PTO last week so I think it's long gone now -- just catching up on github issues. The UI of the extension looked different after I recovered from the crash so maybe an update had triggered it.
