### ISSUE TITLE
Right click menu not working

### ISSUE THREAD

**Issue by Cowpatz** [bwinton/TabCenter#583]
Right clicking on a tool bar books mark to select "pen in a new tab" not working. In fact all of the right click menu is not working for firefox tabs since installing this. Menu appears greyed out.
Using Win 7 64 bit.

![tab centre](https://cloud.githubusercontent.com/assets/21250341/17987584/c131c66a-6b74-11e6-994a-948d060531bb.jpg)

**Comment by tomerof** [comment]
i have the same problem... windows 10 pro

**Comment by SoftVision-PaulOiegas** [comment]
I can confirm this on my end too. here are the exact steps to reproduce:
1. Start Firefox with a new clean profile.

**Comment by ericawright** [comment]
Interesting, this seems to only be reproducible when installed through test pilot, not by using a custom xpi.

**Comment by Keith94** [comment]
Related: #490

**Comment by fredfred41** [comment]
exact same problem here..

ericawright, how do you install a custom xpi?

**Comment by ericawright** [comment]
@fredfred41 if you'd like to take a look at the work on here before we release it you can by building your own XPI. Steps:
- you must be using nightly.
- go to `about:config` in the awesome bar
- set `xpinstall.signatures.required` to false
- After cloning this repository, in the terminal, run `npm install` and `npm install jpm` then:
- `jpm xpi` to generate an installable XPI file locally
- once you have the XPI file, you can drag and drop it onto nightly to install.

**Comment by jasondrew** [comment]
Exact same problem for me too, Firefox 49.0.1 on Windows 10. The context menu (right-click menu) on items in the bookmarks toolbar is grayed out: all the expected options appear, but are disabled. If I access the same items through the main Bookmarks menu, they work OK. It's pretty annoying.

**Comment by LarnuUK** [comment]
Still ongoing, Windows 7 Professional SP1, Firefox 49.0.1.

**Comment by ericawright** [comment]
thanks to @brennie for pointing out this is possibly related to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=625778

**Comment by kkot** [comment]
@ericawright 
Shouldn't it have some higher prio ? For me it makes using this extension very difficult because I often add bookmarks and now I cannot rename them easily.

**Comment by ericawright** [comment]
@kkot I would say this is probably one of the highest priority bugs we have at the moment. It is simply difficult to fix 😄

**Comment by fredfred41** [comment]
Thanks ericawright, but I dont know how to do what you writed : 

After cloning this repository, in the terminal, run npm install and npm install jpm then:
jpm xpi to generate an installable XPI file locally
once you have the XPI file, you can drag and drop it onto nightly to install.

**Comment by ericawright** [comment]
@fredfred41 to make it easier for you you can find the xpi file here:
https://www.dropbox.com/s/ne5i2wu62a0j4hn/tabcentertest1%40mozilla.com-1.26.0.xpi?dl=0
That contains the most current code as of today. If you open the file with Nightly or Dev Edition it will work (it will not work with regular Firefox).

We should be releasing a new version soon though, and if you start using the custom xpi you will not get future updates.

**Comment by fredfred41** [comment]
@ericawright thanks, I will try it, would you please tell us when the new version would be available please. Si when it will, I could manually uninstall the custom xpi.

Off topic, I tried "repair" fonction and I lost all my opened tabs (not synchronisés with Sync of course...) Do you have a way to retrieve them?
Thanks

**Comment by bwinton** [comment]
@fredfred41 Check out [Mozilla Support](https://support.mozilla.org/en-US/questions/1027904) for answers to questions like that…

**Comment by treba123** [comment]
I also have this issue on to distinctive (not connected) installations, both Firefox 50.1.0, Fedora 25 (up-to-date)

**Comment by SoftVision-PaulOiegas** [comment]
>  ericawright commented on Sep 6, 2016
Interesting, this seems to only be reproducible when installed through test pilot, not by using a custom xpi.

@ericawright This issue is bugging me also a lot, so I've put some time in it to figure out the exact behavior. It seams that there has nothing to do with Test Pilot install since I've managed to reproduce it with a custom build made today from the repo. Instead it seams to be directly related to the bookmarks toolbar and Tab Center. See the "Notes" section in my scenario for additional details.
Here is the scenario to reproduce this:

[Prerequisites]:
- Build a custom xpi of the Tab Center repository.
-  Set "xpinstall.signatures.required" pref to "false" on a new profile, in order to be able to install the unsigned xpi.

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites.
2. Right click the area under the awesomebar and choose to enable "Bookmarks Toolbar".
3. Drag the xpi into the browser and install it.
4. Right click the default bookmarks from the toolbar and observe the options from context menu.

[Expected results]:
All options are available and can be selected for the bookmark.

[Actual results]:
All options are grayed out and unusable.

[Notes]:
- The fun part with this issue is that if the "Bookmarks Toolbar" is closed while installing the custom xpi, the context menu works as intended after enabling the toolbar. But this breaks after the browser is restarted.
- Also, if you disable the toolbar, restart the browser and re-enable it, the context menu works again until browser restart.

**Comment by arai-a** [comment]
looks like rearranging XUL elements results in releasing `this._viewElt.controllers`, that had a controller for Places:

https://dxr.mozilla.org/mozilla-central/rev/698de2db1b16a5ef3c6a39f0f72885e69aee4022/browser/components/places/content/browserPlacesViews.js#17
>  this._viewElt.controllers.appendController(this._controller);

maybe released here:
https://dxr.mozilla.org/mozilla-central/rev/698de2db1b16a5ef3c6a39f0f72885e69aee4022/dom/xul/nsXULElement.cpp#880
>         NS_IF_RELEASE(slots->mControllers);
or here:
https://dxr.mozilla.org/mozilla-central/rev/698de2db1b16a5ef3c6a39f0f72885e69aee4022/dom/base/FragmentOrElement.cpp#635
>     NS_IF_RELEASE(mControllers);
or somewhere similar to that.


and controllers is regenerated after that, when gets accessed:

https://dxr.mozilla.org/mozilla-central/rev/698de2db1b16a5ef3c6a39f0f72885e69aee4022/dom/xul/nsXULElement.cpp#1454-1455
>        rv = NS_NewXULControllers(nullptr, NS_GET_IID(nsIControllers),
>                                  reinterpret_cast<void**>(&slots->mControllers));


and regenerated controllers doesn't have the controller appended before, and returns `null` here:

https://dxr.mozilla.org/mozilla-central/rev/698de2db1b16a5ef3c6a39f0f72885e69aee4022/browser/components/places/content/controller.js#1721
>      return view.controllers.getControllerForCommand(aCommand);


so `placesController` below becomes `null` and all places commands are set to disabled:

https://dxr.mozilla.org/mozilla-central/rev/698de2db1b16a5ef3c6a39f0f72885e69aee4022/browser/components/places/content/controller.js#1685-1688
>  var placesController = doGetPlacesControllerForCommand("placesCmd_open");
>  function updatePlacesCommand(aCommand) {
>    goSetCommandEnabled(aCommand, placesController &&
>                                  placesController.isCommandEnabled(aCommand));


the controller is released at this line in `rearrangeXUL` in verticaltabs.js:
https://github.com/bwinton/TabCenter/blob/48f4b66f67762210023ca1e937d1f6e7f27e206f/verticaltabs.js#L603
>     contentbox.insertBefore(top, contentbox.firstChild);

**Comment by arai-a** [comment]
forgot to mention that `top` there is `#navigator-toolbox` and it contains `#PlacesToolbar` that is `this._viewElt.` above.

**Comment by Inoki** [comment]
Still present in 51.0.1 (32-bit).

**Comment by petsuter** [comment]
🎉 When can I get this fix in test pilot?

**Comment by ericawright** [comment]
We'll try to get it out ASAP

**Comment by SoftVision-PaulOiegas** [comment]
Me and @SoftVision-CiprianMuresan tested the build with the fix for a few days now and we can confirm that seems to be a good fix. Life saver ! 👍
