### ISSUE TITLE
closed a tab and now I can't change tabs

### ISSUE THREAD

**Issue by db48x** [bwinton/TabCenter#585]
Clicking on a tab in the list throws a "TypeError: tabs.selectedItem is null  verticaltabs.js:178:7" error in the browser console. Keyboard shortcuts for changing tabs don't work either. Opening a new tab works, but then I can't change to it. Closing tabs no longer works either. I can drag the tabs to a new window and everything works in that new window; it's just the state in this window that's broken somehow.

The tab center in other windows still work fine, however.

**Comment by ericawright** [comment]
I believe this had something to do with the update, and restarting would have fixed the issue - sorry we didn't get back to you.
