### ISSUE TITLE
inapropriate place for buttons

### ISSUE THREAD

**Issue by isingasimplesong** [bwinton/TabCenter#591]
Debian testing
Firefox ESR 45.3

When using TabCenter with full screen Gnome 3 integration, reduce, close and maximize buttons are in inapropriate place. (see screen shot)
![capture d ecran de 2016-08-26 20-37-12](https://cloud.githubusercontent.com/assets/896898/18023879/4da06b6c-6bcd-11e6-8115-6dd77f7f59f2.png)

**Comment by CharoSW** [comment]
If you've got the extension Htitle then that would be the cause of this, just disable it to fix

**Comment by ericawright** [comment]
this has been fixed and will be seen in the next release, see #509 and #595

**Comment by ericawright** [comment]
this has been fixed and will be seen in the next release, see #509 and #595
