### ISSUE TITLE
first touch in a touch screen should not switch to the touched tab

### ISSUE THREAD

**Issue by ajagmx** [bwinton/TabCenter#592]
using surface pro 4, if I have a full tab center (no empty space) and i touch (finger, not pen) to expand it, it switches to whichever tab I touched, which is, 99% of the time, not what I intended. A first touch should work like a pen mouse-over, expand the center but not switch tabs.

**Comment by ericawright** [comment]
Thanks! This issue is being addressed with #611, and tracked with #200.
