### ISSUE TITLE
should have a setting option to push the viewing pane to the right, not just overlay it

### ISSUE THREAD

**Issue by ajagmx** [bwinton/TabCenter#593]
if I open ten pages and want to quickly scan down them all by clicking down the list in the center (this is a very nice thing to be able to do, and much easier than using the tab bar), it would be better if the expanded tab center didn't overlay the left side of each page. so an option (in settings probably, because not everyone will want this) to push the current web page to the right when the center is expanded would be good.

**Comment by ericawright** [comment]
@ajagmx if you keep TC expanded using this button:
<img width="44" alt="screen shot 2016-09-06 at 3 56 13 pm" src="https://cloud.githubusercontent.com/assets/10803178/18293901/6e1278a6-744a-11e6-8b25-af1b818154ac.png">
then it will push the current page to the right rather than overlap it.
