### ISSUE TITLE
wrong tab is scrolled into view when selecting a tab

### ISSUE THREAD

**Issue by db48x** [bwinton/TabCenter#598]
Sometimes when I click on a tab to view it, the tab list jumps and the selected tab is not visible in the list. At first I wasn't able to see what was going on, but now I see that it's scrolling the previously-selected tab into view in the tab list rather than the currently selected tab. That is, if you have tabs 1 through 100 open, and tab 100 is selected, then when you scroll back to the beginning of the list and select tab 1 it will scroll tab 100 back into view. The same problem is visible in other circumstances when changing tabs, but it's usually less obvious.

**Comment by fredfred41** [comment]
Exacly the same behaviour for me, please do something about it, mozilla, it s really annoying.

**Comment by ericawright** [comment]
This will be fixed with next release. Was tracked through #492, and fixed with #575.
