### ISSUE TITLE
Bring back "Restore Previous Session" button on the new page on the tab center.

### ISSUE THREAD

**Issue by MrJustMe** [bwinton/TabCenter#606]
A link with the same funcionality could be a good replacement if you do no want to bring back the restore button.
I mean this button:
http://i.imgur.com/3qFOh4M.png
In this page:
resource://activity-streams/data/content/activity-streams.html#/

Thanks for reading.

**Comment by ericawright** [comment]
Thanks, this is regarding Activity Stream, a different Test Pilot add on. I've opened another issue there for you: https://github.com/mozilla/activity-stream/issues/1229.
