### ISSUE TITLE
Search box context menu is closed when hovering away from text box

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [bwinton/TabCenter#612]
[Affected versions]:
- Nightly 51.0a1
- Tab Center v1.24.0 ( build date 09.07.2016)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Tab Center add-on version (v1.24.0) was installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Hover the Sidebar and right click in the search field.
3. Observe the context menu behavior while hovering away from search text box (any direction).

[Expected result]:
- The context menu is kept open.

[Actual result]:
- The context menu is closed when hovering out the search box.

[Notes]:
- When pasting a long text in the search box, hovering out or in the text box also resets the view from the end, to the beginning of the entered text.
- This issue is reproducible even when Sidebar is pinned.
- Not reproducible on Mac OS or Linux.
- Added a screen recording with the issue http://goo.gl/pksCEu .

**Comment by SoftVision-CiprianMuresan** [comment]
There's also a nasty side effect to this issue. The sidebar remains opened until a different browser context menu is opened and closed. See http://goo.gl/gTrkbu.

**Comment by ericawright** [comment]
for reference:
This can be seen on Mac as well. If you open up the browser debugging tools and click on this button
<img width="33" alt="screen shot 2016-09-09 at 2 58 24 pm" src="https://cloud.githubusercontent.com/assets/10803178/18404180/cf006038-769d-11e6-9328-cf08e0de9003.png">
This should keep popup menus open until `esc` is clicked (and does with all other menus). However if you click outside of the search box or, search box context menu it will close. Also causes ^^ "nasty side effect"
