### ISSUE TITLE
Pinned tabs shouldn't require right-click to close, should have hover close button

### ISSUE THREAD

**Issue by hafta** [bwinton/TabCenter#615]
It would be more natural if pinned tabs could be closed in the same way as regular tabs. i.e., if the close 'X' button appeared on hover over a pinned tab.

**Comment by bwinton** [comment]
That's contrary to the idea behind pinned tabs, as tabs that are always there for you, so I think we're not going to do this.  (If you want to be able to close them, then why bother pinning them?)

Thanks for the idea, though!  🙂

**Comment by hafta** [comment]
Sure. Thanks for looking into it. It is rare that I close a pinned tab. I get that requiring a right-click for pinned tabs has value because then you're less likely to close a pinned tab by accident when you really just wanted to select the tab, but the inconsistency nagged me a bit.
