### ISSUE TITLE
Tab list jumps to wrong position when selecting tab

### ISSUE THREAD

**Issue by paulkoan** [bwinton/TabCenter#619]
To reproduce:

1) Open a lot of tabs such that you need to scroll to get to the bottom
2) Choose the bottom tab
3) Scroll up such that the currently selected tab is off screen
4) Click a visible tab

Expected behavior:

The tab under the mouse cursor is the one you just clicked

Actual behavior:

The tab under the cursor is some other tab, and the one you clicked is.. well somewhere else.  Sometimes at the top of the visible tabs, often off the top of the tab list, out of sight.

The problem:

Aside from losing your sense of where you are in the tab list, there is a "close the wrong tab" issue.  If you see a tab that is a candidate for closure, you click the tab to check, then middle click to close.  Except you are closing a completely different tab.

Solution:

Do not move the tab list when a tab is selected.

Version: 1.24.0
FF: Windows 48.0.2

**Comment by ericawright** [comment]
Is this with the version that is currently released or built with the current code on master? I ask because there have been some changes in the past week that might affect this behavior (either fixing or causing it 😄  ) which have not been officially released yet.

**Comment by paulkoan** [comment]
The version is at the bottom of the post, 1.24 - so this is the release.  I couldn't see a related issue that might be addressing this in master.

**Comment by ericawright** [comment]
Okay. It's possible that #610, #589, or likely #575 may have fixed this issue. But I'll double check.

**Comment by ericawright** [comment]
Tested on windows 10 and OSX, this has been fixed. Will be in the next release.
