### ISSUE TITLE
Shortcust conflicting with developer tools

### ISSUE THREAD

**Issue by anshulguleria** [bwinton/TabCenter#622]
- Operating system: `linux 16.04`
- Firefox build: `developer edition`

The shortcut `Ctrl + Shift + K` focusses the search for tabs in tab center but the same shortcut is used by mozilla developer tools for opening console tab in developer tools thus I am not able to open/focus the `console` tab in develolper tools.

**Comment by ericawright** [comment]
Thanks, this has been fixed by #559 and will be available with the next release.
