### ISSUE TITLE
Error when open with private window

### ISSUE THREAD

**Issue by ricsdeol** [bwinton/TabCenter#623]
**scenario**: The error occurs when there is no instance of open firefox and open firefox only in private mode

**Firefox Version**: Mozilla Firefox 50.0a2
**SO**: Ubuntu 16.04 64

Prints:
![selection_001](https://cloud.githubusercontent.com/assets/719970/18492666/d9083108-79e2-11e6-8e14-f39976fceb51.png)

When I mouse click in the window:
![screenshot from 2016-09-13 18-47-45](https://cloud.githubusercontent.com/assets/719970/18492667/d909a6be-79e2-11e6-8af1-e60edfe89f2c.png)

**Comment by ericawright** [comment]
linking to #675
