### ISSUE TITLE
Causes other extensions (Diigo toolbar) to hide buttons?

### ISSUE THREAD

**Issue by Jaykul** [bwinton/TabCenter#624]
I don't know who's fault this one is, so I [cross posted it here](https://groups.diigo.com/group/Diigo_HQ/content/bar-has-no-buttons-in-firefox-with-tab-center-15380795), but the [Diigo toolbar](https://addons.mozilla.org/en-US/firefox/addon/diigo-web-highlighter-and-stic/reviews/?src=api) has no buttons when I restart my browser after turning on Tab Center. 

I can turn off Tab Center, restart, and the buttons come back, then I can turn Tab Center back on.

**Comment by ericawright** [comment]
Thanks! (I assume it is likely our fault) We aren't currently focusing on compatibility with other addons, so, for now I will link it to this list #464 so it is recorded for when we have the time.
