### ISSUE TITLE
Tab Center steals devtools' CTRL+SHIFT+K keyboard shortcut

### ISSUE THREAD

**Issue by cpeterso** [bwinton/TabCenter#628]
STR:
1. Press CTRL+SHIFT+K keyboard shortcut to open the devtools console. (It doesn't matter if the devtools are already open or not.)

RESULT:
The devtools console never opens because Tab Center's tab search box steals input focus.

**Comment by bwinton** [comment]
Thanks, this was reported in #553 and will be fixed with the next release.
(Also, is it just me, or is GitHub's issue search surprisingly flaky…  🙂)
