### ISSUE TITLE
Website preview lies! WTF?

### ISSUE THREAD

**Issue by Red-Squid** [bwinton/TabCenter#629]
[The original author decided to be abusive and insulting, so their comment was deleted.]

**Comment by bwinton** [comment]
Your tone is inappropriate for this project.  Please refrain from commmenting until you can do so in a respectful, professional manner.

**Comment by Red-Squid** [comment]
BTW, bwinton, I'm not a professional, I'm a real world user! Real world users often express themselves in terms that they know any 8th grader could understand. That does not make their experiences, opinions any less valuable than those of a professional. Nor does it make them any less valid or valuable than a professional.

Perhaps in the future you should just edit the content to remove, or alter, the less desirable aspects, rather than being abusive yourself, and simply disregarding the matter because it's presentation displeases you.

I know, had mistakenly assumed we were all adults, I sincerely apologize; lesson learned.

**Comment by bwinton** [comment]
"Real world users" can still be polite and respectful.  If that is beyond your capabilities, then perhaps we aren't all adults here.

**Comment by Red-Squid** [comment]
If it not polite to ask questions that one would like the answer to?

**Comment by bwinton** [comment]
It's not polite to suggest that the people who are working on this thing (which they have provided to you for free!) are "high on crack" or that their hard work "looks like utter crap".

**Comment by Red-Squid** [comment]
You read that as a 'suggestion'... that's interesting. The '?' clearly denotes a question.

And whether or not something looks pleasing or unpleasing is subjective and valid regardless of a differing of opinion by the creator (or anyone else). Reacting as though such an opinion does not have value because you do not agree is outright and blatantly inappropriate.

You may have only developed this tool to your liking, but it is publicly accessible, and other people have developed, and will continue to express, their own opinions regarding it's appearance and usefulness. Nobody is required to refrain from expressing those opinions because they gained access to the tool for free. Nobody is required to be grateful! Nor are you required to like the opinions of others, nor what words are used to express them, but you absolutely should not act to outright silence them. If addressed properly, and in a mature fashion, they can instead be used to your benefit.

If you don't like the word crap, for example, replace it with something comparable. Perhaps use a thesaurus (words related: illogical, irrational, senseless, incongruous [unbecoming]). 

This is an interesting subject matter in and of itself. Would you have chosen to take offense had another word been used to suit the same purpose? I mean, people who don't know you also don't what level of mastery you poses over the English language (how big is your lexicon?). Why would you assume that any stranger who is talking to you would use anything but the most simple and clearest terms they know (the popular lowest common denominator)?

If someone asks you if you are on drugs, perhaps it's worth considering why they are asking? Perhaps it's worth actually listening to them and determining what has led them to consider such a thing possible? Perhaps it's worth noting that perhaps other people will ask the same, or a similar, question when they encounter the same things? Perhaps other people just won't be so forward as to make you aware of the fact that those questions are being asked? Isn't it better to know?

~ I always though knowledge was rather empowering, personally.

Hey, I'm curious: If a cop were to pull you over, and start their interaction with you by asking you if you'd been drinking, would you become irate and dismissive? 

Perhaps, if the only criticism anyone ever offered each other was a pat on the back and a cookie, nobody would ever realize that what they were doing wasn't all rainbows and unicorn for other people?

To be really clear here, emotionally intelligent adults generally respond to questions by answering, or opting not to answer, rather than by imposing more meaning on the question asked, and then choosing to take offense to that imposed meaning, and then reacting to that now self-imposed offense by dramatically overreacting... for example, excluding the asking party from further participation, or otherwise limiting their speech.

Emotionally Intelligent people also don't take offense to the personal opinions of others, or words in and of themselves, but instead consider their honesty, meaning, and usefulness during future actions. As far as programming is considered: If 90% of users don't like a newly added feature of an app, perhaps that feature should only be an 'option'? On the other hand, if only 5% of users find a new always on feature undesirable, perhaps it's not worth the effort/energy to redesign the app?

~ Why not cut out the middle man and make all features optional?

Tell me, what do you think is more true. Did I come here to upset you, or did I come here to express an unfavorable opinion I formed while testing your add-on, and also to provide possible methods for you to utilize in order to ensure others don't form the same opinion. Tell me, seriously, was my comment just those few words that you quoted, and chose to take offense to, or was my comment 98% other things?

I know what an adult is BTW, I'm a college educated middle age male (and a life-time learner), who's studies have primarily focused on subjects like sociology, anthropology, psychology, philosophy, et cetera... (humanities, human sciences). But still, knowing how dysfunctional most people are, have been, and will be, I still choose to engage with them regularly. We all make mistakes, don't we?

**Comment by bwinton** [comment]
I'm uninterested in continuing this discussion, as you seem to be acting in bad faith.  Good day.
