### ISSUE TITLE
[FeatureRequest] Hotkeys

### ISSUE THREAD

**Issue by saksmt** [bwinton/TabCenter#644]
There is awesome feature - tab filtering, but it almost useless without the ability to call it with hotkey and to navigate through found tabs with only keyboard.

Flow:
1. `Ctrl` + `G` - for focusing on filter input
2. Type your filter request
3. Use arrow keys to navigate between filtered tabs
4. Press enter to select one

**Comment by bwinton** [comment]
Try `Ctrl-Shift-L`, and `Ctrl-Tab` (or `Ctrl-Shift-Tab`)…  🙂
(It may be `Ctrl-Shift-K` in the version you‘re running.)

**Comment by saksmt** [comment]
@bwinton, thanks, `Ctrl` + `Shift` + `K` works, but it pins the tab pane also it's not so comfortable to switch immediately between tabs with `Ctrl` + `Tab` especially when you have about 30 open tabs where most of them unloaded from memory.

Also: did you ever try to switch more than one tab with `Ctrl` + `Shift` + `Tab` with only one hand? :smile:

**Comment by bwinton** [comment]
`Ctrl-Shift-K` will also close the tab pane, if it's open, which should make it a little better.  (And yeah, I switch between tabs with a one-handed `Ctrl-Shift-Tab` all the time…  Perhaps I have a different keyboard layout, or perhaps all my tabs are loaded, but it doesn't seem that bad to me.  🙂)
