### ISSUE TITLE
Conflicts with Tab Groups (former Firefox Panorama feature)

### ISSUE THREAD

**Issue by leezu** [bwinton/TabCenter#648]
When using tab groups ( https://github.com/Quicksaver/Tab-Groups ) the TabCenter does not work as expected.

When first enabling TabCenter it only shows the tabs of the current group (as expected). However when hovering over the TabCenter for the first time it fetches also tabs of other groups and displays all of them.

This makes TabCenter useless when combined with the Tab-Groups addon.

**Comment by Quicksaver** [comment]
Also reported at https://github.com/Quicksaver/Tab-Groups/issues/375, haven't looked into it yet but I will soon.

**Comment by ericawright** [comment]
this will be fixed with #702
