### ISSUE TITLE
Stop setting browser.tabs.drawInTitlebar (or only set it on install)

### ISSUE THREAD

**Issue by nt1m** [bwinton/TabCenter#649]
My Firefox layout looks like this with browser.tabs.drawInTitlebar = true :
<img width="1440" alt="stop-drawing-in-titlebar" src="https://cloud.githubusercontent.com/assets/1795135/19021887/4a6109ee-88c3-11e6-89c6-011cc3658f47.png">

But TabCenter keeps setting browser.tabs.drawInTitlebar to false, which prevents me from having that layout.

It would be less annoying if the pref was only set on install, instead of every startup and customization mode change.

**Comment by ericawright** [comment]
@nt1m this should be fixed now with #701
