### ISSUE TITLE
After instalation I was totally blocked from using FF until plugin was disabled

### ISSUE THREAD

**Issue by slobodan-djukic** [bwinton/TabCenter#651]
I just installed plugin and the browser/page started to look like on the attached image. Pages that were open before became grey with no displayed content at all. I was just able to close the tabs. Terminating FF and starting again would not help. I had to start FF in safe mode and to disable this plugin. I am on OSX El Capitan, FF 49.0.1.

![screen shot 2016-10-03 at 3 19 55 pm](https://cloud.githubusercontent.com/assets/4256826/19039102/d6fb8468-897e-11e6-9ad7-e0b4ea0f2c28.png)
![screen shot 2016-10-03 at 3 22 55 pm](https://cloud.githubusercontent.com/assets/4256826/19039101/d6fa3d7e-897e-11e6-8485-bb18137770b8.png)

**Comment by ericawright** [comment]
linking this to #675
