### ISSUE TITLE
Close button doesn't appear for tabs that exceed the length of the sidebar.

### ISSUE THREAD

**Issue by filchermcurr** [bwinton/TabCenter#656]
Since the change back to scroll bars, tabs with long names (longer than the sidebar) don't display the close button when you hover over them. Tabs with semi-long names show the close button is being obscured by the scroll bar.

[Edit! I opened another window and the close button doesn't appear in long titles even without scroll bars.]

[moar edit: Toggling 'keep sidebar open' off and then back on results in the close buttons showing properly until the next time I open Firefox, so it seems to be a problem with the sidebar always showing.]

I'm using...
Firefox Nightly (2016-10-03)
Tab Center 1.25.0
macOS Sierra 10.12

(p.s. I don't know where to actually submit feedback, so I'll sneak it in here. An option to restore the old scrolling behavior would be great!)

**Comment by ericawright** [comment]
thank you! (note: this has to do with the crop)
