### ISSUE TITLE
Keep the tab bar visible when the search box is in focus

### ISSUE THREAD

**Issue by dannyhajj** [bwinton/TabCenter#659]
Not sure if this related to #571 but currently, when the search box is in focus and the tab bar is not always visible/pinned, once you mouse away from the from bar, it collapses while the search box is still in focus, and you still type and filter.

## Current behavior & Steps to reproduce
- Set the Tabs sidebar to collapse when the mouse is not hovered over it
- Focus on the search box
- Start typing "Git"
- Move the mouse away from the sidebar so it collapses (but don't click anywhere)
- At this point #571 occurs (The search box is emptied)
- Continue typing "Hub"
- Hover over the sidebar so it opens.
- The current filter will be "Hub"

## Suggested behavior
- Keep the tabs sidebar visible when the search box is in focus
- Another possible behavior would be to remove focus on the search box the bar is collapsed, but the previous point, in my opinion at least, would make more sense

## System info
- Firefox 50.0b3
- Ubuntu 16.04
- Tab Center 1.25.0

**Comment by ericawright** [comment]
I would say this is the exact same behavior as #571 is referencing, so I'll dupe it to that
