### ISSUE TITLE
[Bug] No way to access address bar in fullscreen.

### ISSUE THREAD

**Issue by Hoverbear** [bwinton/TabCenter#660]
**OS:** Mac OS X
**FF Versions:** 49.0.1

When I make Firefox full screen, the address bar becomes inaccessible.

Previously, I could move my mouse to the top of the screen and the address bar would show. This includes previous versions of TabCenter.

Now, it does not.

### Screenshots:

Not in full screen:

![screen shot 2016-10-04 at 10 16 57](https://cloud.githubusercontent.com/assets/130903/19066853/b264dc38-8a1b-11e6-901d-205b734d051c.png)

In full screen, mouse not at top:

![screen shot 2016-10-04 at 10 17 24](https://cloud.githubusercontent.com/assets/130903/19066864/c18883f4-8a1b-11e6-9af3-bf98b42848db.png)

In full screen, mouse at top:

![screen shot 2016-10-04 at 10 17 40](https://cloud.githubusercontent.com/assets/130903/19066869/cb1511da-8a1b-11e6-99d1-f3b7f1b3c3ce.png)

**Desired behavior:** I should be able to see and change the address bar while in full screen.

**Comment by dannyhajj** [comment]
I confirm this behavior on Ubuntu 16.04 as well. Using Firefox 50.0b3
Though I would also like to add that the address bar is accessible when using the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>L</kbd>.
But after using that shortcut, sometimes the awesome bar becomes visible sometimes not. Haven't figured out if there's a pattern.
When it is visible, it disappears when using some keyboard shortcuts in that bar like <kbd>Ctrl</kbd>+<kbd>Z</kbd> to undo or <kbd>Ctrl</kbd>+<kbd>A</kbd> to select all.

p.s. Even if the the bar disappears, it is still focused and you would still be able to type in it. The suggestions you get while typing stay visible even if the awesome bar disappears.

**Comment by spectrumcat** [comment]
Thank you @dannyhajj, the key shortcut works! In my case the bar disappears after I right-click on a tab and in any way exit the menu that popped up (like click somewhere else)

**Comment by ericawright** [comment]
@Hoverbear  this behavior is incorrect, I'll work on fixing it. But in the meantime there is a small dark line at the top of Tab Center, if you hover that the awesome bar should expand again.

**Comment by Hoverbear** [comment]
@ericawright Keep up the awesome (pun intended) work! :)
