### ISSUE TITLE
Shrink sidebar not working

### ISSUE THREAD

**Issue by NaRuBeTo** [bwinton/TabCenter#665]
I'm really liking the Tab Center, but for the past few days, "Shrink sidebar when not in use" is not working.
I've tried toggling and I've tried restarting the browser.
I didn't see anything here addressing this issue; please feel free to link me to an existing thread if I have simply missed one.

**Comment by NaRuBeTo** [comment]
Aaand, of course, it's working just fine now.

**Comment by ericawright** [comment]
@NaRuBeTo it may have had something to do with the update which was just pushed yesterday?

**Comment by Mahendranadh** [comment]
Is this fixed? It still doesn't shrink for me? This bug has got me to the point where I almost want to disable TabCenter

**Comment by ericawright** [comment]
@Mahendranadh since the original reported said it was fixed, and couldn't duplicate it, we didn't have any further information to work on in order to fix it.
If you have some steps to reproduce, gifs, or other info you can give us we'll have a better chance at fixing it.

**Comment by Mahendranadh** [comment]
![firefox_tabcenter_shrink](https://cloud.githubusercontent.com/assets/17054715/19870552/473abc94-9f6e-11e6-8daf-dd01a14c3f88.gif)

Am on Beta Channel of Firefox and 50.0b7 is my version

**Comment by Mahendranadh** [comment]
Thanks for the reply @ericawright Here is the Gif and some other detail

**Comment by ericawright** [comment]
It's a little tough to see in that gif, but what looks like is happening is that it briefly goes into shrink mode, then changes back. Does that sound correct to you?
I'll try reproducing it in Beta

**Comment by Mahendranadh** [comment]
I shared a video on my gdrive. Hope that is better. If not, I can do a quick session on vidyo too. Let me know. Thanks!
