### ISSUE TITLE
Tab list scroll position changing on mouseout

### ISSUE THREAD

**Issue by Maeyanie** [bwinton/TabCenter#669]
Recently, when I scroll the list of tabs, when I move the mouse of of the list it instantly changes to the selected tab being at the bottom of the page.

If I mouseout while the list is still scrolling, it keeps its position after it finishes, but then instantly changes when I move the mouse onto the tab list instead.

**Comment by Maeyanie** [comment]
Actually it seems to be not really consistent about the position where it sets the scrolling.

**Comment by devanes** [comment]
I can confirm this (on FF for Linux)

**Comment by mhammerly** [comment]
ff49 on linux (two systems), and I see similar behavior. When I move my mouse away from the tab list, it snaps to the top of the list. No position change when I move my mouse into the list.

**Comment by ericawright** [comment]
This is because of the way the `overflow` attribute is being handled (though it is tough to solve). Thanks for the info!

**Comment by soar** [comment]
Old scrollbar (little styled ellipse) looks mush better, than new default windows light long bar. I use FF Developer Edition with dark theme.

**Comment by devanes** [comment]
This issue is starting to really nag me. It didn't happen until recently, so looks like it's a new bug/regression. If this isn't fixed soon, I'll be forced to stop using Tab Center until it is. The tab bar just keeps scrolling to the current tab which makes selecting a different one (in my long list of tabs) very difficult.

**Comment by kirbysayshi** [comment]
Has this fix been released? This is currently a very large pain point of using tabcenter.
