### ISSUE TITLE
vertical tab does not maximizes when mouse hover 

### ISSUE THREAD

**Issue by ayazmaqbool** [bwinton/TabCenter#670]
Hi earlier when mouse cursor was hovered over the tabs it would slide and give you more details of the tab and also one could close it but since this week the functionality is not working , please help me resolve it .

**Comment by ericawright** [comment]
Do you mean that you can no longer close the tab when you click the x button, or that the x button does not appear?
As for the more details on hover - what type of details are missing?
Any extra info would be great. Thanks.

**Comment by ayazmaqbool** [comment]
Please view demonstration of the issue ,`https://drive.google.com/open?id=0B2gReGpg2LsiYVFybkFBVTBYaG8`  .Earlier if one hovers over the tabs, it used to slide and gives option to close X , now I have to right click and close it , thats very painful , can you help me if there is a setting which needs to be changed . Attachment can be opened in any web browser ,its a swf file .

**Comment by ericawright** [comment]
Oh I see!
Hopefully this video will help you :)
![oct-05-2016 10-08-58](https://cloud.githubusercontent.com/assets/10803178/19116479/acbc9d0c-8ae3-11e6-89eb-97c92d7a3290.gif)

The button on the top right side of Tab Center sets the state to "pinned" or "unpinned". If it is "pinned" you can drag it to resize to whatever size you like. When "unpinned" it will pop in and out.
