### ISSUE TITLE
Address bar goes missing after some time

### ISSUE THREAD

**Issue by vigyasharma** [bwinton/TabCenter#671]
Address bar gets hidden after some time. It however does not come back on mouse over or scrolling up, and seems to take an unpredictably long time to come back.
Not sure if this is a planned feature, but unable to find a way to get address bar back quickly after I enabled TabCenter.

Device: MacBook Pro (Retina, 13-inch, Early 2015)
OS X El Capitan Version 10.11.6
Firefox 49.0
<img width="1280" alt="screen shot 2016-10-05 at 11 28 42 am" src="https://cloud.githubusercontent.com/assets/869395/19102577/f3852af0-8aee-11e6-92eb-8ba52da80e7e.png">

**Comment by dannyhajj** [comment]
If your issue occurs when when Firefox is in fullscreen, see issue #660 to check if it's the same problem. As this was reported and fixed yesterday.

> https://github.com/bwinton/TabCenter/issues/660#issuecomment-251386479: this behavior is incorrect, I'll work on fixing it. But in the meantime there is a small dark line at the top of Tab Center, if you hover that the awesome bar should expand again.

**Comment by vigyasharma** [comment]
Yes, this is the same issue. Thank You.
