### ISSUE TITLE
alwaysright FF extension is broken

### ISSUE THREAD

**Issue by jdm** [bwinton/TabCenter#674]
[alwaysright](https://addons.mozilla.org/en-US/firefox/addon/always-right/?src=api) makes new tabs opened (either via links or explicit new tab actions) always appear to the right of the current tab in the non-vertical mode. Until the most recent TabCenter update, this was working fine; now explicit new tab actions always open at the end of the bar, rather than adjacent to the current one. Ctr+click on a link still works fine.

**Comment by jdm** [comment]
This seems related (but maybe not identical?) to #655.

**Comment by bwinton** [comment]
Do you see the same behaviour if you toggle the "Tabs on Top" preference?

**Comment by jdm** [comment]
No. It behaves like it did before the update (both in terms of vertical direction of new tabs, and expected position of new tabs relative to current).
