### ISSUE TITLE
Keep Sidebar Open Creates Image Misalignment

### ISSUE THREAD

**Issue by ZombieFodder** [bwinton/TabCenter#677]
![firefox tab issue](https://cloud.githubusercontent.com/assets/22640905/19118984/3dd09fac-8aec-11e6-9211-a45b6e4da39b.PNG)
As observed in the attached photo, when I use the keep sidebar open option in the vertical tabs I view a small portion of my desktop on the right most side of the screen (I believe it is transparent). I am using Firefox 49.0.1 on a Windows 7 64bit Professional license. It appears that all content is present, just not aligned properly.

**Comment by ericawright** [comment]
is this in fullscreen?

**Comment by ericawright** [comment]
I can't seem to reproduce this. Can you give me some steps?
Also, if you happen to have other addons that may be conflicting could you try disabling those?

**Comment by ZombieFodder** [comment]
I have narrowed this issue down to enabling/disabling the plugin Capture for JIRA V2.9.7.0 by Atlassian. We use Atlassian tools at work and therefore the Jira plugin. 

With regard to steps for reproducing, I simply launch Firefox, click the Keep Sidebar Open button and the issue appears. It does not matter if the Firefox window is full screen, maximized, or windowed mode.

I hope this helps.

**Comment by ericawright** [comment]
great thank you! I'll add  Capture for JIRA to this list for now: #464
