### ISSUE TITLE
Add a small delay before expanding the tab center on mouse hover

### ISSUE THREAD

**Issue by dannyhajj** [bwinton/TabCenter#678]
At the moment, as soon as the the mouse is hovered over the collapsed bar, the animation begins.
Even if we instantly move mouse out of the tab center, the animation would still run (I guess this is probably due to the timeout that currently exists before starting the collapsing animation).

This behavior sometimes causes problems since the browser's back button is right next the tab center at the top left (It's also an issue if you try to access the first bookmark I guess).
Maybe it's because my resolution is very high, but I almost always miss the back button on the first try when trying to hover over it with mouse; So the mouse slightly hovers over the tab center. By the time I correctly move back the mouse cursor over the back button, the tab center expands and I end up clicking on the tab center's "New Tab" button instead of the back button.

My suggestion is to add a very short timeout before expanding the Tab Center (like the one that exists before the tab center collapses). Maybe even allow us to change the default value with Firefox's about:config.

**Comment by omeringen** [comment]
IMHO, https://github.com/bwinton/TabCenter/issues/639 will resolve this issue too.

**Comment by macxcool** [comment]
I agree. It's too sensitive. A delay would prevent all the times the sidebar opens when i don't want it to.

**Comment by c633** [comment]
It's probably better if we can custom these timeout values from `about:config` (both collapsing and expanding)

**Comment by bwinton** [comment]
I disagree.  This extension isn't meant to be all things to all people, but instead to work the way we feel will be the best for the most people.  More importantly, there are only 1.5 people working on this, and every extra about:config value doubles (or more) the amount of testing we have to do, and the number of cases we need to consider when adding new features.

We should definitely add a small delay, but it's _not_ going to be configurable.

**Comment by dannyhajj** [comment]
@omeringen Although #639 would help, I don't think it would solve the problem completely. If your working on a website that uses 100% of the browser's width (Google Spreadsheets for example), this #639 wouldn't help at all.
I agree with @bwinton. I don't see any advantage of having this a setting in about:config. Not sure if more than handful of people would ever even change it.

**Comment by c633** [comment]
I feel like the delay before the tab center collapses is too long. Not sure how others feel about this but to me, it seems to reduce my work efficiency. Just my personal feeling, don't bother.

**Comment by macxcool** [comment]
I think that the enter delay is fine now but, as c633 comments, the exit delay could be shorter. That seems like another 'issue' though, so I'll start a new thread.

**Comment by dannyhajj** [comment]
Has this been silently implemented? :stuck_out_tongue: It seems now the tab center doesn't open as soon as the mouse is hovered over it. And it seems to be working great so far,

**Comment by ericawright** [comment]
@dannyhajj there has always been a small delay - If I recall correctly it was implemented before this issue was even opened. The delay has not been made longer though, not yet.

**Comment by dannyhajj** [comment]
@ericawright In that case, I'd say this is no longer valid. When I had opened this issue, there didn't seem to be any kind of delays at all. However, the way it behaves at the moment is great in my opinion. I'm no longer having any of the issues I described in my original post.

**Comment by ericawright** [comment]
@dannyhajj good to know, I'll close the issue.
