### ISSUE TITLE
Cmd+T open a new tab before all the tabs

### ISSUE THREAD

**Issue by indradhanush** [bwinton/TabCenter#683]
If I have the tabs: 1, 2, 3, 4, 5 and 6, where the tabs 1 and 2 are pinned tabs.
Now on hitting Cmt+T on OSX, the new tab pops up between tabs 2 and 3 instead of after 6.

**Comment by ericawright** [comment]
Yes, the default setting for this changed (we will be changing it back shortly) but you can go to `about:addons` in the awesomebar and click `extensions` on the left, then on `preferences` for tab center and change your tabs to open on the top or bottom of your list, as you like it.
