### ISSUE TITLE
Tab Center doesn't recognize "The Addon Bar (restore)" addon in Firefox's personalize layout menu

### ISSUE THREAD

**Issue by RodrigoCav27** [bwinton/TabCenter#690]
Whenever Tab Center is active, an addon which adds a toolbar in the botton of Firefox window layout, ("The Addon Bar (restore)), doesn't appear in Firefox's personalized menu layout. I would like to add in contrast, that the addon is still shown and active in the general window layout, that is when is not in personalize menu mode.

I don't know how much Tab Center changes Firefox window layout under the hood that can causes this; and I imagine that when Firefox ships a change in a new release it's the in the non official Firefox addon's creators job to make the corresponding changes; but still I thought it would be a good idea to report this never the less.

Is it ok to report conflicts that Tab Center has with other addon, like with other sidebars addon?

Thanks in advance.

**Comment by bwinton** [comment]
It changes the layout quite a bit, I'm afraid.  🙁
It's very much okay to report conflicts like this, and if you can find the author of the other add-on(s), please point them at this repo so that we can try and get everything working together…

Thanks!

**Comment by ericawright** [comment]
duping this to this list for now #464
