### ISSUE TITLE
Add a toggle to switch between side tabs and tabs on top

### ISSUE THREAD

**Issue by phlsa** [bwinton/TabCenter#691]
There is currently no easy way to toggle between side tabs and tabs on top once tab center is installed. You either get one or the other.

This concept adds a button to the tab strip or the header of tab center that toggles between the two views.

Note that we should also make sure that we instrument how much time a user spends in either mode and how often (in total and per session) the layout is toggled. Happy to file a separate issue for the instrumentation if needed.

![tc toggle](https://cloud.githubusercontent.com/assets/514315/19231053/2c3e7292-8ed8-11e6-8f6c-16c23a2499a3.png)

**Comment by nt1m** [comment]
@phlsa I rather would put the switch inside the customization mode (or next to the collapse sidebar button), since it's not an option people would toggle often.

**Comment by phlsa** [comment]
That's part of what I'd like to find out: would people toggle back and forth frequently or would they remain in a mode forever?
As for the placement within tab center: Unfortunately, both the collapse and the toggle button are quite non-standard. I'm afraid that putting them right next to each other will make the UI harder to read. Also, with this placement, the button stays roughly in the same place, with should help with recognition.

**Comment by phlsa** [comment]
Here's some icons as SVG
[tc-icons.zip](https://github.com/bwinton/TabCenter/files/523905/tc-icons.zip)

**Comment by ericawright** [comment]
@phlsa 
Some questions we've been thinking about:
should enable/disable be on a per-window basis?
      if yes, how do we report (and make use of) that info for the shield study?

**Comment by phlsa** [comment]
@ericawright A general enable/disable should be enough for now :)

**Comment by phlsa** [comment]
Oh, and I've just seen in the other issue that you made it per window -- that's cool too

**Comment by phlsa** [comment]
Oh, I've just seen that you made it per window in the PR. That's cool too.
As for instrumentation, we should probably collect data on number of windows in each mode and time spent in each mode or something like that.
