### ISSUE TITLE
Not respecting hidden tabs

### ISSUE THREAD

**Issue by Quicksaver** [bwinton/TabCenter#692]
You can [hide and show tabs in Firefox](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#2965-3020); from a quick dxr search, SessionStore and the devtools seem to take advantage of this, although I haven't really tested the specifics on either. I do know that there are add-ons that do use this feature (https://github.com/Quicksaver/Tab-Groups/issues/375).

Tab Center is not respecting this at all, its ```filtertabs()``` method always shows all tabs when not there's no filter query. Was this a deliberate decision, to bypass previously hidden tabs? It seems like it would be fairly straightforward to fetch a copy of ```gBrowser.visibleTabs``` and use it to restore properly hidden tabs after the search has ended. Or maybe not if there's no way to automatically end that search, so the filter term would remain there possibly through many operations that would render that backup of previously hidden tabs useless?

Note that I'm perfectly fine addressing the problem with Tab Groups within Tab Groups itself. I just don't fully agree with how Tab Center is doing its filtering and thought I'd bring it up.

**Comment by bwinton** [comment]
It wasn't a deliberate decision, as far as I know, but @ericawright would know better.
(We're mostly just looking for obvious APIs, so if we get the wrong one, like we did for the thumbnails, it's not malicious.  🙂)
I'm up for switching it so that Tab Groups works out of the box.  (Heck, I've been using Tab Groups since before it was integrated into Firefox!  Of course I want it to stay working!  😄)

**Comment by Quicksaver** [comment]
I'll probably end up having to tweak Tab Groups as well, regardless of what you end up doing here. For example, if the user inputs something in the textbox to filter the tabs, and then switches groups without clearing the search box at the top, then any copy you had from ```visibleTabs``` would be outdated and useless. So at least for now I wouldn't worry about Tab Groups compatibility as far as that goes, I guess that's my problem either way. 😄  (Just don't remove the ```VerticalTabs``` object from the main window, please, as long as that stays accessible, it's easy to adapt to it.)

My concern was that [```gBrowser.visibleTabs``` is used in a lot of places](https://dxr.mozilla.org/mozilla-central/search?q=visibleTabs&redirect=false). By setting a tab's hidden property, Tab Center is essentially nulling that; when Tab Center filters tabs with a search term, either the visibleTabs is cached and only actually a subset of those are visible, or it caches with only those filtered tabs which is technically a lie because all other tabs are still there and could be important.

Note that I really have no idea in which cases it's desirable (for those functions that work with ```visibleTabs```) for that to happen, maybe there are a few cases where those should really know about only the filtered tabs and not unfiltered ones, but I suppose you'd know that better than me. For one, I'm sure Telemetry doesn't care about filtered tabs. 😉 

Personally, in Tab Center I'd stay away from a tab's hidden property and use something else to filter them, because of how that's used, or at least supposed to be used, throughout the browser it seems very error-prone; it doesn't seem like a "use this to temporarily filter tabs" thing at all.

**Comment by Quicksaver** [comment]
> it doesn't seem like a "use this to temporarily filter tabs" thing at all.

Note the words "doesn't seem"! I could be completely wrong, you'd have to go through its uses in the browser to have a more concrete answer of course; I haven't checked how Tab Center uses it beyond filtering the tabs either, so again you definitely would know better than me. :)

**Comment by Quicksaver** [comment]
Wrote a quick fix for Tab Groups so that things work for now: https://github.com/Quicksaver/Tab-Groups/commit/5fc0bfcf3730ece1522db33211dbaaad577caca6. It should be easy to follow if you'd like to take a peek at how I handled Tab Center's ```filterstabs()```, but if you need any info just ask!

By the way, I noticed that the ```actuallyResizeTabs()``` method currently relies on a comparatively more expensive ```querySelectorAll``` call; using ```visibleTabs``` (and everything else related of course) in Tab Center itself may bring some benefit there, regardless of if ```filtertabs``` ends up using those as well or something else entirely; the possibilities are interesting at least.

Of course I'll try to keep a close eye on Tab Center's development, to make sure Tab Groups doesn't screw anything up with its fixes for now.

In the long run, what are your ideas for having both add-ons (and maybe other things that make use of tab visibility?) play nice together? I could see either add-on keeping some sort of list or controller in the main window to reset back to unfiltered tabs correctly, which the other add-on would respect.
