### ISSUE TITLE
Needs an option to show small tabs always

### ISSUE THREAD

**Issue by Temeez** [bwinton/TabCenter#700]
[I don't like needing] to have an x amount of tabs open before the tabs get smaller. I don't have time to look at the thumbnail, url and then the title to find the tab that I'm looking for!

**Comment by andrewshadura** [comment]
👍

**Comment by bwinton** [comment]
(Edited to remove insults.)

**Comment by bwinton** [comment]
Also, this is a duplicate of issue #439.  Thanks for the report, though!
