### ISSUE TITLE
"New Tab" does not work in a new window

### ISSUE THREAD

**Issue by jamesderlin** [bwinton/TabCenter#703]
If I have Tab Center enabled and create a new window, I cannot create additional tabs in that new window. None of Ctrl+T, the "New Tab" button, nor "Open Link in a New Tab" from a context menu work.  Disabling TabCenter makes opening new tabs work again.

I suspect that this might happen with any window that has only one tab (perhaps this is related to recent changes that affect whether new tabs open before or after the current tab?).

**Comment by jamesderlin** [comment]
Hm, I can't reproduce it with a clean profile, so maybe there's some weird interaction with another extension I have.  I'll reopen this if I can figure out better reproduction steps.

**Comment by ericawright** [comment]
@jamesderlin thanks, please let us know if you happen to figure out what was causing it so we can note it.
