### ISSUE TITLE
Print Preview Menu Bar

### ISSUE THREAD

**Issue by fxnick** [bwinton/TabCenter#721]
Open multiple tabs, Do Print Preview.
Top Menu Bar with print options stays across all tabs and new tabs.
Tested on windows 7 sp1

**Comment by ericawright** [comment]
@fxnick can you tell me how you are doing print preview? Are you using an add-on for this?

**Comment by ericawright** [comment]
Windows 7, with TC:
![screen shot 2016-10-24 at 1 58 28 pm](https://cloud.githubusercontent.com/assets/10803178/19657353/e301af52-99f1-11e6-9b42-2f4528cb2f15.png)

Windows 7, regular:
![screen shot 2016-10-24 at 2 00 18 pm](https://cloud.githubusercontent.com/assets/10803178/19657378/fb26b000-99f1-11e6-8e10-95020bf1c85f.png)
