### ISSUE TITLE
browser.tabs.drawInTitlebar preference is broken

### ISSUE THREAD

**Issue by nt1m** [bwinton/TabCenter#722]
Because of https://github.com/bwinton/TabCenter/blob/ae3b16a0ce3bc1ea260487a9c6a5c6b16f091382/verticaltabs.js#L307

**Comment by bwinton** [comment]
As mentioned in another bug, we don't support non-standard `about:config` preferences.  But we might be switching the design to not draw the titlebar in a future update…
