### ISSUE TITLE
Sidebar stays open forever? when mouse goes out of window before animation completes

### ISSUE THREAD

**Issue by macxcool** [bwinton/TabCenter#724]
If I slide my cursor to the left until the sidebar pops open and then move it out of the trigger region before the open animation is finished, it stays open forever until I retrigger the opening.
I suppose this might be fixed by adding a delay, but a delay might just make it worse by extending the time to get your mouse out of the trigger region before the animation starts.

**Comment by macxcool** [comment]
I'm using Firefox on Windows 8.1 with dual screens. That's why I often go off the window to the left quickly. I'm moving the mouse to my other monitor.

**Comment by ericawright** [comment]
I cannot duplicate this. Any other info you can give me would be great, does this happen ever time?

**Comment by macxcool** [comment]
Yes. It was happening every time for the last few days.
Now I can't get it to happen at all. Was there an update?

**Comment by ericawright** [comment]
hmm, no, there was not. I think the last update was over a week ago. Perhaps you had not restarted Firefox since the last update? Did anything else change, other add-ons maybe?

**Comment by macxcool** [comment]
I haven't restarted Firefox. This is weird. I was getting the sidebar popping open whenever the mouse went over it, even very quickly. Now it's ignoring anything below a certain threshold time.

Oh well. Fixed, I guess.

**Comment by ericawright** [comment]
okay, reopen if it comes back :)
