### ISSUE TITLE
urlbar lose content when clicked/Ctrl+L

### ISSUE THREAD

**Issue by pymaldebaran** [bwinton/TabCenter#739]
When TabCenter is activated if ever I Ctrl+L or click on the urlbar I get a "search prompt" (just like in a new tab) instead of the actual url of the current page...

**Comment by ericawright** [comment]
![nov-01-2016 14-44-04](https://cloud.githubusercontent.com/assets/10803178/19902570/b022d2c2-a041-11e6-894a-62c7f868b30d.gif)

I can duplicate this on the moment of install or uninstall, and only on the test pilot page.
