### ISSUE TITLE
Test Pilot should mention where to find options

### ISSUE THREAD

**Issue by laktak** [bwinton/TabCenter#749]
As the process for installing TabCenter via Test Pilot is quite different from installing a normal add-on I didn't think of TabCenter as an add-on at first. So when I first installed it, it didn't occur to me that its options can be found on the add-ons page and it took me some time to find them.

A screenshot of the options page would probably help new users.

**Comment by bwinton** [comment]
Well, we don't actually want people to change the options, since that would affect the experimental data we get, so I think this is going to be closed "wontfix".  Thanks for the idea, though!
