### ISSUE TITLE
1 more tab...

### ISSUE THREAD

**Issue by laktak** [bwinton/TabCenter#750]
I get a line "1 more tab..." that does nothing.

Repro (with Firefox developer, on master `jpm run -b...`):
- open a single tab (e.g. "example.com")
- open add-ons from the menu

<img width="412" alt="more" src="https://cloud.githubusercontent.com/assets/959858/19908483/d2918cee-a083-11e6-9b8d-fa0fd4927d5d.png">

After clicking on "1 more tab..." the "1 more tab..." item disappears.

**Comment by ericawright** [comment]
That is being fixed with #748. Thanks :)
