### ISSUE TITLE
Disabling animations when exiting fullscreen

### ISSUE THREAD

**Issue by cocreature** [bwinton/TabCenter#758]
Currently when exiting fullscreen (I only tried youtube so far), there is an animation that redraws all of the tabs. I find that to be quite confusing since I expect an animation to indicate that something has changed but the tabs are still the same.

Obviously this is pretty subjective so an option to disable this rather than disabling it for everyone is just fine.

#740 is related but is about disabling all animations rather than one specific animation.

**Comment by ericawright** [comment]
I'm not sure about adding an option to disable it. But I agree that the animation should only happen when a NEW tab is being created or a tab destroyed - not when all of them are reappearing. I'll see what I can do ;)
