### ISSUE TITLE
TabCenter doesn't load on boot.

### ISSUE THREAD

**Issue by Or3stis** [bwinton/TabCenter#765]
When I start Firefox the default theme is shown for about a second. After that the TabCenter is loaded.

![test](https://cloud.githubusercontent.com/assets/11923550/20031562/99c4587e-a371-11e6-940c-a8900de89733.gif)

Is that a common behavior or is there something wrong with my settings?

I am using macOs 10.12.1 and Firefox 49.02.

**Comment by ericawright** [comment]
@Or3stis That is common behavior. 
Tab Center is an add-on, and not part of the default behavior of Firefox. So, the add-on is not activated until Firefox has finished starting up.
