### ISSUE TITLE
Mousewheel scrolling no longer works in the Sidebar if the "Reverse Tab Order" option is enabled

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#776]
[Affected versions]:
- Nightly 52.0a1
- Tab Center 1.26.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to false and latest Tab Center add-on is installed.
- Have multiple tabs opened so that the Sidebar is scroll-able.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to about:addons -> Extensions.
3. Double click the Tab Center addon and click the "Reverse Tab Order" option.
4. Hover the Sidebar and scroll through the list using the mouse wheel.

[Expected result]:
- The list is scrolled.

[Actual result]:
- Nothing happens.

[Notes]:
- This issue is not reproducible on the Tab Center version from Test Pilot.
![mousewheel no longer works with reveresed tabs](https://cloud.githubusercontent.com/assets/18304511/20141263/361ede3c-a698-11e6-8174-bbb9a76ce4a0.gif)

**Comment by ericawright** [comment]
I cannot duplicate

**Comment by SoftVision-CiprianMuresan** [comment]
@ericawright could you try this build https://goo.gl/uiK1Ry? Maybe there's something wrong with it.

**Comment by ericawright** [comment]
hardware required: real mouse wheel

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest 1.26.0 build (custom xpi).
