### ISSUE TITLE
Reword "close_tabs_above" and "close_tabs_below" context menu options

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#777]
[Affected versions]:
- Nightly 52.0a1
- Tab Center 1.26.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to false and latest Tab Center add-on is installed.
- Have at least 2 tabs opened.
- "Reverse Tab Order" option is disabled for Tab Center from "about:addons > Extensions" section

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Right click on one of the tabs.
3. Observe the "close_tabs_below" context menu option.

[Expected result]:
- "Close Tabs Below" is displayed.

[Actual result]:
- "close_tabs_below" is displayed.

[Notes]:
- The issue is also reproducible for the "close_tabs_above" option, if the "Reverse Tab Order" option is enabled for Tab Center from "about:addons > Extensions" section.
- This issue is not reproducible on the Tab Center version from Test Pilot.
![reword close_tabs_belowabove context menu option](https://cloud.githubusercontent.com/assets/18304511/20141803/ac0c1446-a69a-11e6-8552-2cf85f2a0223.gif)

**Comment by ericawright** [comment]
thank you. 
This is affecting all labels that were supposed to be localized.
Also will be fixed together with `opentabstop_description` which was incorrectly declared.

**Comment by ericawright** [comment]
@SoftVision-CiprianMuresan can you run `npm install` and `npm run locales` in your terminal before bundling the xpi. Let me know if it makes a difference, this should fix #775 and #776 as well.

**Comment by SoftVision-CiprianMuresan** [comment]
@ericawright, I did as instructed and #775 and #777 are no longer reproducible, but #776 still is. 
I'm gonna go ahead and close the two.
