### ISSUE TITLE
sidetabsbutton should only respond to left button

### ISSUE THREAD

**Issue by yfdyh000** [bwinton/TabCenter#779]
It responds to the mouse right button for now.
https://github.com/bwinton/TabCenter/blob/3101f4f41d6c9c5cc08448253cdafdd129b561ad/verticaltabs.js#L95

Also, I cannot to load the xpi after `jpm xpi`, is it right for now?
And, I cannot find the toolbar button for `side_label`.

**Comment by SoftVision-CiprianMuresan** [comment]
You need to have the "xpinstall.signatures.required" pref set to false in about:config. Also this only works on Nightly and Aurora.

**Comment by yfdyh000** [comment]
@SoftVision-CiprianMuresan But I see `There was an error during installation: File D:\repo\Mozilla\TabCenter\tabcentertest1@mozilla.com-1.26.0.xpi does not contain a valid install manifest` always.

**Comment by ericawright** [comment]
@yfdyh000 
`side_label` and `top_label` are never seen. `side_label` is the label for the same button that `side_tooltip` shows up on. 

The code that you reference is written to *stop* it from responding to the mouse right button. For me it does not respond on right-click.

**Comment by ericawright** [comment]
@yfdyh000 how are you trying to install it? After building the xpi are you dragging and dropping the file onto the browser?
(Also, make sure you've run `npm run locales` in the terminal in the Tab Center directory before building the xpi.)

**Comment by ericawright** [comment]
it no longer responds to It to the mouse right button.
