### ISSUE TITLE
The browser toolbar is wrongly displayed while in page "Print Preview" mode

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#791]
[Affected versions]:
- Nightly 53.0a1
- Tab Center 1.26.0

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to false and latest Tab Center add-on is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Visit any site and Print Preview the page. (File > Print Preview)
3. Observe the top part of the print preview window.

[Expected result]:
- Default "Print Preview" page elements are correctly displayed.

[Actual result]:
- The browser toolbar is wrongly displayed beside the default elements.

[Notes]:
- The browser toolbar is fully functional and can be used while in this state.
- This issue is not reproducible on the Tab Center version from Test Pilot.
![browser toolbar is displayed while in print preview](https://cloud.githubusercontent.com/assets/18304511/20347485/10e1bc80-ac0a-11e6-9d77-1bc772807478.gif)

**Comment by ericawright** [comment]
notes for self: 
- when print preview freezes or exits in a non-standard way TC will be lost
- if in toptab mode the tabs and icon stick around as well

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest 1.26.0 build (custom xpi).
