### ISSUE TITLE
Closing the print preview tab in tab center does not get rid of the print preview toolbar until the window is closed.

### ISSUE THREAD

**Issue by FLamparski** [bwinton/TabCenter#792]
Steps to reproduce:

0. open a new window
1. go to example.com
2. click File → Print Preview
3. observe a new tab appear in the tab center, and the print preview toolbar being shown
4. close the new tab using tab center
5. observe the print preview toolbar still being shown, which cannot be closed by clicking the 'Close' button contained therein

What should happen:

When the print preview tab is closed, the print preview toolbar should be hidden.

Versions:

* Firefox: 50.0b11 build ID 20161028075722
* Tab Center 1.26.0

**Comment by ericawright** [comment]
@FLamparski can you tell me which version of Windows or Linux you are on?

**Comment by FLamparski** [comment]
Sure. I'm running Ubuntu 16.10 on one system (Linux [redacted] 4.8.0-27-generic #29-Ubuntu SMP Thu Oct 20 21:03:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux), and another system I'm using is running Ubuntu 16.04 (Linux Tardis 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux).

I also just confirmed that the bug still occurs in Firefox 51.0b1 build 20161115122615.

I can send you my about:support data by email if you need it.
