### ISSUE TITLE
Feature Request: Ability to nest tabs within other tabs.

### ISSUE THREAD

**Issue by Shickmo** [bwinton/TabCenter#795]
Figured this would be a logical progression of the tool at some point. Also I would imagine the default behavior to be opening a new child tab within a parent it should open at the top of the list to perpetuate the default behavior of Firefox ctrl + tab = next tab / ctrl + shift + tab = previous tab but this behavior would ideally be configurable by the user.

**Comment by bwinton** [comment]
Nesting is something that we explicitly don't want to do in Tab Center.  There are a bunch of other extensions that cover that, and we feel that it's more complicated than it is useful for most people.

Thanks for the suggestion, though!
