### ISSUE TITLE
In fullscreen searchbar hints are cut from right side.

### ISSUE THREAD

**Issue by Vouskopes** [bwinton/TabCenter#803]
When pressing F11 than F6 and type searchbar.
![firefox tab center bug - f11 full screen _ f6 searchbar badly displayed](https://cloud.githubusercontent.com/assets/6736907/20467259/7145726a-af84-11e6-8927-67bb0ae5dd91.png)

**Comment by ericawright** [comment]
Thanks! This was fixed with https://github.com/bwinton/TabCenter/pull/711 and will be out with the next release.
