### ISSUE TITLE
Latest Update breaks tab navigation via keyboard shortcut

### ISSUE THREAD

**Issue by indradhanush** [bwinton/TabCenter#816]
"Tab shortcuts move in reverse" should be independent of "Newest tabs are on top" setting.

When I enable the "Reverse Tab Order", now my keyboard shortcut to move forward by one tab take me one to the tab above the current tab and vice versa for the keyboard shortcut to move backward by one tab.

**Comment by indradhanush** [comment]
Also Alt-1 goes to the last tab and Alt-9 goes to the first tab.
If I have 3 tabs pinned, Alt-9 goes to the 4th tab.

**Comment by heftig** [comment]
Especially the reversed Ctrl+PageUp/PageDown is confusing. Ctrl+(Shift+)Tab is less critical (and even unaffected if tab previews are enabled).

**Comment by ericawright** [comment]
duping this to #815.
Please continue the discussion there.
