### ISSUE TITLE
TabCenter doens't remember the bar width after firefox restart

### ISSUE THREAD

**Issue by saro** [bwinton/TabCenter#818]
Hello,
I use the tabcenter bar reduced to display only the tabs favicon. Since the last update the width of the bar seems to be lost at every firefox reboot forcing me to resize it manually at every start up.
Is this a new bug or an wanted behaviour?
Thanks

EDIT: If I kill firefox (with a kill -9 <pid>) at the restart the bar keeps the correct width. Same result if I restart the browser from the add-on menu.

Note: I'm using version 1.28 on Firefox 50.0 (Linux)

**Comment by ericawright** [comment]
Thanks for this! No it was not intentional, it seems to happen on windows and linux, not on mac. 

note for self: this is also not remembering tabs on top mode. 
Likely due to sessionstore.setWindowValue

**Comment by dannyhajj** [comment]
@ericawright A similar problem is that the TabCenter isn't remembering that I had auto-collapsed it. Is it the same issue, Or do I open a new ticket for that?
Firefox 51 on Ubuntu.

**Comment by ericawright** [comment]
@dannyhajj it's all due to the same issue, so you don't have to open a new ticket.
