### ISSUE TITLE
CTRL+PageUp/Down are reversed

### ISSUE THREAD

**Issue by SimonSapin** [bwinton/TabCenter#819]
The keyboard shortcut CTRL + PageDown normally goes to the next tab (below in TabCenter, left in default Firefox) and CTRL + PageUp to the previous on (above / right). Since a recent update, the direction is reversed: CTRL + PageDown goes up and CTRL + PageUp goes down.

**Comment by SimonSapin** [comment]
It looks like it’s more complicated than that. With recently-opened tabs, I can’t predict at all where PageUp or PageDown is gonna take me. I’m sure there’s a way to explain this behavior, but I haven’t figured it out yet.

**Comment by ericawright** [comment]
@SimonSapin this should only be the case if you have 'open new tabs on top' preference set. Please see this discussion:
#815
#816
