### ISSUE TITLE
New tab opened from pinned tab moves to bottom after a few seconds

### ISSUE THREAD

**Issue by SimonSapin** [bwinton/TabCenter#825]
Steps to reproduce:

* Have the "Reverse Tab Order" pref enabled
* Have a few pinned tab
* Find a link in a pinned tab
* Ctrl+click it
* The new tab for that link near the top of the tab list (but below pinned tabs), as expected
* Wait a few seconds
* Without further user action, this new tab then moves by itself to the bottom of the tab list. (Which makes it disappear completely if there is more than one screenful of tabs.)

**Comment by Screwtapello** [comment]
See also #821

**Comment by ericawright** [comment]
thank you, duping to #821
