### ISSUE TITLE
Tab Dragging/Scrolling Issue with Reversed Order

### ISSUE THREAD

**Issue by laktak** [bwinton/TabCenter#826]
When dragging tabs while the scroll bar is visible, the list will scroll in the wrong direction if you drag to the top or bottom.

I haven't had time to look at what changed but this is a regression on #737

**Comment by cpeterso** [comment]
If I drag a tab off the bottom of the tab list and release it when I have Reversed Order enabled, the tab returns to its original location (as expected), but then the tab list stops allowing tabs to be reordered.
