### ISSUE TITLE
Since 50 seeing weird errors of tab ordering and tabcenter quitting

### ISSUE THREAD

**Issue by supnah** [bwinton/TabCenter#827]
It seems like since the update to 50 TabCenter has been crashing on a somewhat regular basis. When it 'crashes' the tabs revert back to normal (top) for no apparent reason. TabCenter still displays as being enabled. If you disable, and then re-enable the sidebar will come back, but often with tab ordering issues. See the attached image where tab order is reversed, including pinned tabs being at the bottom. 

Here's a shot of what the tabs look like when tabcenter 'crashes' - notice the weird overlay of tabs on the right side. Another note is that when tabcenter is disabled, it continues to look like this.
![screen shot 2016-12-01 at 9 57 33 am](https://cloud.githubusercontent.com/assets/1953038/20806001/f8343e74-b7ad-11e6-8a8f-b41b431d05db.png)

Upon re-enabling tabcenter, this is what the sidebar looks like. Tabs in reverse order, pinned tabs at bottom. 
![screen shot 2016-12-01 at 9 57 43 am](https://cloud.githubusercontent.com/assets/1953038/20806006/fd312f9a-b7ad-11e6-9335-487ce1770e64.png)

I have experienced this multiple times now. Going to quit and restart Firefox with tabcenter enabled and see how it starts back up. Will report here.

**Comment by supnah** [comment]
Upon restart pinned tabs are correctly at top, but all tabs, and within pinned tabs, order is still reversed. 
![screen shot 2016-12-01 at 10 11 08 am](https://cloud.githubusercontent.com/assets/1953038/20806153/9abaed28-b7ae-11e6-95c3-7c753dd5c89b.png)

**Comment by ericawright** [comment]
if you go to `about:addons` in the awesomebar and navigate to tab center options, can you tell me if the 'tabs in reverse' pref has been selected?

**Comment by supnah** [comment]
Ahhh. I think so, except it's called: Open Tabs Above

In that case, maybe it's behaving as expected, but it would be a much better experience if tabcenter could remember what were pre-existing tabs and open them in normal order on a restart or when tabcenter is engaged, and only apply the open above action when a new tab is added to an existing window. Does that make sense? And maybe this is a known issue already. 

<img width="664" alt="screen shot 2016-12-02 at 9 06 37 am" src="https://cloud.githubusercontent.com/assets/1953038/20843111/eeda7a3e-b86e-11e6-8ac6-fad8a2b01d62.png">

**Comment by ericawright** [comment]
When you go to the options page again does it say version 1.26 or 1.28? I'm interested because the wording you show is from 1.26 but the toggle feature is from 1.28...

**Comment by supnah** [comment]
Now it says 1.28 and says "reverse tab order," but I don't know if it updated since that last screengrab when I quit and restarted Firefox to correct the issue. 

In any case, it's still having problems even now when it's definitely 1.28. 

<img width="1265" alt="screen shot 2016-12-03 at 3 51 47 am" src="https://cloud.githubusercontent.com/assets/1953038/20855199/de26635e-b90b-11e6-98ec-acde71d0b294.png">

**Comment by supnah** [comment]
Now it says 1.28 and says "reverse tab order," but I don't know if it updated since that last screengrab when I quit and restarted Firefox to correct the issue. 

In any case, it's still having problems even now when it's definitely 1.28. 
<img width="1265" alt="screen shot 2016-12-03 at 3 51 47 am" src="https://cloud.githubusercontent.com/assets/1953038/20855208/ff6bcec8-b90b-11e6-95fd-4bce506c6cf1.png">

Each time I go into tabcenter preferences and disable and then re-enable it adds another tabcenter icon in the top right. I just did it again after the screengrab above was taken, and now I have 4 of them. :o
<img width="193" alt="screen shot 2016-12-03 at 3 53 55 am" src="https://cloud.githubusercontent.com/assets/1953038/20855216/23661298-b90c-11e6-837f-a1c7f6d8ac54.png">

**Comment by ericawright** [comment]
I would ask you to create a new issue regarding the multiple icons but I'm unable to reproduce it. If you are still able to reproduce that one can you open a new issue and try to give me some steps to reproduce.

**Comment by supnah** [comment]
I am able to reproduce, but unfortunately it requires updating to a new version of firefox. Maybe there's a way to install an older version to prompt an update? I'm not sure the best way to go about that though.

**Comment by SoftVision-CiprianMuresan** [comment]
@supnah, you can download an older version of Firefox from [here](http://ftp.mozilla.org/pub/firefox/releases/49.0.2/)(the link is for 49.0.2, but you can get any version you like). Download the executable (.exe) file and extract the contents wherever you want, after that use CMD or Terminal and drag the Firefox in it and add "-p -no-remote". 
Now you have an older version of Firefox opened and it will prompt you to update to the latest one (if it doesn't, just go in Help->About Firefox).
