### ISSUE TITLE
Sidebar resizing on browser restart

### ISSUE THREAD

**Issue by herrgruebner** [bwinton/TabCenter#831]
I normally have the sidebar sized so that only the preview tiles are visible. When I restart the browser, the sidebar expands to full size, forcing me to resize it. This has only started happening in the past week or so, I'm not sure whether it was due to a FF or TabCenter update.

I'm running Firefox 50.0.2 with TabCenter 1.28.0 on Win 7

![sidebarbig](https://cloud.githubusercontent.com/assets/15949350/20856651/431c081e-b979-11e6-8032-c29ab2f348df.png)
![sidebarsmall](https://cloud.githubusercontent.com/assets/15949350/20856650/4313520a-b979-11e6-9a2f-03b7050d9c3d.png)

**Comment by dannyhajj** [comment]
This has been reported in #818 and fixed in #823. So when the next version is released, we'll receive the fix for this issue.
