### ISSUE TITLE
Provide an option to display tabs without the preview snapshot next to them. 

### ISSUE THREAD

**Issue by andrea-capri** [bwinton/TabCenter#832]
It would be more useful to have tabs as just a simple title and icon instead of the preview mode as I find it adds a lot of noise to the interface.
I don't think it necessarily should be a default but there should be an option to use the condensed view that already exists when you open more than x number of tabs

**Comment by dannyhajj** [comment]
I'd like to point out that once you have enough tabs to fill the your window's height, the tabs collapse into smaller ones with just the title and favicon. Though it'd be nice if we can have an option to disable the preview completely.
FWIW, I never noticed this behavior until I read this ticket.

**Comment by andrea-capri** [comment]
Yeah, but filling a 4K monitor takes a lot of tabs it would just be more convenient I guess.

**Comment by mattyc3** [comment]
I agree with this as a feature request. I like using tabs completely minimized. I prefer not to use auto-collapse as I also find it intrusive, although I can see its usefulness with managing a LOT of tabs.

My problem is that keeping tabs in minimized view, I have no close buttons. I migt not keep them minimized if previews were able to be toggled, so that I can also have my close buttons visible.

**Comment by Keith94** [comment]
Solution here: https://github.com/bwinton/TabCenter/issues/439#issuecomment-238034669

**Comment by arvenil** [comment]
... but why make them so small. 

This basically makes it worse copy of TabTree https://addons.mozilla.org/nn-NO/firefox/addon/tab-tree/ which is amazing but I was excited about trying out addon that has bigger miniatures, sadly it's either tiny (which makes i useless) preview or even tinier icons. I really would love to see browser that treats webpages like apps. Big app icons, and then maybe after clicking, a list of sub-pages.

**Comment by bwinton** [comment]
@arvenil: While that would be an interesting idea, it's not what this experiment is intended for.  Perhaps a future experiment will go in that direction…

Also, thinking about it, we're really not going to implement this in the current add-on, so I'm going to close this bug.  Thank you all for your comments!
