### ISSUE TITLE
Tab center width resetting

### ISSUE THREAD

**Issue by Tsmith18256** [bwinton/TabCenter#835]
As of recently (maybe the last week or so), the width of my tab center keeps resetting every time I open the browser for the first time. If I open the browser, close it, then open another one, it doesn't resize; it just resizes every time I open the first one for the day.

I have my width set to pretty narrow, so that you can just see the favicons and each tab is a square, but it keeps returning to full width, showing the tab preview and text.

I have observed this behaviour on both my Windows machine at home and my Mac at work, so it is not isolated to one machine.

**Comment by ericawright** [comment]
this should be fixed as of 1.29 are you still bale to reproduce?

**Comment by Tsmith18256** [comment]
Not getting it on the Mac at work; I will confirm tonight if it is fixed on Windows as well.

**Comment by Tsmith18256** [comment]
Yep, working on my Windows machine. Thanks!
