### ISSUE TITLE
upper and lower arrow to change the tabs

### ISSUE THREAD

**Issue by mMARUF** [bwinton/TabCenter#839]
It is a feature request. We we are using TabCenter and in a position when the tab center is selected, it would be cool if we can switch  current tabs by using upper and lower arrow form keyboard.

**Comment by ericawright** [comment]
Some shortcuts actually already exists. As we try to follow the default behavior of tabs. `ctrl-tab` and `ctrl-shift-tab` will cycle through your open tabs (I believe onall OS). As well as a second way on mac with `cmd-shift-{` and `cmd-shift-}`.
