### ISSUE TITLE
Closing tabs using application close button

### ISSUE THREAD

**Issue by JamieOglethorpeEPS** [bwinton/TabCenter#850]
Closing a minimised left tab as provided by the test pilot can be fiddly. It will be easier to use the browser close button at the top right, and for the multi-tab close dialog to offer the option to close the current tab in addition to the other options.

While we are at it, the option to close all tabs **except for** the current tab would also be useful.

**Comment by ericawright** [comment]
There is an option to "close other tabs" on the menu that appears when you you right-click on the tab. 
As for using the browser close button - we are trying to mimic the default behavior of tabs, and that could cause a lot of confusion for people expecting the entire browser to close.
