### ISSUE TITLE
Fade out tab label on overflow instead of ellipsis

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#854]
[Bug 658467](https://bugzilla.mozilla.org/show_bug.cgi?id=658467) recently landed in Nightly, and the vertical tab bar is lacking this improvement. Will it be added?

![tab-title-fade](https://cloud.githubusercontent.com/assets/5490615/21381813/4826e062-c712-11e6-89a1-b99cddcd6c21.png)

**Comment by SoftVision-PaulOiegas** [comment]
That would be nice. 👍  Haven't noticed it on Nightly.
