### ISSUE TITLE
Tabs always have overflow="true" attribute set

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#863]
Even with only one tab open, DOMi still reports `overflow="true"` attribute is set:

![firefox_2016-12-26_13-18-32](https://cloud.githubusercontent.com/assets/5490615/21486710/e34db520-cb6d-11e6-9d53-e53ae063c97a.png)

**Comment by ericawright** [comment]
yes, that was done as a work-around in this PR https://github.com/bwinton/TabCenter/pull/575
in order to fix: #273 and #492

**Comment by Keith94** [comment]
Well is there any other attribute that can define if a scrollbar is present or not? It's useful because I have some CSS modifications that rely on that sort of thing.
