### ISSUE TITLE
Pin button has the wrong tooltips

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#866]
After initial install from Test Pilot (and after restarting Firefox) the tooltips are shown like this.

![firefox_2016-12-29_09-41-17](https://cloud.githubusercontent.com/assets/5490615/21550027/3c0fa04e-cdab-11e6-920c-828372a06c9e.png)
![firefox_2016-12-29_09-41-35](https://cloud.githubusercontent.com/assets/5490615/21550029/3ca0a846-cdab-11e6-8a51-fbf9d02ead41.png)

**Comment by ericawright** [comment]
Thank you. This has been fixed and will be out with the next release.

**Comment by Keith94** [comment]
I installed the latest build from master, but tooltips are like this. Am I missing something?

![firefox_2016-12-30_11-39-45](https://cloud.githubusercontent.com/assets/5490615/21571499/cfc4191c-ce84-11e6-9286-55c7b554ab71.png)

**Comment by ericawright** [comment]
you may need to restart your browser, or if you haven't, run `npm run locales` before you bundle the xpi

**Comment by Keith94** [comment]
When I use `npm run locales` in Git Shell, it says something like.

```
> ./genlocales

'.' is not recognized as an internal or external command,
operable program or batch file.
```

I'm not sure why.. :(

**Comment by bwinton** [comment]
Are you on Windows, by any chance?

**Comment by Keith94** [comment]
>Are you on Windows, by any chance?

Yes

**Comment by bwinton** [comment]
Hmm.  I've only been developing Tab Center on Mac OS.  If you try using the Windows Subsystem for Linux, it may go better.  Or you could try running `node genlocales`, and see if that works.

**Comment by Keith94** [comment]
When using `node genlocales` there's an error `SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

> If you try using the Windows Subsystem for Linux, it may go better

How do I use it?

**Comment by bwinton** [comment]
Which version of node are you using?  And I think the Windows Subsystem for Linux will require more explanation than I can give here.  If you wanted to try googling for it, there's a bunch of info about it in various places.  (It's Windows 10-only, if that makes a difference.)

**Comment by Keith94** [comment]
I think it's node 4.4.7.

**Comment by bwinton** [comment]
Yeah, I'm on 7.3.0.  If you wanted to try upgrading, that might fix it.

**Comment by Keith94** [comment]
Thanks, upgrading did do the trick! Now `node genlocales` works perfectly for me, but `npm run locales` does not work.

**Comment by bwinton** [comment]
Yeah, that part is still Mac OS only.  If you change ``package.json` to run `node genlocales` and it works, I bet we would accept a pull request for that…  😉

**Comment by Softvision-CristinaBadescu** [comment]
I managed to reproduce this issue on latest Firefox Developer Edition 56.0b12 and Beta 56.0.
This is the list of the buttons that seem to be affected by the wrong strings in the tooltips: "Move tabs to the top", "Move tabs to the side", "Shrink sidebar when not in use" and "Keep sidebar open".
I also noticed that "Close Tabs Below" option from the context menu is wrongly displayed.
For more details, please see the following screen recording of the issue: https://goo.gl/ggdgok

**Comment by ericawright** [comment]
@Softvision-CristinaBadescu thank you, this is an issue with the xpi that I had attached, as I built it incorrectly. It is now fixed.
