### ISSUE TITLE
Web extension doubts

### ISSUE THREAD

**Issue by daiheitan** [bwinton/TabCenter#868]
As stated in mozilla's addon blog, only addons based on web extensions will be loaded at the end of 2017. We all know that web-ext's major limitation is you could not modify firefox UI like it is in the old ways.

Does this mean that TabCenter will be terminated after a year or so, as it is JPM based? I'm considering about develop an addon which also tweaks the default UI.

Thanks a lot.

**Comment by bwinton** [comment]
Short answer: Yes.

Longer answer: I've been talking with the people implementing WebExtensions for a while now, and they are committed to [adding the APIs](https://bugzilla.mozilla.org/show_bug.cgi?id=1208596) necessary to support something like TabCenter (or TreeStyle Tabs, or any of the other side-tabs add-ons).  I don't know their final timeline, but I would be very surprised if the new APIs weren't available before we turned off old-style extensions, and I have already started working on [a new branch](https://github.com/bwinton/TabCenter/tree/webext) that implements TabCenter as a WebExtension.

Having said all that, it's likely that at some point in the future, TabCenter will no longer be developed, and at that point, we'll recommend people switch to one of the other side-tabs add-ons.  I don't know the timing for that, either, and which add-on (or add-ons) we recommend is still to be discussed, but just so you know, TabCenter isn't something that will live forever.  (I mean, it _is_ open source, so if people were interested, I guess they could take over maintaining it.  I would be more than happy to help with that, if someone stepped up. 🙂)

Thanks for your question!

**Comment by daiheitan** [comment]
Thanks for the reply. It's a complicated feeling to see firefox going on this way. I will start my add-on anyway.

**Comment by bwinton** [comment]
You're welcome.  It's complicated on the Mozilla side, too, but I _think_ WebExtensions are a better way forward than the previous technologies…  As a side note, if you want any help with your add-on, feel free to email me at bwinton at mozilla.com!  I don't know how much I'll be able to do, but I'm happy to share the knowledge I have, and help people propose new APIs for things they can't do yet.  🙂

**Comment by lkraav** [comment]
Heya. 10 months later, is there a more up to date tracking issue on this somewhere? I just updated to FF57b3, everything is quite smooth but of course Tab Center, the best thing since sliced bread, is gone now.. :)

**Comment by bwinton** [comment]
[Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/) is the WebExtension I've been pointing people to recently. It's pretty good, I think, and has been able to do some stuff Tab Center couldn't.
