### ISSUE TITLE
Strange forced scroll down pins tab center view to bottom

### ISSUE THREAD

**Issue by supnah** [bwinton/TabCenter#873]
Strange behavior seen. I've seen it multiple times. This time it was triggered by turning on the "Reverse Tab Order" option. It did not resolve by turning off "Reverse Tab Order", and was only resolved by quitting and restarting Firefox. Upon restart, I turned "Reverse Tab Order" back on and there were no problems. Other times I've seen this occur, I do not think it necessarily had anything to do with Reverse Tab Order, but can't remember. Attaching a gif of the behavior - you can see me scroll up, and then all of the down scrolling is happening without user input. It just keeps forcing to the bottom of the scroll bar.
![n1ylxqu - imgur](https://cloud.githubusercontent.com/assets/1953038/21628505/db4f20da-d1d4-11e6-8a66-a93d02bd7d82.gif)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @supnah and thanks for reporting this. I think this is generated by trying to drag and drop tabs outside the sidebar trough its top or bottom. Or at least I managed to reproduce it like this in #841.  Maybe you can confirm this using my steps from the bug.

Anyway, if this is the same issue, then it's already fixed on the latest dev version but didn't landed yet on the production. I'll close this one, but if this still occurs for you after the new version is released, please reopen it and provide additional info if you'll have any.

**Comment by supnah** [comment]
Yes - I think you're probably right. I remember pulling a tab out right around the same time as well, but didn't think about it at the time. I'll keep an eye on it and reopen as you said if it keeps happening after the new version lands. Thanks!
