### ISSUE TITLE
[Reverse Tab Order] Links opened in new tabs from a pinned tab are wrongly positioned at the bottom of the Sidebar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#881]
[Affected versions]:
- Firefox 50.1.0 and above
- Tab Center 1.29.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Tab Center add-on is installed on a new clean profile.
- Reverse tabs order option is checked from "about:addons" page for Tab Center extension.
- Have at least 3 tabs opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new tab and navigate to a https://triagebot.mozilla.org/dashboard.html.
3. Pin the tab and open one of the links from the page in a new tab.
4. Observe the newly opened tab's position in the Sidebar.

[Expected result]:
- The tab is opened under the pinned tab.

[Actual result]:
- The tab is opened under the pinned tab until it has finished loading, then it is moved to the bottom of the Sidebar.

[Notes]:
- Here is a screen recording of the issue: 
![links opened in new tabs from a pinned tab are wrongly positioned at the bottom of the sidebar](https://cloud.githubusercontent.com/assets/18304511/21683815/ac008842-d363-11e6-8e09-1e92bea62a63.gif)

**Comment by ericawright** [comment]
> The tab is opened under the pinned tab until it has finished loading, then it is moved to the bottom of the Sidebar.

interesting, though it seems to move to the bottom once the mouse enters the sidebar.

**Comment by db48x** [comment]
Yes, it only jumps to the bottom when the mouse enters the sidebar. However, if you pay attention while using control-tab/control-shift-tab you'll see that it's actually positioned in the tab order as if it were already at the bottom.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Tab Center (built on 2/15/2017).
