### ISSUE TITLE
Won't Enable

### ISSUE THREAD

**Issue by davehb0909** [bwinton/TabCenter#886]
Receiving error: "Uh oh. ⁨Tab Center⁩ could not be enabled. Try again later."  It's been over two hours.
Thanks!

**Comment by bwinton** [comment]
This _sounds_ like a bug in Test Pilot…  Could you open the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console), and see if there are any Tab Center-specific errors there, and if not, file a bug [over here](https://github.com/mozilla/testpilot/issues) instead?

**Comment by SoftVision-PaulOiegas** [comment]
I think you were trying to enable the experiment while the Test Pilot team was doing a production deploy with some changes. 
Can you please go in "about:addons" page and manually check for updates from the top right wheel button on the page ? And afterwards try to enable again Tab Center. If the issue still persists, please reinstall Test Pilot and retry. 
Let me know of the results so I can inform the team if you still have an issue with this.

Thanks !
