### ISSUE TITLE
mouse wheel changes which tab is selected

### ISSUE THREAD

**Issue by db48x** [bwinton/TabCenter#888]
When I try to scroll up or down in the list of open tabs, it instead changes which tab is selected. It won't move the selection onto a pinned tab though (which would be an odd choice if this were intentional), so at that point I can scroll again (until I try to scroll back up).

This is in addtion to bug #880.

**Comment by ericawright** [comment]
Can you let me know what OS you are on and I assume this is for reverse and regular tabs?

**Comment by db48x** [comment]
The OS is Linux, and indeed it only happens for reversed tabs.

**Comment by ericawright** [comment]
confirmed - looking into it, thank you!
