### ISSUE TITLE
tabcenter continually scrolls back to the top of the tab list

### ISSUE THREAD

**Issue by db48x** [bwinton/TabCenter#892]
Fair warning: this is not going to be a great bug report, because I don't have a precise way to reproduce the problem.

The arrowscrollbox lets you scroll around by hovering over the up and down arrows. However, it has a bug (which I have seen often and reported in the past) that causes it to occasionally lose track of the user's mouse cursor (it misses a mouse event or something). It will then think that it should keep scrolling forever, even as you scroll the other way. You can sometimes see this in Firefox's old-school bookmarks menu, for instance.

I was dragging some tabs around today to rearrange them and got into this same state with TabCenter. Any time I select an old tab that is off the end of the list it immediately starts scrolling back to the top. I don't think it does this very often, because I moved several tabs around before I noticed it happening. I also can't get it to stop; I'm going to have to restart Firefox at some point. Once I do I'll try more carefully to reproduce it.

I suspect that TabCenter might be more fragile in this way than the bookmarks menu, because of the way the arrow buttons are hidden in TabCenter.

**Comment by SoftVision-PaulOiegas** [comment]
Maybe I'm wrong, but isn't this duplicate to my issue #841 ? If yes, this is no longer happening on latest dev build and probably will be available on the next released build.

**Comment by db48x** [comment]
It's possible. In my case it was slowly scrolling up, not jumping back to the top. Either way though, the cause is the same.

**Comment by SoftVision-PaulOiegas** [comment]
Seems so. Anyway, thanks for the report ! 
I'm gonna close this until the dev version is released. If you still encounter it after, please reopen it and let us know.
