### ISSUE TITLE
Left border not animated on all tabs

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#897]
Selecting pinned tabs has an animation on the left-border, but non-pinned tabs doesn't have this animation (on Windows).

![2017-01-18_05-32-54](https://cloud.githubusercontent.com/assets/5490615/22066102/3a8ade2e-dd40-11e6-9995-42a9efecf770.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Tab Center build (built on 3/2/2017).
