### ISSUE TITLE
Undo close tab causes unnecessary scrolling

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#901]
## Steps to reproduce
1.  Open enough tabs that the tab sidebar is vertically scrollable
2. Close a tab
3. Press Ctrl+Shift+T to reopen the closed tab

## Expected result
The tab sidebar is only scrolled if necessary to bring the reopened tab into view

## Actual result
The tab sidebar scrolls even if it's not necessary to bring the reopened tab into view

## Environment
* Platform (OS): Windows 8
* Version of Firefox: 53.0a1

---

Screencast of the issue: https://a.pomf.cat/svixdu.mp4

**Comment by ericawright** [comment]
I can't seem to duplicate. I've tried with the drawer opened and hiding, using the xpi from master and the test pilot version.
Also Firefox 53.0 and Win 8.1. Have also tested on win 10.
Is there anything else that might be affecting this?
