### ISSUE TITLE
tab center

### ISSUE THREAD

**Issue by Aiswarya-ksr** [bwinton/TabCenter#902]
the feature does not get enabled!

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @Aiswarya-ksr, could you please do a manual check for updates for the Test Pilot addon in about:addons? 
Go to about:addons, click the Extensions tab, right click on the Test Pilot addon and click "Find Updates".

**Comment by Aiswarya-ksr** [comment]
@SoftVision-CiprianMuresan  .. tried it out..but there are  no updates found...

**Comment by SoftVision-CiprianMuresan** [comment]
Could you please give us some more information about your sistem?
OS, Firefox version, Test Pilot version?

Do other experiments from the Test Pilot site install correctly? Or is it just Tab Center that has this issue?

**Comment by Aiswarya-ksr** [comment]
its the firefox developer edition on windows 8..all other experiments are working correctly, and only tab center seems to be a problem.

**Comment by SoftVision-CosminMuntean** [comment]
I haven't managed to reproduce this issue, Tab Center is correctly enabled.

@Aiswarya-ksr  what version of Test Pilot do you have? In order to find the version go to "about:addons" and from "Extensions" section double click on Test Pilot. 
Also, the issue is still reproducible even if you restart the browser?

**Comment by Aiswarya-ksr** [comment]
test pilot 0.9.3-dev-837c6a0
the problem persists even after restarting the browser

**Comment by SoftVision-CosminMuntean** [comment]
Do you have any anti-virus or firewalls installed?  We had a few issues where users could not install the experiments until they disabled the antivirus.

If you uninstall Test Pilot and reinstall it, Tab Center can be enabled?
