### ISSUE TITLE
Tooltip of shrunken tab side bar button shows technical stuff

### ISSUE THREAD

**Issue by beingalink** [bwinton/TabCenter#909]
[image](https://www.dropbox.com/s/9pzjhlwx6rlqwzq/Screenshot%202017-01-26%2019.16.34.png?dl=0https://www.dropbox.com/s/9pzjhlwx6rlqwzq/Screenshot%202017-01-26%2019.16.34.png?dl=0)

**Comment by ericawright** [comment]
thank you, this has actually been fixed, just not released yet!
