### ISSUE TITLE
Allow Tab Center to be placed on the right hand side of the browser window

### ISSUE THREAD

**Issue by petertrotman** [bwinton/TabCenter#921]
I'm enjoying using the Tab Center, but I would much prefer to place it on the right hand side of the browser window rather than the left. I've searched the options but this isn't one that I can find anywhere.

Hopefully this won't be too demanding to implement.

Cheers.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @petertrotman, thanks for the report, however this is a duplicate of #7.
