### ISSUE TITLE
Tour: Init with multiple windows

### ISSUE THREAD

**Issue by ericawright** [bwinton/TabCenter#930]
@phlsa:  @bwinton and I were discussing how to initialize tab center for Shield.

On install the tour starts - in the primary window - with tabs on top, and guides the user into tabs on the side (provided the user follows it). The question is what state should we start secondary windows - tabs on side or top?

on side: 
- forces user to use it
- circumvents the tour
- if the user follows the tour they will end up with all windows in the same state
- has potential to be very confusing if they do not follow the tour ("why are my windows different?")
- we chose this option for test Pilot since we figured that users have opted in and will be less surprised if they don't follow the tour

on top:
- if user does not complete the tour windows will all be in similar states
- if user completes the tour they should be able to figure it out when they see the icon in other windows. 

combination (windows with more tabs get side, less get top):
 - good for usability
 - user may not see the pattern and will be confused

**Comment by phlsa** [comment]
Let's have all windows start with tabs on top. That way, the behavior is consistent between windows :)
