### ISSUE TITLE
[Reverse Tab Order] Wrong tab gets selected when toggling top and side tabs

### ISSUE THREAD

**Issue by ericawright** [bwinton/TabCenter#934]
STR: have tabs in reverse, click to toggle to tabs to the top

ER: The selected tab does not change when toggling between top and side tabs.

AR: The tab in the same position get selected after the tabs are re-sorted when toggling between top and side tabs.

**Comment by SoftVision-CiprianMuresan** [comment]
I might be wrong, but isn't this a dupe of #849?

**Comment by ericawright** [comment]
@SoftVision-CiprianMuresan yes it is! Thank you. I'd lost that one.
