### ISSUE TITLE
feature request: keyboard shortcut to open and close the drawer without needing to mouse hover

### ISSUE THREAD

**Issue by lundjordan** [bwinton/TabCenter#95]
:)

again please close if you would not like to support this or it's being tracked elsewhere

**Comment by lundjordan** [comment]
s/drawer/sidebar

**Comment by bwinton** [comment]
Yeah, we _should_ figure out what the keyboard shortcuts for this will be…

**Comment by johngruen** [comment]
Let me know what this is and i'll put it in the onboarding tour

**Comment by bwinton** [comment]
I think we're going to go with ⌘-⇧-L (or ^-⇧-L on Windows/Linux)…

**Comment by bradmont** [comment]
I also would really like this. Regarding the actual shortcut, as a Ubuntu user, my first reflex was to try and treat it like the dash in Unity, where you can just tap the meta key to open it. Would it possible to toggle it with a simple tap of the ctrl key? Would that make it too central?

**Comment by vkareh** [comment]
I agree with @bradmont here, I mostly change tabs using Ctrl + PgUp|Dn - it would greatly improve usability if Ctrl and Ctrl+Shift (for moving tabs) would automatically expand the sidebar so that on the next key (PgUp|Dn) you can see what's happening
