### ISSUE TITLE
Fullscreen (f11) on Windows

### ISSUE THREAD

**Issue by ericawright** [bwinton/TabCenter#951]
TC should hide and the window controls should go away when in f11-fullscreen.

When entering fullscreen, this happens as expected. 

When entering fullscreen first with tabs-on-top, then toggling it to tabs-on-side, TC will stay around and the window controls will be mashed onto it.

**Comment by SoftVision-PaulOiegas** [comment]
Uh, nasty, I can reproduce it too. We had something like this before (#509), but back then we didn't had the tabs on top option.
