### ISSUE TITLE
[Reverse Tab Order] Links opened in new tabs are wrongly opened at the top of the Sidebar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#956]
[Affected versions]:
- Firefox 51.0.1 and above
- Tab Center 1.29.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Tab Center add-on is installed on a new clean profile.
- Reverse Tab Order is enabled in about:addons->Extensions->Tab Center
- Have at least 4 tabs opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Focus the last tab in the Sidebar and navigate to https://en.wikipedia.org/wiki/Main_Page. (or any other website)
3. Open a link in a new tab and observe the tab's behavior in the Sidebar.

[Expected result]:
- The new tab is opened above the focused one.

[Actual result]:
- The new tab is opened on top of all the other tabs.

[Notes]:
- The issue is only reproducible if tabs are in reverse order.
- The issue is reproducible regardless of the way you open a link in a new tab. (Ctrl/CMD+Click, Middle Click or through the context menu option)
- Here is a screen recording of the issue: 
![links opened in new tabs are wrongly opened at the top of the sidebar](https://cloud.githubusercontent.com/assets/18304511/23303317/03704b1c-fa9c-11e6-89cb-68f4f6f103cc.gif)

**Comment by ericawright** [comment]
:(

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Tab Center version (built on 3/3/2017).
