### ISSUE TITLE
Unusable with RightBar

### ISSUE THREAD

**Issue by xtotdam** [bwinton/TabCenter#962]
I like the whole idea very much but 
I am used to open all my bookmarks in a side panel, which is on the left by default, and I moved it to the right with RightBar (https://addons.mozilla.org/ru/firefox/addon/rightbar/)
TabCenter does not work correctly for me:
- with sidebar open
![default](https://cloud.githubusercontent.com/assets/5108025/23331481/f9a013a6-fb77-11e6-9388-a757f879b0b8.png)
- with it open and tabs panel unfolded (which is ${strings.sidebar.Shrink}, button next to 'move tab top' (I have russian locale))
![default](https://cloud.githubusercontent.com/assets/5108025/23331478/f0443b0c-fb77-11e6-899f-949ea6315968.png)

Not only there is too much unused space, but 'Back' button hides, which is bad

**Comment by ericawright** [comment]
closing as it is on the list - thank you
