### ISSUE TITLE
Change "move tabs to the top" with search

### ISSUE THREAD

**Issue by ShalokShalom** [bwinton/TabCenter#975]
The option to find tabs via the search function is superb and i cant use it currently without destroying my current width. So, in order to find something, do i need to expand the view, find the tab and rearrange it, which is of course a little bit inconvenient, i hope you understand that. 

![screenshot_20170301_112854](https://cloud.githubusercontent.com/assets/6344099/23456089/50b2009e-fe72-11e6-8aa4-e22a881ac67e.png)

So, my idea is simply to replace "move tabs to the top" with the search function in the smaller views, so once the user decide to shrink the width. 

Since "move tabs to the top" offer the exact same function as the 	deactivation of TabCenter, is this feature a bit superfluous in general. 

I think its quite nice to display the input field once the loupe icon get clicked by simply overlapping the toolbar with it and another solution is to create an additional line for it over the first tab?

**Comment by SoftVision-CiprianMuresan** [comment]
We already have something that might be related to this. 
#969 would enhance all the options from the sidebar when it is narrowed that much. Do you think this particular scenario would also be improved by #969?

**Comment by ShalokShalom** [comment]
When "overflow menu icon" means the same as what i describe as "overlapping the toolbar", then yes.

**Comment by SoftVision-CiprianMuresan** [comment]
This is an example of an overflow button:
![overflow button](https://cloud.githubusercontent.com/assets/18304511/23462437/819d9316-fe96-11e6-9972-2bb3c8041d9a.png)
Basically, if there isn't enough room to have all the buttons visible, a single button would be created (an overflow button). If the button is clicked, all the options would be revealed in a way similar to the attached picture.
What do you think?

**Comment by ShalokShalom** [comment]
Yes, so long as i can type, once the overflow button is triggered.

**Comment by ericawright** [comment]
while the overflow menu might still be introduced - at a basic level I agree with having the search have priority vs. the toggle

**Comment by SoftVision-CarmenFat** [comment]
Tested this on the latest version of Tab Center (built on 3/21/2017) and the Search field is displayed until the sidebar becomes too shrink for it. After that, the "Move tabs to the top" button appears instead of the Search field.

![searchf](https://cloud.githubusercontent.com/assets/26000308/24141629/baa048a2-0e2c-11e7-86f2-943fe21de344.gif)

**Comment by ShalokShalom** [comment]
Great ^.^
