### ISSUE TITLE
Unable to edit Bookmarks on Bookmarks Toolbar

### ISSUE THREAD

**Issue by Annexoid** [bwinton/TabCenter#978]
After enabling the TabCenter, all options (eg Properties etc) are greyed out while right clicking on any of the saved bookmarks on the Bookmarks Toolbars.

However, moving tabs to the top and restarting Firefox solves the issue (until the tabs are moved to the side again)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @Annexoid and thanks for the report ! However, this issue was already tracked and fixed in #583 and will be included in the next release of Tab Center. Bare with us a few more days please. 😃
