### ISSUE TITLE
Highlight is gone

### ISSUE THREAD

**Issue by djmitche** [bwinton/TabCenter#984]
I use the darker theme, and with the update that occurred a few hours ago, I no longer have any indication of which tab is active.  Actually, now that I look I think there is a slightly lighter gray:

![screenshot from 2017-03-03 15-06-27](https://cloud.githubusercontent.com/assets/28673/23567166/fc8c92c4-0022-11e7-988f-007d40ad1cb5.png)

Please bring back the nice bright highlight bar!

**Comment by miloskroulik** [comment]
I, for one, welcome our new lighter gray backgrounds. I'm using Developer theme.

**Comment by djmitche** [comment]
@miloskroulik can you tell at a glance which tab I have selected above?

**Comment by miloskroulik** [comment]
@djmitche The Github one?

**Comment by djmitche** [comment]
The "?" in your response says it all!

This is a UI hint which should be visible in peripheral vision, not one that requires me to lean into my screen and adjust the backlight.

**Comment by miloskroulik** [comment]
Once upon a time, I used the Treestyletab extension, which had several themes included. Perhaps something like that would be the way?

**Comment by djmitche** [comment]
Actually, now that I look at the preferences for the add-on, there appears
to be no choice of themes anymore.  Am I somehow "locked" into the dark
theme now?

**Comment by ericawright** [comment]
@djmitche  it should look like this:
<img width="267" alt="screen shot 2017-03-03 at 4 14 12 pm" src="https://cloud.githubusercontent.com/assets/10803178/23569337/c1b18f6a-002c-11e7-823c-bc83a9090cf8.png">

Can you give me more info on your OS as it should not behave the way you are describing. Also, this might have something to do with the update, so if you happen to restart and it changes please let me know.

**Comment by djmitche** [comment]
Ah, that's the theme I was remembering, thanks.  I'm not losing my mind after all :)

I'm on Linux, Firefox 51.0.1.

**Comment by djmitche** [comment]
Ah, and after a browser restart, the highlight appears to be back.  Go figure :(

**Comment by djmitche** [comment]
Also, the animations of that highlight bar are neat.  So I guess this is a restartless-upgrade issue -- not sure if it's worth keeping open, then.

**Comment by ericawright** [comment]
Sometimes restartless updates are not full restartless :(

**Comment by ericawright** [comment]
No, I'll close it. It's good to know though - we seem to have a few issues every release about something not quite restarting properly.
