### ISSUE TITLE
Tabs Tree Options

### ISSUE THREAD

**Issue by Kruzifixium** [bwinton/TabCenter#989]
I wanted to ask if there is any possibility to add some tree-style possibilitys.

That tabs, opened as new tabs from a existing tab are sorted in something like a folder for that tab, like the try with the "Tree Style Tab" Addon (but not perfectly working).
with this oppurtunity you'd be able to close one tab with the tabs, opened out of the "main" tab, not only the tabs opened afterwards.

sometimes you start working with a tab you've opened long time before and atm you've to close every single tab, when you won't kill all tabs sorted afterwards.

it would be awesome, if you could add this feature inside tab center :)

(sorry for my bad english...)

**Comment by ericawright** [comment]
Sorry, we don't have the resources to implement these types of features.
