### ISSUE TITLE
unsafe CPOW usage

### ISSUE THREAD

**Issue by pdehaan** [bwinton/TabCenter#99]
Also randomly spotted in Browser Console. I'm still trying to figure out [what CPOWs are](https://mikeconley.ca/blog/2015/02/17/on-unsafe-cpow-usage-in-firefox-desktop-and-why-is-my-nightly-so-sluggish-with-e10s-enabled/) and if this is legit or just a red herring.

![browser_console](https://cloud.githubusercontent.com/assets/557895/14991935/a2e7e36c-1118-11e6-80c7-e1899ddfa2eb.png)

**Comment by bwinton** [comment]
So, in theory these are things we want to fix.  Can you click on the "verticaltab…" at the end to get actual line numbers and paste those here?  (But also, it's kinda a post-launch thing, so marking as such.)

**Comment by pdehaan** [comment]
Ah yes, sorry... It's [verticaltabs.jsm:120](https://github.com/bwinton/VerticalTabs/blob/master/verticaltabs.jsm#L121) -- although, when I click on that result, it takes me to line 121 in the debugger, so it's somewhere in that 2-3 lines.

**Comment by bwinton** [comment]
These seem to be fixed, probably largely by the switch to the Add-on SDK…  🙂
