### ISSUE TITLE
Window height changes when switching tab bar position from top to side

### ISSUE THREAD

**Issue by ugggf** [bwinton/TabCenter#990]
It happens on Firefox startup (as tabs initially appear on top before automatically move to the side) or when switching the tab bar position. It's annoying if you wat Firefox window to occupy the whole height of the screen but not be maximized. Happens on my Linux (Mint 18.1 Cinnamon).

**Comment by SoftVision-PaulOiegas** [comment]
Hi @ugggf  and thanks for your report. Yeah, I see this behavior everyday and it also occurs on Windows and Mac OS. It looks like the Tab Center extension takes some time to initialize, but I'm not sure if there is something the devs can do here. 
Probably this won't happen if Tab Center will end up as a feature in Firefox (praying for that 😃). 

@ericawright any thoughts on this ?

**Comment by ericawright** [comment]
Sorry for the late response, I looked at this previously, and no it doesn't look like there is anything we can do about it.
