### ISSUE TITLE
Side Tab does not close and remains as a blank space 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#991]
This issue is cloned from [Test Pilot #2285](https://github.com/mozilla/testpilot/issues/2285).

>Issue for Side Tab 
>
>Issue : After clicking X on side tab for a window , The tab still remains with Blank space. Attached screen shot for your reference .
>![sidetab](https://cloud.githubusercontent.com/assets/22630878/23597608/55fb2c60-025a-11e7-86f2-605305ba9778.png)

**Comment by ericawright** [comment]
This issue has been reported in #985 for ESR 45.7.0. 
@ayazmaqbool can you give more detail on what Firefox version you are using?

**Comment by ayazmaqbool** [comment]
I am using ESR 45.7.0 @ericawright

**Comment by ericawright** [comment]
thank you, closing in favor of #985
